### ISSUE TITLE
Stop Download not working correctly (sometimes) and some other Bugs

### ISSUE THREAD

**Issue by tox2** [n0ix/SFDL.NET#101]
Das ganze ist nicht unbedingt ein Funktionaler BUG der Session, sondern mehr ein Optik bug bzw. Seltsames verhalten. Da jetzt mehrere Sachen auftreten würde ich sagen es ist Ansichtssache was ein Bug ist und was nicht. :) 

1. Markiert mehr als 3 Files welche geladen werden (es funzt zwar der download aber warum markiert er sachen die erst an die reihe kommen)
2. Wenn man mit Sub Package ladet wird der Speedy bei mehreren Paketen im letzten paket Ordner erstellt wäre der SFDL HauptPaket ordner nicht besser ?
3. Wenn man 2 Container wie im Video drinnen hat erstellt er obwohl nur ein Container geladen wird. einen Speedy für den nicht geladen mit Random Zahlen 

http://www.xup.in/dl,98616979/local_(06).mp4/
http://www.xup.in/dl,10488386/log_-_Mystery_BUG.log/

-----------

Hab auch nochmal versucht die Sachen nachzuvollziehen in einem Längeren Video 
das "...(07).mp4" mit 11:58 und "...(08).mp4" mit 2:50 da treten die selben auf wie oben nur das noch weitere seltsame Sachen passieren

4. der Loader lässt 2 parts nicht demarkieren weil der Status auf loading ist obwohl der download gestoppt ist.
5. Dann steht da eine Meldung und verschwindet einfach nie. Speedy erstellt | 19,82 MB .... 
6. wenn zb. wie bei mir jetzt ein Rar Archiv ohne das Haupt Rar da ist weil, es auch solche ab und zu gibt wo das Hauptarchiv mit part1.rar beginnt werden diese nicht entpackt. cRark wäre aber in der Lage dazu.
7. Dann hat er auch einmal seltsamer weiße 2 unfertige downloads nachdem ich oben auf stopp drückte demarkiert . :D 
8. Falls die Frage auf kommt warum das mit Multi Select manchmal im Video geht manchmal nicht ist weil ich das mit SPACE und ENTER versucht habe. Jedes mal Space drücken nimmt er die Zuletzt gewählte Zeile und markiert nur diese statt alle gewählten. (bei ENTER macht er ein invert von allen) Siehe video (05)
9. zu guter letzt wäre es nicht besser wenn ein Unrar erfolgreich ist auch denn Status abzuändern ? das zb erfolgreich entpackt wurde im status beim jeweiligen Filepart steht ? Siehe video (08)

Video (07): https://mega.nz/#!4gohBb5K!Keq9F1NUCpA-Y4sfjgo7PhuHypIvG97SYBEHVaNKYx0 
PW (tester) Link zum TestArchivSFDL:  http://www.xup.in/dl,13871958/SFDL_Archiv_TESTCases.sfdl/
http://www.xup.in/dl,50947084/local_(05)Space_vs_Enter.mp4/
http://www.xup.in/dl,14640773/local_(08)_cut.mp4/
http://www.xup.in/dl,19822636/log_-_VideoTime.log/

**Comment by n0ix** [comment]
Hallo, ich versuche das mal alles etwas zu Ordnen.

1.) Tut mir leid ich verstehe den Satz leider nicht so recht. Am Video kann ich auch nicht ausmachen was du meinst

2.) Das ist korrekt ,war ich zu faul das anständig zu machen -  dir entgeht auch nichts ;-)

3.) Alles klar - Verstanden und **behoben**

4.) Blöde Sache aber denke ich eine "einmalige". Ich werde versuchen den Stop Prozess zu optimieren.

5.) hängt vermutlich mit Punkt 4.) zusammen (Folgefehler)

6.) Hängt vermutlich ebenfalls mit Punkt 4.) zusammen (Folgefehler)

7.) Werde das mit der Leertaste wieder entfernen

8.) Sehe ich jetzt keinen wirklich vorteil darin. Verstehe aber auf was du hinaus mcöhtest.

**Comment by tox2** [comment]
Ehm ja ist nicht meine beste Beschreibung geb ich zu :D 

1) Der Loader setzt mehr als 3 Part mit dem Status "Download Läuft". Normalerweise sollten die 3 welche geladen werde diesen Status haben und die anderen Parts denn Status "Wartend"

Siehe BILD 1 "Soll" BILD 2 "BUGGY"
BILD 2 wurde bei video (06) Minute 0:22 aufgenommen, man kann dann dort und im späteren video (07) (08) das ganze nochmal beobachten. 

Deshalb hab ich auch die Videos (07)(08) gemacht um dann auch gleich das Bug verhalten einzufangen.
Leider konnte ich nicht ganz nachvollziehen was die genauer Ursache ist um es zu rekonstruieren.
Aber wenn der Loader nur ein SFDL geöffnet hat also einen Container hat. 
Dann tritt das verhalten nie auf.
Erst bei mehreren. Vielleich auch nur mit so einem Multi Paket Container. Auf jeden Fall Mysteriös. :D  
 

![3thread loading](https://cloud.githubusercontent.com/assets/23582323/22899881/a682d072-f22c-11e6-966d-690cfdd30a1c.png)
![3thread loading_buggy](https://cloud.githubusercontent.com/assets/23582323/22899880/a67f0a0a-f22c-11e6-9fab-dd53dcbdaf32.png)

**Comment by n0ix** [comment]
Ok, danke für die erklärung. Schau ich mir nochmal genauer an. Evtl. finde ich etwas.

**Comment by tox2** [comment]
Hab versucht mit der neuen exe vom ProzentSprung, denn Bug mit dem Status mehr als 3 "Download läuft" nachzukonstruieren. Ist mir aber nicht gelungen Scheint behoben zu sein vielleicht hat dieser irgendwie mit denn anderen Bugs was zu tun. Und ist daher auch verschwunden.

**Comment by tox2** [comment]
Hab noch ein wenig probiert bei 5). Es war wohl nur für die eine Session der Fall, bei einer zweiten Session Trat der Fehler nie auf. 
Session jetzt im dem Sinne. Loader geöffnet SFDL s geöffnet Download start stop x mal, und dann wieder geschlossen.

**Comment by n0ix** [comment]
Danke für die Rückmeldung/Infos

**Comment by tox2** [comment]
Ich schließe hier mal da die hier genannten Fehler so in der RC4 nicht mehr existieren. 
Jedoch hab ich andere Aufdecken können, als ich versucht habe diese oben zu reproduzieren :D 
Siehe #109
