### ISSUE TITLE
Status: Filename too long Error, can this be longer ? Bug Report by Combi

### ISSUE THREAD

**Issue by tox2** [n0ix/SFDL.NET#103]
Hab es nur vom Forum hier eingetragen weil es mit dem genannten SFDL File auch in RC3 so ist und das selbe Ergebnis kommt.

**Comment by tox2** [comment]
Hab kurz geguckt wenn der Pfad lokal über die 260 Zeichen lang ist dann kommt der Fehler.
Hab dass ganze anscheinend auch selbst mit der Subfolder Einstellung "Ein" geschafft.
Ohne Sub Folder laden die Parts. 👍

**Comment by n0ix** [comment]
Und wo ist jetzt der BUg? Ist eine Windows limitation...

**Comment by tox2** [comment]
Achso ja ne wollte mit dem Issue einfach fragen ob das der Loader so beschränkt oder wie das zustande kommt, aber wenn es von Windows so ist dann close ich hier mal :D
