### ISSUE TITLE
Execlude Small Files Like NFO,SFV,JPG ?- [Fetarue Request by Hard.Kore-AB]

### ISSUE THREAD

**Issue by tox2** [n0ix/SFDL.NET#104]
Hard.Kore-AB Zitat:
> Ausserdem wolllt ich mal Frage nach einer Funktion die Datein Automatisch ausschließt, wenn ich eine SFDL Lade werden ja oft, NFO,SFV,JPG Datein mit in den Loader geladen. Die möchte ich gerne Automatisch ausschließen zb. Demarkieren, ohne es jedes mal von Hand zu machen. Hoffe ich werde verstanden. 

Dachte mir ich werf das ganze hier rein, ich finde den Vorschlag sogar recht nützlich.
Vielleicht das mann dann die Möglichkeit hat in den Einstellung NFO,SFV,JPG zu ignorieren, und vielleicht sogar das für die Sample Ordner bzw. Rar Files zu machen. 

Natürlich wäre jetzt die Fallback Lösung einfach selbst demarkieren aber wenn der Loader das automatisch macht, kann mann noch schneller laden.

Ob das ganze einfach umzusetzen weiß ich gar nicht.

In dem Sinne 
Gruß tox2

**Comment by n0ix** [comment]
Hatte sowas auch schon im Sinn. Ich denke das ist ne gute  Idee.

**Comment by n0ix** [comment]
Im den Einstellungen kann man nun RegEx Pattern hinterlegen. Diese Items werden dann automatisch **nicht** markiert wenn eine SFDL **geöffnet** wird.

![image](https://cloud.githubusercontent.com/assets/17708302/23330683/7155b730-fb54-11e6-90d4-0b5999548746.png)


RegEx Pattern Beispiele:

- `.*\.sfv`
- `.*sample.*`
