### ISSUE TITLE
Speedreport NAN überschreibt denn vorherigen Speedy

### ISSUE THREAD

**Issue by tox2** [n0ix/SFDL.NET#105]
Kann man das so machen das wenn NAN Speedy kommt, vorher überprüft wird ob ein Speedy vorhanden ist. Damit dieser vorherige nicht überschrieben wird.

Bei mir war dass eben gerade so. Paket geladen einmal kurz gestoppt dann fortgesetzt. Wurde Feritg geladen wunderbar. Dann bemerkt das ich in denn Settings das AutoUnrar deaktiviert hatte kurz aktiviert.
Dann nochmal alle Parts ausgewählt (nur eine Part reichte leider nicht) um die AutoUnrar Chain auszulösen.
Archiv wurde erfolgreich mit dem richtigen PW entpackt. aber dann eben der alte Speedy überschrieben mit einem NAN.

Also mein Vorschlag:

-  NAN Speedy zwar im Loader anzeigen, aber bei vorhandenen nicht überschreiben lassen.

- in einer RC ging das glaube ich, geht jetzt aber nicht mehr, ich hatte es auch mal als Issue. Und zwar die unrar chain wird nicht ausgelöst wenn man nur 1 Part nach lädt. mann muss immer das gesamte Paket durchlaufen lassen.

Hab das ganze auf der RC4 getestet,(wo im Help als versions info wieder 3.0.0.3 RC4 steht) müsste ja dann 3.0.0.4 :P sein.

**Comment by n0ix** [comment]
Das mit der UnRAR ist mir auch schon aufgefallen. Danach wollte ich mal noch schauen.

Das mit dem Overwrite Problem vom Speedreport ist vermutlich etwas komplizierter.

**Comment by tox2** [comment]
Das mit dem UnRAR war glaube ich in #91 der auslöser das man jetzt wieder alle parts markieren muss.
Weil wenn er bei jedem part finished event ja die unrar ausgelöst hat.

Wäre nach dem DownloadSession Complete doch sinnvoller bzw. DownlaodContainerSession Complete
wenn man mehrere Container ladet.

**Comment by n0ix** [comment]
- [ ] Skip Speedreport Generation if nothing was downloaded and there is no existing Speedreport
- [ ] Needs to be fixes: UnRAR only gets fired if all Items are selected

**Comment by tox2** [comment]
Wäre folgendes Möglich, das Nodata Speedy wenn diese erstellt werden, wie in diesem Fall die Status Meldung rein geschrieben wird. In diesem Fall Status "Datei nicht gefunden".
[Nodata_Speedy_LOG.zip](https://github.com/n0ix/SFDL.NET/files/821575/Nodata_Speedy_LOG.zip)

Wobei was noch besser wäre das diese NoData Speedy auch nicht erstellt werden, es wurden ja auch keine Daten geladen und es entsteht nur ein Zombie Ordner auf der Platte. Also das NoData Speedy gleich wie 0MB und NAN Speedys nicht erstellt werden.

Was hingegen toll klappt ist das dieser NoData Speedy nicht überschrieben wird :D 

werde das mit anderen SFDLs aber noch genauer erforschen :D
