### ISSUE TITLE
[Feature] TaskBar Progress, weil die Prozent Anzeige ja jetzt nicht mehr springt :D

### ISSUE THREAD

**Issue by tox2** [n0ix/SFDL.NET#106]
Wäre das einfach umzusetzen mit .net ?
So eine Taskbar Fortschrittsanzeige ist doch nützlich man hat ja denn Loader nicht immer im Auge bzw. die meiste zeit minimiert.

**Comment by n0ix** [comment]
Dürfte nicht allzu schwer sein...
