### ISSUE TITLE
[Feature] Speedreport Variable, PackageName ?

### ISSUE THREAD

**Issue by tox2** [n0ix/SFDL.NET#107]
Könnte man das noch anbieten in denn Einstellung denn die  %%SFDL_DESC%% Beschreibung ist ja nur selten angeben.
Das man dann halt eben auch  %%SFDL_ContainName%% bzw.  %%SFDL_PackageName%%.
In der Speedy Maske automatisch drinnen hat bzw. angeben kann.

**Comment by n0ix** [comment]
Package Name wird schwierig weil das können ja mehr als 1 sein. ContainerName könnte man nehmen, weiß aber vermutlich der normale Benutzer nichts damit anzufangen. Man könnte Filename nehmen und dann die SFDL_DESC Variable gleich rauschmeißen.

**Comment by tox2** [comment]
Ja ich dachte nur deshalb weil meine Speedy immer so aussehen und dann dort der erste Platzhalter oft leer ist.

THX! Speedy Follows, SFDL: "%%SFDL_DESC%%" by "%%SFDL_UPPER%%"
Dann resultiert das oft in 
THX! Speedy Follows, SFDL: "" by "" 

Der ContainerName bzw. der Filename wäre denke ich ideal. 👍 
Ich denke auch die meisten Upper setzten denn ContainerName == Filename == ReleaseName gleich.
