### ISSUE TITLE
Seltsames Verhalten bei SFDLs wo der Server online ist aber der Ordner nicht mehr vorhanden ist

### ISSUE THREAD

**Issue by tox2** [n0ix/SFDL.NET#108]
Hab hier was seltsames gefunden und zwar sind es wieder mehrere Punkte:

- Retry's werden nach dem ersten Durchlauf mit Max Threads +1 Thread durchgeführt.
- Die Meldung "Download Läuft" kommt zwischen denn Retry's und dann am Ende noch mal wo eigentlich die Meldung "Server-Voll" dann schon da steht.
- "Server-Voll" ist ja eigentlich nicht richtig denn das würde ja bedeuten dass das SFDL online ist aber gerade keine Freien ServerSlots zu Verfügung stehen. Der FTP Folder existiert aber auf dem Server nicht mehr und  ist somit eigentlich Offline, das könnte dann der User im Forum dann auch brav Melden.
- Aja und Speedy mit 0MB oder NAN würde ich nicht auf die Platte schreiben lassen, jedoch diese in der TASK Meldung im Loader anzeigen. Damit etwaige vorherige Speedys nicht gelöscht werden. (Ist aber eigentlich auch komplett irrelevant in Anbetracht dessen das Wahrscheinlich nie ein User Speedys posten wird, vielleicht in andere Foren mehr wo via SFDL ein Speedy pflicht herrscht) 

-----------------

Sind auch alle im Video hier zu sehen : http://www119.zippyshare.com/v/ypS28ChS/file.html

Hier das LOG und die SFDL
[ServerVoll_SFDL_und_log.zip](https://github.com/n0ix/SFDL.NET/files/819403/ServerVoll_SFDL_und_log.zip)

**Comment by n0ix** [comment]
Das mit dem Retry ist mehr ein anzeige Fehler. Ist ein bisschen kompliziert das hier zu erklären.
Habe die Statusmeldung etwas nach "hinten" verschoben. Je nach Fehler Art wird sich das aber nicht gnaz vermeiden lassen
Das sollte nun gefixxt sein mit 3ebd76d
Das ist doppelt mit #105 - gehe ich hier nicht weiter drauf ein.
