### ISSUE TITLE
Session wird nicht gespeichert und 2 verschiedene FTP server können nicht gleichzeitig laden

### ISSUE THREAD

**Issue by tox2** [n0ix/SFDL.NET#109]
hier ein Zwei teiliges video und ein extra video das folgendes zeigt:

- Session wird nicht gespeichert
- Ftp error 200 und 550 treten auf
- 550 weil keine 2 verschiedene FTP gleichzeitig laden können (siehe video http://xup.in/dl,21311367)
- 200 keine Ahnung warum... Siehe log Files + Video Files  

Log Files:
[LogFiles_Session_Error_Download_Errors.zip](https://github.com/n0ix/SFDL.NET/files/819426/LogFiles_Session_Error_Download_Errors.zip)

2 Video Files:
http://www12.zippyshare.com/v/dY6fo6Ya/file.html
http://www12.zippyshare.com/v/BXGjaVe2/file.html

**Comment by n0ix** [comment]
Autsch, ja das mit den zwei verschiedenen FTP Server. Da habe ich wohl etwas zu viel optimiert und diesen Umstand nicht bedacht. Warum da allerdings die Session nicht gespeichert wurde - keine Ahnung. Kann ich absolut nicht nachvollziehen. Das würde ich jetzt aber außen vorlassen es sei denn es tritt bei dir häufiger/immer auf.

**Comment by n0ix** [comment]
Fixed with 9ba0986

**Comment by n0ix** [comment]
Habe den DL von RC4 mal rausgenommen da dass doch ein ganz schön heftiger Bug ist.

**Comment by tox2** [comment]
Ich schätze mal mit #109 war Change Unrar Handling as discussed in #112 gemeint :D
