### ISSUE TITLE
Retrys könnte man besser Multi threaden oder siehe Video

### ISSUE THREAD

**Issue by tox2** [n0ix/SFDL.NET#111]
Hab hier nochmal was besonderes zu Retrys:
EDIT: das länger Video ist besser geworden, da sieht man die dynamic der Retrys am besten. Ist aber ein etwas längeres Video (24min) ...siehe unten

Als erstes ist mir aufgefallen das wenn man in den Settings das "überschreiben" aktiv hat, dass Retrys dann auch das File überschreiben. (könnte man durchaus argumentieren dass das gut ist) 
- Das seltsame ist jedoch dann das folgende video ( http://www.xup.in/dl,16585942/local_.mp4/ )
- Die Retrys von **Part 1 wird weiter geladen** jedoch warten die Retrys von Part 2 und Part 3 solange bis Part 1 fertig ist.
- Dann gehts nur mit dem Retry von Part 2 weiter  **anstatt mit beiden**.
- Nun gut ich dachte mir nach dem **fertig geladenen Part 2** kommt dann endlich Part 3 dran. Das war eine falsche Annahme da hab ich aber auch leider das video gestoppt, müsste im Log aber zu finden sein.
- Es ging dann nämlich **wieder mit Part 1** weiter (??!) das wurde dann auch an der stelle nochmal geladen(512MB), dachte nach dem Part 1 kommt dann endlich Part 3 weil Part 2 ja auch fertig ist.
- Und wieder falsch gedacht es kam dann **nochmal Part 2** (??!) obwohl der auch wie Part 1 schon fertig war.
- erst nach dem der Part 1 und 2 **_(insgesamt 2 mal)_** geladen wurden kam **Part 3 dran**
- und sowie dieser fertig war hab ich auch ein video welches etwas ganz anders zeigt.
- und zwar wurde der Download nicht als Fertig markiert sonders als **gestoppt**. (http://www.xup.in/dl,84133945/local_(01).mp4/ ) 

hier das log und das SFDL file: 
[Crazy_Retrys.zip](https://github.com/n0ix/SFDL.NET/files/821736/Crazy_Retrys.zip)
Testcase war ganz einfach laden lassen, Nach kurzer zeit Wlan deaktivieren und sehen was passiert :D 

--------

- Es  ist denke ich besser, wenn die Retrys nicht warten bis ein anderer Download Fertig wird. 

- Falls  doch die Retrys dann von vorne laden sollen, darf es nicht sein das bereits geladene Files nochmal geladen werden. 

kann mir gut vorstellen das hier etwas kompliziertes im Hintergrund abläuft und nicht so einfach ist zu beheben. Dennoch fallst du noch ein Video mit anderem SFDL dazu brauchst sag bescheid. 👍 

------

Hier das länger Video 
https://mega.nz/#!eIdSUapA!kRPrOmbOvw6FgKt2-pW-yp4SQMvCYGQjbVCgtdAwSZA
Und hier auch noch log hab ich fast vergessen zum langen video : 
[Crazy_Retrys_long_video_log.zip](https://github.com/n0ix/SFDL.NET/files/821970/Crazy_Retrys_long_video_log.zip)

**Comment by n0ix** [comment]
Ok muss ich mir anschauen. Gut möglich das hier was schief läuft denn Retry+Override Modus habe ich noch nie probiert. Danke schonmal für die Mühe.

**Comment by tox2** [comment]
Jo am besten das länger Video angucken da sind die anderen auch nochmal besser zu sehen weil ich nicht dachte das im später download verlauf noch was dazukommt.

**Comment by n0ix** [comment]
Ähm habe mir das mal angeschaut, abgesehen von der Sache das der Retry überschreibt ist das verhalten teilweise gewollt. Hintergrund ist folgender:

Ich habe eine "ServerFullDetecttion" eingebaut. Die funktioniert wie folgt:

- Mehrere Threads laden (nehmen wir mal 3) = alles OK
- Ein Thread wird fertig ein neuer wird gestartet und der neue läuft auf einen Fehler.
- Der Fehler wird geparst. Kommt die funktion zum Schluss das hier irgendwo (Server Full, Login limit reached) aufgetaucht ist dann wird ein Event abgefeuert welches der **Session** mitteilt das sie nur noch mit **1 Thread** zu laden hat.

Da würde das verhalten was du beschrieben hast teilweise erklären.

Daher wäre meine Schlachtplan folgender:

- **Fix:** Bei einem Retry wird immer fortgesetzt und nicht überschrieben
- T**est:** SFDL laufen lassen, Netzwerkkabel ziehen und schauen was passiert.

**Comment by tox2** [comment]
Der Teil unten ist nur blabla was ich mir denke, bitte nicht streng beachten. Der Fix wäre zum Testen und ist denke ich ausreichend als Lösung für das beschriebene Problem. Solange es im Test dann nicht andere seltsame Sachen verursacht. Bin gespannt auf das nächste Release 👍 

-------------

Dein Fix müsste soweit funktionieren, wenn man folgendes Szenario und Video Verhalten in betracht zieht.

Also im Video ist es ja so, ich beziehe mich hier auf das länger Video, dass bei einem solchen Retry-Event 
eine Art Liste im Hintergrund erstellt wird. Diese wird wie du sagst dann bewusst sequenziell abgearbeitet, (1 Thread max.). Da diese Liste undefiniert oft durchlaufen wird und oder irgendwie im Zusammenhang mit den Max.Retry Versuchen und den Max.Threads von 3 (oder 5) ist. Wird sich an diesem Abarbeiten der Liste durch denn Fix nichts ändern sondern, die X Neulade-versuche würden deutlich schneller gehen weil der Download ja schon vollständig auf der Platte liegt. 

Idealerweise wäre es ja das man dieses Abarbeiten der Liste eindeutig definiert.
Wenn Man dieses Verhalten klar definieren könnte, dann wäre es egal, ob der Loader Überschreibt oder Fortsetzt.  

Leider kann ich mich nicht so gut rein denken wie das am besten gelöst werden kann, weil ich nicht weiß wie du das umgesetzt hast, jedoch _**hier die Frage an dich wäre dieses Sequenzielle Listing besser umsetzbar ?**_

**Comment by n0ix** [comment]
verdammt `_item.DownloadStatus = NET3.DownloadItem.Status.Running` zwei Zeilen zu hoch gesetzt ;-(

**Comment by tox2** [comment]
Ne echt ? das ist unlucky

**Comment by n0ix** [comment]
ich lade es nochmal hoch

**Comment by tox2** [comment]
ok 👍

**Comment by n0ix** [comment]
Ist das schon die neue (bitte MD5 Hash vergleichen)

**Comment by n0ix** [comment]
Naja trotzdem passt da noch etwas nicht. Er macht einmal Retry (nachdem das Netzwerk wieder da ist) korrekt mit "ResumeFile" danach lädt er die Datei aber nochmal (warum auch immer) und dann überschreibt er weil es kein Retry war. Irgendwie Strange.

**Comment by tox2** [comment]
Brauchst du ein log dazu ?

**Comment by n0ix** [comment]
Ne, habe schon ne idee woran es evtl. liegen könnte.

**Comment by tox2** [comment]
Hier hab ein log während des Gif recordings:
Seltsam ist dann auch nach einem Retry werden die Files nicht als abgeschlossen markiert ...
[RC_Retrys_while_gif_recording_log.txt](https://github.com/n0ix/SFDL.NET/files/831959/RC_Retrys_while_gif_recording_log.txt)

![retrys in rc5neu](https://cloud.githubusercontent.com/assets/23582323/23765500/b1ca48c4-0501-11e7-9fec-78982c15bf5b.gif)

**Comment by tox2** [comment]
Die Retrys im Debug sehen besser aus und funktionieren deutlich besser, bis auf einen kleinen Hacken wenn bei einem Part der Status Server Voll kommt, stoppt der download nicht mehr.... bis läuft immer...

log + gif encoding ....
[log_debug_crazy_unrar_.txt](https://github.com/n0ix/SFDL.NET/files/832304/log_debug_crazy_unrar_.txt)

**Comment by n0ix** [comment]
Gut das der Download nicht stoppt hatten wir ja vorher gefixxt. Von daher hört sich das ja prima an :-)

**Comment by tox2** [comment]
so das Debug v3 Release geht auch hier und löst dieses Problem.
TOP Arbeit. Ich werde natürlich das Verhalten in zukünftigen Releases beobachten ob diese auch so gefixxt bleiben :D 

Ich hoffe ich konnte dir heute beim Debuggen helfen und ein wenig Zeit ersparen alleine ist das dann doch oft mühsam :D 

PS: Morgen werde ich mich dann auf die Suche machen nach weiteren Bugs, oder am besten warte ich auf RC6 dann wird aber alles durchgecheckt :D

**Comment by n0ix** [comment]
Hat mir auf jedenfall sehr weitergeholfen. Ohne dich wären die sachen lange nicht so schnell gefixxt.

Danke!
