### ISSUE TITLE
Automatic UnRAR is not working if not all Items are selected for Download

### ISSUE THREAD

**Issue by n0ix** [n0ix/SFDL.NET#112]

**Comment by n0ix** [comment]
Erstmal noch etwas Grundlegendes: Das Problem tritt auf die Items, wenn sie fertig heruntergeladen sind, automatisch demarkiert werden. Daher bleiben diese bei einem erneuten Start des Downloads im Status "None".

Folgender Code Abschnitt ist das Problem:

```
                If IO.File.Exists(_chainmember.LocalFile) Then

                    Select Case _chainmember.DownloadStatus

                        Case DownloadItem.Status.AlreadyDownloaded
                            'ok

                        Case DownloadItem.Status.Completed
                    'ok

                        Case DownloadItem.Status.Completed_HashInvalid
                    'ok

                        Case DownloadItem.Status.Completed_HashValid
                            'ok
                        Case Else
                            _rt = False

                    End Select

                Else
                    _rt = False
                End If
```

Dieser hat zur Folge das eine UnRAR Chain nur als vollständig erkannt wird wenn alle benötigten Items der Chain einen der oben genannten Stati haben.

Jetzt ist die frage wie man das Problem löst.

### Variante 1 - Abfrage der Stati entfernen

Hört sich im ersten Moment ganz gut an, allerdings würden dann alles nochmal entpackt werden wenn man den Download stoppt und wieder startet oder eine gespeicherte Session wieder startet.

### Varinate 1b - Abfrage der Stati entfernen + Flag setzten "Chain bereits entpackt _(mein Favorit)_"

Würde das Problem lösen dass nicht nochmal alles entpackt wird wenn man den Download stoppt oder eine gesicherte Session startet. Hätte allerdings den Nachteil dass man die SFDL komplett schließen müsste um einen erneuten UnRAR Vorgang zu erzwingen.

### Varinate 2 - Alle Items die lokal existieren (auch wenn diese nicht markiert sind) den Status "Already Downloaded" verpassen.

Hat den Nachteil das man nicht sicher sein kann ob das Lokale File wirklich komplett ist da man im Zweifelsfall nicht weiß wie große Sie sein muss (BulkFolder). Wenn man hier wieder ein FTP Connect zum vorher prüfen macht dann hätte man sich das mit den automatischen abwählen der Files wenn diese Fertig sind auch komplett sparen können.

@tox2 : Habe ich bei einer dieser Variantem einen Denkfehler? Hast du noch eine bessere Idee bzw. welche Variante hälst du für am besten?

**Comment by tox2** [comment]
Frage ist es unbedingt nötig, zur Download Zeit des Containers oder Pakets die Daten zu entpacken?
Wäre es nicht sinnvoller mit der Unrar Chain auf den Abschluss des jeweiligen Downloads zu warten ?

GS hat es in seinem bash-laoder auch so.

1. SFDL open
2. SFDL download 
3. SFDL Speedreport 
4. SFDL extract 

Andererseits hab ich hier nochmal die v2 version angekuckt wie sicher der Loader dort verhält.
Da werden die Files nicht demarkiert sondern einfach als fertig bzw. "Already Downloaded" gesetzt.

hier ein video dazu: 

----------

**Variante 1** würde ich sagen ist **gut** wenn nach jedem Download ein Unrar Chain ausgelöst wird, denn in einem vorherigen Bug #91 , war es ja dann so das es besser ist vorhandene Dateien vom unrar nicht zu überschreiben also das unrar zwar starten aber unrar per Parameter sagen er soll vorhanden Files  überspringen.

**Variante 1b** + Chain bereits entpackt würde ich nicht machen denn es gab denke ich Fälle wo das dann eben **kontraproduktiv** ist im Fall eines Fehlers, wo zb. nur der halbe SFDL Container geladen wurde. 

**Variante 2** wäre ähnlich zum v2 Verhalten würde ich sagen dort geht das mit dem unrar wie man im Video sieht gar nicht, wenn man das clever macht würde müsste es denke ich gehen und für denn User ein besseres Feedback bieten.

Ich würde aber **Variante 3 empfehlen** :

- Die Unrar Chain's warten auf Download Finish Event für den jeweiligen Thread wenn zb. 3 Container Threads simultan laden [SFDL "A,B und C"] ( wenn "A" fertig ist darf die Unrar Chain für Container Thread "A" gestartet werden). 
Wenn es hilfreich ist würde ich das mit dem "Download Finish" berücksichtigen wenn der User zb. stop start macht das dann zu "Already Downloaded" gewechselt wird. Und hier eben ein ähnliches Verhalten wie in v2 zu erzeugen jedoch sollte das "Already Downloaded" sehr flott sein, die FTP Session steht ja schon da wäre nur ein FileSize Match ausreichend ohne CRC Control. Weiters darf die UnrarChain nur die Start Archive als solche entpacken, also *.rar oder .part1.rar etc. Ich denke diese bedingung schließen einige Fehlverhalten aus. Ist jetzt nur ein Gedankenspiel welches man testen müsste ob es umsetzbar ist und Zielführend.

Ich denke JDownloader und Load! machen das so ähnlich wie die Variante 3 es beschreibt.

**Comment by n0ix** [comment]
Ich finde es ziemlich blöde das der UnRAR nur am Ende des Downloads laufen soll. Das grade bei Serien mit Folgen ziemlich dämlich da dann nämlich 20 Folgen auf einmal entpackt werden müssten. Da kommt dann aber jede HDD nicht hinterher.

JDownloader entpackt übrigens auch sofort eine Chain Komplett ist und warten nicht den ganzen Download ab.

Was du an Variante 1b jetzt kontraproduktiv findest kann ich nicht nachvollziehen. Auch wenn ich den Container ich 2 Steps (also mit einem Stop dazwischen) lade funktioniert der UnRAR.

**Comment by tox2** [comment]
also markiert er nicht das schon Archiv schon entpackt wurde ?  wenn man zb 20 folgen hat 
2 entpackt er dann pause dann 18 laden, der entpackt dann 18 ?

**Comment by n0ix** [comment]
jo genau, so würde das funktionieren bzw. so war meine Vorstellung davon ;-)

**Comment by tox2** [comment]
Ist dieses markieren "Archiv schon entpackt" dann im im Status zu sehen und kommt nach "Download abgeschlossen" oder bleibt da im Status "Download abgeschlossen. 
Ich denke jetzt an das eine SFDL von mir wo ich mehrere Verschiedene Archive über für 4 Pakete in einem Container drinnen habe. Ob das dann dort auch klappt?

**Comment by n0ix** [comment]
Ne der Status wird nicht angepasst. Ist nur ein Flag im der Klasse "UnrarChain" welches gesetzt wird. Und jede Instanz einer UnRAR Chain bekommt ihr eigene Flag, daher ja (sofern ich deine Frage richtig verstanden habe) funktioniert auch über mehrere Packages hinweg.

**Comment by n0ix** [comment]
Bei mir hat es soweit funktioniert. Versuch mal dein Glück :-)

http://www.xup.in/dl,21027270/SFDL.NET_3_UnRAR_TestBuild_09032017.zip/

**Comment by tox2** [comment]
Jup klappt auf dem ersten Blick ganz gut, Die Meldung "No valid UnrRAR Password found!" kommt sehr oft. 

und beim 2ten Anlauf (start stop) entpackt er zwar jedoch war bei einem RAR ein unbekannter fehler das part wurde noch nicht fertig geladen. Da versucht er gerade bei mir städig neuzuentpacken. (endless unrar loop)

Hier das Log dazu, vielleicht kannst du daraus mehr ablesen 
[log_unrar_testbuild.txt](https://github.com/n0ix/SFDL.NET/files/831088/log_unrar_testbuild.txt)

**Comment by tox2** [comment]
Die Session klappt wieder und funktioniert bei mir im Testbuild 👍

**Comment by n0ix** [comment]
Hm, wenn der Unrar nicht klappt wird auch das flag nicht gesetzt was dann zur folge hat das er loopt.
Ist jetzt Frage wie man damit umgeht.

Vermutlich ist es besser das unabhängig vom UnRAR result zu setzten.

**Comment by tox2** [comment]
Hier zum Unrar verhalten in RC5, log + gif :D 
Da die Parts nicht als fertig markiert werden, kommt es dazu das der loader im im State ist Download läuft. Obwohl nichts läuft.

Die meldung Unrar no PW found kommt seltsam oft.
Im testbuild  war es um einiges Stabiler als jetzt. bis auf das mit der Meldung und der Loop. 

Das mit dem Download läuft betrifft jedes Sfdl und blockiert denn Loader stark momentan.

[UNrar in RC5_log.txt](https://github.com/n0ix/SFDL.NET/files/832031/UNrar.in.RC5_log.txt)
![unrar in rc5](https://cloud.githubusercontent.com/assets/23582323/23766134/e7e5d714-0503-11e7-8d6a-da45ed19ee39.gif)

**Comment by n0ix** [comment]
Es ist irgendwie der Wurm drin. Die Issuse hier sowie die bzgl. Retry hängen etwas zusammen. Ich führe es daher erstmal hier fort. Ich habe jetzt nochmal alles etwas überarbeitet. Es war alles etwas unlogisch bzw. den Bezeichnungen für die Download Status usw. Aus meiner Sicht als Programmierer ist das jetzt alles etwas stimmiger.

Ich mach grade noch ein zwei Basis Tests dann würde ich dich bitten das nochmal anzuschauen wenn du Zeit und List hast. Ich weiß die ganzen Fehler sind grade ziemlich nervig.

**Comment by tox2** [comment]
Ja Zeit und Lust habe ich immer :D schaue auch gerade nur einen Stream zu hab nicht viel zu tun :D 
das Debug.rar wäre das zu testende release ?

**Comment by n0ix** [comment]
ja genau

**Comment by tox2** [comment]
kurze frage was eigentlich schon ein Bug ist, laden tut dieses SFDL (File Not Found) aber es kommt nie die Meldung das der download fertig ist. http://www.xup.in/dl,31842959/0_v9_nopw_down.sfdl/

Versuch du dein glückt stoppt bei dir der Download irgendwann ?

**Comment by tox2** [comment]
Beim SFDL:
http://www.xup.in/dl,17871800/SFDL_Archiv_TESTCases.sfdl/

scheint der bug darin zu liegen das wenn ein RAR ohne PW entpackt wurde, eine Variable gesetzt wird welche ein rar mit pw entpacken einwenig verhindert oder auf jeden fall nicht sauber ausführt. 

LOG:
[log_debug_crazy_unrar_.txt](https://github.com/n0ix/SFDL.NET/files/832268/log_debug_crazy_unrar_.txt)
GIF: incoming still encoding

**Comment by tox2** [comment]
Hat jede Unrar Chain seinen eigenen Thread ? bzw. ist dieser unabhängig von anderen unrar chains ?
Gerade wegen diese Unrar Chain "Chain bereits entpackt" Mechanik

**Comment by tox2** [comment]
Falls ich noch was testen soll sag bescheid

**Comment by n0ix** [comment]
1.) Bug wo der Download nie stoppt - gefixxt
2.) läuft bei mir tadellos. Kommt auch keine Meldung von wegen er würde kein PW finden.
3.) Ja jede Chain ist eigenständig. Aber ich hatte bei Variante 1b dann doch einen denkfehler. Und zwar tritt das nur bei deinem Test SFDL in der Form auf da hier UnRAR Chains nur aus einer Datei bestehen. Sobald diese Lokal existieren  (das tun sie ja sobald der download startet) wird versucht diese zu entpacken. Dies schlägt natürlich fehl was dann (fälschlicherweise) in "No Valid Password found" mündet.

**Comment by tox2** [comment]
Single rar Archive werden e nie geladen wenn es nur dort auftritt lass es als bug offen fürs erste :D

**Comment by tox2** [comment]
bei 2) kam es bei  mir deshalb zu dem Fehler, weil er gerade das *.Rar geladen hat. Die chain jedoch schon vorher gestartet wurde. bei vorherigen part

**Comment by n0ix** [comment]
Na das ist doch auch keine lösung. irgendwann tritt der Fehler dann doch auf.

Viell. ist deine Variante 3 doch nicht so eine schlechte Idee. Wenn man das am Ende vom Download entpackt könnte ohne größere Probleme die Dateigröße gegen den FTP prüfen (denn das Problem besteht nach wie vor) und dann eben entpacken.

**Comment by tox2** [comment]
> also markiert er nicht das schon Archiv schon entpackt wurden ? wenn man zb 20 folgen hat
> 2 entpackt er dann pause dann 18 laden, der entpackt dann 18 ?
> 
> Wenn es so klappt dann hab ich es falsch verstanden ?

also kann man sagen das Szenario dann nie korrekt entpackt werden kann ? mit Variante 1b ?

**Comment by n0ix** [comment]
Doch generell funktioniert 1b schon. Das ganze ist nur ein Timing Problem.

**Comment by n0ix** [comment]
Das mit der Filesize gegen den FTP prüfen könnte man eigentlich auch weglassen, da das meiste eh BulkFolder ist (da wird die FileSize ja eh eingelesen) und wenn es eine "normale" SFDL ist dann steht die FileSize ja schon in der SFDL.

**Comment by tox2** [comment]
Verstehe, ich werde mir die tage ein wenig denn Kopf darüber zerbrechen, Vielleicht hab ich eine gute Strategie wie man das umsetzten kann :D 

Wobei ich denk das mit dem am ende des Downloads die einfachste davon sein müsste. 
Vielleicht fällt dir auch noch was ein. 👍

**Comment by tox2** [comment]
Blöde frage statt die Filegröße zu prüfen, könnte man einfach den Status des Parts prüfen ? sobald der auf Download Abgeschlossen steht darf entpackt werden ? und das nur für Start Archive ?

**Comment by n0ix** [comment]
Ja, aber wenn man in 2 Steps lädt hat das Item keinen Status

**Comment by tox2** [comment]
ja es hat auch keinen Sinn bei wenn zb. nach dem 1step 50% geladen wurden, ein unrar chain zu starten
nach 2step ist es dann 100% dann darf er...

**Comment by n0ix** [comment]
Ich glaub ich habs: http://www.xup.in/dl,41855745/SFDL.NET_3_UnRAR_ExeOnly.zip/

**Comment by tox2** [comment]
sollte 2 und 3 jetzt klappen?

**Comment by n0ix** [comment]
ne hab grad noch ein fehler gefunden

**Comment by tox2** [comment]
also bei 2 entpackt er nicht und bei 3 ) versucht er manchmal öfter das selbe Archiv zu entpacken.. bis zu  3 mal in meinen test gerade. 

Ganz zum Schluss im log sieht man das er versucht ein rar öfter zu entpacken.
[Uploading Test_session_contains_alot_but last_contains_multi_unrar_of single_file.txt…]()

**Comment by n0ix** [comment]
Hast du "Unterordner pro Packet erstellen" aktiviert?

**Comment by tox2** [comment]
nope weder bei bei 2) noch bei 3)

**Comment by n0ix** [comment]
Ja das ist das Problem Kollege. Du hast im deinem Test Case nämlich gleiche Files. Daher entpackt er auch viele Files 2x. Da das File in zwei oder verschiedene Package enthalten ist. Da der Haken **nicht** gesetzt ist wird alles in den selben Ordner geschmissen. Kannst du mir folgen?

**Comment by n0ix** [comment]
http://www.xup.in/dl,32629809/SFDL.NET_3_UnRAR_ExeOnlyv2.zip/

**Comment by tox2** [comment]
Ja das ist mir bewusst :D aber ich habe nur ein rar von jeweiligen gewählt, und in den rar sind sie dann als 7z drinnen. sogar wenn es ein rar ist es wird ja nicht überschrieben wenn es denn gleichen namen hat.

**Comment by n0ix** [comment]
Hm nicht böse gemeint: Aber du hast nicht verstanden was das "problem" an deiner SFDL ist. Mach den Haken rein, nimm die neue Exe und staune ;-)

**Comment by tox2** [comment]
Hm geht bei dir das "PW_NO_30M.part1.rar" und "PW_NO_30M.part2.rar" ? ich habe jetzt denn hacken drinnen aber das will nicht entpacken.

**Comment by tox2** [comment]
Aber warum hat das mit dem Hacken was zu tun ich habe in meinem test ja nur Files aus einem der 4 Pakete gewählt ? 

Ich teste mal ohne Hacken

**Comment by n0ix** [comment]
Ne geht mir auch nicht. Die Chain besteht nämlich lustiger Weise aus diesen Files:

```
PW_NO_30M.part1.rar
PW_NO_30M.part2.rar
PW_NO_30M.part2.rar
PW_NO_30M.part2.rar
```

Kurzum hier ist das UnRARChain Parsing etwas buggy.

**Comment by tox2** [comment]
Auch ohne Hacken gehen jetzt die Files zum entpacken und die Meldung das kein PW gefunden wurde kam auch nicht mehr. 

Ich versuche jetzt das Paket einmal komplett laden zu lassen :D

**Comment by tox2** [comment]
WOW nice sogar ein kompletter Durchlauf eines Pakets in dem Container ging, ab und zu kam der Unbekannte Fehler Status aber alle UnrarChains haben funktioniert. 
TOP 👍

**Comment by tox2** [comment]
Die part1 + part 2 sind halt eben noch buggy

**Comment by n0ix** [comment]
Also es wird wiefolgt geprüft ob eine Chain entpackt werden kann:

- Existiert die Datei?
- Passt die Dateigröße?
- Sind alle anderen ChainMitgleider ebenfalls vorhanden und haben die korrekte Dateigröße?

Wenn alle 3 Punkte zutreffen dann wird die Chain entpackt.

Was passiert jetzt bei deinem SFDL File wenn der Unterordner haken nicht gesetzt ist?

```
Chain1 (Package1):

PW_NO_30M.part1.rar
PW_NO_30M.part2.rar

Chain2 (Package2):

PW_NO_30M.part1.rar
PW_NO_30M.part2.rar
```
Jetzt geht er jede Chain in eine Schleife durch prüft die oben genannten Kriterien. Hoffe ich konnte dir die logik etwas näher bringen

**Comment by tox2** [comment]
Ja das ist klar aber da muss es auch Fehler geben. 
Mein Test case war folgender:
Da sind nur Parts von einem Paket markiert und da kam es in dem oberen log dann zu dem multi unrar. 
Jetzt im debug v2 geht aber alles wunderbar bis auf part1 und part2.rar 

![testcase](https://cloud.githubusercontent.com/assets/23582323/23774874/41a005be-0526-11e7-943f-b21ba390fe21.png)

**Comment by n0ix** [comment]
Die letzte für heute bzw. gestern: http://www.xup.in/dl,51422059/SFDL.NET_3_UnRAR_ExeOnlyv3.zip/

PS: geht bei dir MLC auch nimmer?

**Comment by tox2** [comment]
dieses Test SFDL, wurde deshalb mit 4 packages erstellt damit ich weniger klicken muss und bei jedem test darf man nur mit einem der 4 Pakete arbeiten alle anderen müssen deaktiviert sein. 

Denn so ein Szenario wird es nie geben wo der Upper 2 Pakete mit selben files ein SFDL packt.

**Comment by tox2** [comment]
MLC ist tot ja

**Comment by tox2** [comment]
in v3 wird jetzt part1 und part 2 entpackt ? oder sollte entpackt werden ?

**Comment by n0ix** [comment]
> dieses Test SFDL, wurde deshalb mit 4 packages erstellt damit ich weniger klicken muss und bei jedem test darf man nur mit einem der 4 Pakete arbeiten alle anderen müssen deaktiviert sein.

> Denn so ein Szenario wird es nie geben wo der Upper 2 Pakete mit selben files ein SFDL packt.

Alles klar, war auch nicht böse gemeint. Wollte nur vermeiden das wir aneinander vorbeireden.

> in v3 wird jetzt part1 und part 2 entpackt ? oder sollte entpackt werden ?

ja sollte funktionieren. Hat es zumindest bei mir ^^

**Comment by tox2** [comment]
Jup geht bei mir auch jetzt mit part 1 und part 2, ich lasse ihn jetzt nochmal alles laden in einem paket.

**Comment by tox2** [comment]
Also bis auf dass das meine CPU auf 100% geht weil plötzlich 5 Unrar Chains arbeiten. 
denke ich das das Release die Fehler alle ausgemerzt hat.

**Comment by n0ix** [comment]
Cool das hört sich gut an. Das mit der CPU ignoriere ich mal gekonnt ;-)

Danke nochmal für deine Unterstützung.

**Comment by tox2** [comment]
Ist klar CPU kann man jetzt nicht auch noch berücksichtigen kann vor allem ist das eh nie der Fall der so viele auf einmal exekutiert werden :D 

Kein Ding, der Loader v3 muss deutlich stabiler sein als v2 :D dann kann der auch ein Paar Jahre so bleiben.

**Comment by n0ix** [comment]
kann man dann hier und das Retry Problem zumachen?

**Comment by tox2** [comment]
Denke schon ja
