### ISSUE TITLE
RC5 Crashes when opening any SFDL File ? 

### ISSUE THREAD

**Issue by tox2** [n0ix/SFDL.NET#113]
Log hab ich keine die was aussagen.. ist das bei dir auch so in RC5 ? 

also das beim SFDL öffnen der Loader sich aufhängt ?

**Comment by n0ix** [comment]
Ähm nein?

**Comment by tox2** [comment]
Hast du einen tipp hier das video dazu hab auch schon versucht die appdata zu löschen nichts hat geholfen 
http://www.xup.in/dl,20694996/local_.mp4/

**Comment by n0ix** [comment]
sehr komisch. schick mir mal das file bitte

**Comment by tox2** [comment]
Bug found "SFDL.Container.Legacy.dll"  fehlt im zip file

**Comment by n0ix** [comment]
Danke, lade gleich nochmal neu hoch
