### ISSUE TITLE
Improvment - Close SFDL Loader after Download warn user and wait 3s  

### ISSUE THREAD

**Issue by tox2** [n0ix/SFDL.NET#115]
Momentan wird nachdem "Download Finished" und "unrar Finish" sofort Beendet, ich würde beim schließen und beim PC Shutdown, ne kleine Wartezeit einbauen. So 3s oder so. Vielleicht mit Panic Abbruch.

Das mit dem PC Shutdown habe ich nicht getestet bis jetzt.

**Comment by n0ix** [comment]
Beim PC Shutdown (30 Sekunden) wird gewartet. Allerdings über Windows Boardmittel. Könnte man dann manuell abbrechen mit `shutdown -a`

Ich würde das erstmal weglassen da ich eigentlich mal gerne eine Stable veröffentlichen werden, da kommen wir aber nicht hin wenn wir "dauernd" neue Sachen einbauen ;-)

Kurzum: Könnte man einbauen, dann aber zu einem späteren Zeitpunkt.

**Comment by tox2** [comment]
Verständlich, alles klar dann lassen wir das einfach offen oder auf einer "possible ToDo" Liste. 👍

**Comment by n0ix** [comment]
Das Feature wird noch etwas warten müssen. Finde grade keine vernünftigen weg das zu implementieren

**Comment by tox2** [comment]
Kann man das nicht mit einem Timer machen ? 
Sowie hier mit Thread Sleep oder so...

http://stackoverflow.com/questions/15857893/wait-5-seconds-before-continuing-code-vb-net#15861154

**Comment by n0ix** [comment]
Theoretisch ja -allerdings ist das eine Async Funktion. Da funktioniert das nicht. Muss da mal drüber nachdenken...habe irgendwie ne wand vorm kopf

**Comment by tox2** [comment]
http://mahapps.com/controls/dialogs.html

könnte hier der Progress dialog der Schlüssel zum erfolg sein ?

bzw. hier mit etwas mehr code als Beispiel 
http://stackoverflow.com/questions/23211259/updating-showmessageasync-progress-value-from-external-method

was sagst du dazu @n0ix

**Comment by n0ix** [comment]
Danke für den Denkanstoß. Konnte es damit super einbauen :-)

**Comment by n0ix** [comment]
Hier mal ein kleines GIF damit sieht wie das ganze dann nachher aussieht. 

![showcase](https://cloud.githubusercontent.com/assets/17708302/24442067/adc37cb8-145c-11e7-918c-353c33b65301.gif)

_Notiz: Das GIF habe ich etwas "getuned". Es sind alles keine wirklichen 30 Sekunden zu sehen._

**Comment by tox2** [comment]
Top Arbeit freut mich das ich helfen konnte 👍 
Denke das Rundet die Funktion optimal ab.
