### ISSUE TITLE
Improvment: Update Info in Titelbar, like MahApps 

### ISSUE THREAD

**Issue by tox2** [n0ix/SFDL.NET#117]
@n0ix, was hältst du von dieser Idee.

http://mahapps.com/guides/quick-start.html#windowcommands
![05_windowcommands](https://cloud.githubusercontent.com/assets/23582323/23778529/0817167e-053b-11e7-8fba-9fe27a1d83e6.png)

so wie es das bild zeigt das man dann sieht 
Neue Version Verfügbar: [Download hier](https://github.com/n0ix/SFDL.NET/releases)

Wenn kein Update vorhanden ist dann sieht man nichts.

PS: Sind nur kleinen Vorschläge von mir. Würde nur gern wissen wie du zu denen stehst 😃

**Comment by n0ix** [comment]
Finde ich generell eine gute Idee. Werde ich einbauen.

**Comment by n0ix** [comment]
Optisch so ok?

![image](https://cloud.githubusercontent.com/assets/17708302/23790310/d7488278-057e-11e7-98c9-c2e1378043d7.png)

Man kann dann draufklicken - dann soll sich die Github Release Seite öffnen

**Comment by tox2** [comment]
Perfekt 👍
