### ISSUE TITLE
Improvment: Hab hier was für denn Spacebar Select vielleicht gefunden

### ISSUE THREAD

**Issue by tox2** [n0ix/SFDL.NET#118]
http://stackoverflow.com/questions/16939859/check-uncheck-checkbox-with-space-enter-in-gridview-in-listview-wpf#16940838

Falls das schon versucht wurde. kannst das thema closen oder löschen oder was auch immer.

**Comment by n0ix** [comment]
Hatte ich schon versucht. Genau den gleichen Code verwende ich ja auch - nur eben mit der Enter Taste.

Ich hab keine Ahnung warum er sich da an der Leertaste verschluckt, evtl. liegt es an den MahApps.
