### ISSUE TITLE
Volle HDD BUG, -> Status "Unbekannter Fehler" ?

### ISSUE THREAD

**Issue by tox2** [n0ix/SFDL.NET#120]
Loader zeigt unbekannten Fehler im Status an. log schreibt aber alles richtig mir.

Siehe Gif + log
[log_Volle_HDD.txt](https://github.com/n0ix/SFDL.NET/files/834685/log_Volle_HDD.txt)
![vollhdd_rc6](https://cloud.githubusercontent.com/assets/23582323/23806482/24163dbe-05c2-11e7-912c-edbb8791b3a2.gif)

**Comment by n0ix** [comment]
Hm blöd. Liegt daran das die Threads ja parallel laufen und zum Zeitpunkt der Speicherplatz überprüfung natürlich genügend Platz zur Verfügung steht.

**Comment by tox2** [comment]
hat die FTP lib keine Fehler codes für diesen fall ? oder der File Stream write wo er sagt ich kann nicht mehr auf die platte schreiben, weil kein speicher ?

**Comment by n0ix** [comment]
Fixed. 
![image](https://cloud.githubusercontent.com/assets/17708302/23809042/6146e170-05cc-11e7-9b1c-2fcb848dc119.png)

**Comment by tox2** [comment]
✅ Fixed in 3.0.0.8
