### ISSUE TITLE
2 Container dont load simultan

### ISSUE THREAD

**Issue by tox2** [n0ix/SFDL.NET#121]
Ist das so beabsichtigt, das 2 Container von 2 verschiedenen Server, abwechselnd laden ?
kann mir gut vorstellen das da manchen User dann sagen "ja ich will aber das entweder diese nacheinander wie in einer Warteschlange geladen werden oder pro Paket simultan, ohne dieses hin und her springen" 

Das ist mir schon vorher aufgefallen ich denke erst ab Rc4 oder Rc5 ist das so. 

Ach ja und zum Schluss vom Gif lasst er mich das SFDL nicht schließen 🤔 

Siehe log+ gif:
[RC6_Simultan_load_log.txt](https://github.com/n0ix/SFDL.NET/files/834738/RC6_Simultan_load_log.txt)
![2_container_simultan_rc6](https://cloud.githubusercontent.com/assets/23582323/23807053/81e3719e-05c4-11e7-9dc6-db2ba2fb5262.gif)

**Comment by n0ix** [comment]
Nope läuft bei mir einwandfrei. Sieht mir eher so aus also würde die erste SFDL deine Max Eingestellten Threads "aufressen"

**Comment by tox2** [comment]
Aso ja das kann sein, sind auf 5 eingestellt, dachte die max threads sind pro Session maximiert. Mein Fehler.

**Comment by tox2** [comment]
Close dann mal
