### ISSUE TITLE
Visual Bug ? Pixel Offset in columns.

### ISSUE THREAD

**Issue by tox2** [n0ix/SFDL.NET#123]
Das war das was ich in der PN meinte...

![colum_offset](https://cloud.githubusercontent.com/assets/23582323/23832436/480d2dd6-0734-11e7-9c77-44834bd8466f.png)

**Comment by n0ix** [comment]
Jetzt wird es aber sehr kleinlich^^

Habe mal etwas rumprobiert, wird aber nur schlimmer nicht besser.

**Comment by tox2** [comment]
Alles klar, ich schließe das dann hier ganz schnell mal 😆
