### ISSUE TITLE
EN Setting is ignored ? 

### ISSUE THREAD

**Issue by tox2** [n0ix/SFDL.NET#125]
Ist das normal bzw. wird die GUI Sprache auf englisch umgewechselt und wenn ja wann nach neustart oder sofort ?

Siehe Gif:
![en_ignore](https://cloud.githubusercontent.com/assets/23582323/23835429/8e690ff6-0767-11e7-9c5a-675c4df1cf1b.gif)

**Comment by n0ix** [comment]
Neustart eigentlich.

**Comment by n0ix** [comment]
Habe ich wohl vergessen zu programmieren so wie ich das grade sehe

**Comment by tox2** [comment]
Hab ich versucht, will bei mir nicht so ganz :( 
Vielleicht das ein File einen Falschen namen hat ?

**Comment by n0ix** [comment]
Habe das echt vergessen - I'am really sorry

**Comment by tox2** [comment]
✅ Fixed in 3.0.0.8
