### ISSUE TITLE
Unrar No PW found, executes multiple times 

### ISSUE THREAD

**Issue by tox2** [n0ix/SFDL.NET#126]
Siehe gif + log:

Das hatte ich voll vergessen zu testen 😆  SRY

Das seltsame ist ich hab vorhin denn Loader geschlossen um das in einem gif nochmal zu scannen, und dann erzeugte er ein log da so nicht stimmen kann oder ? es waren noch rar files im Ordner von vorher. Aber warum sind die im Unrar Chain ? 

**Könntest du das mal testen,** Testcase: nothing loaded no PW in settings stored, download RAR with pw.

Da macht er bei mir (immer) 3 versuche... (denke die 3 ist nicht immer war jetzt halt so.)
Ist das normal ?

[unrar_no_pw_log.txt](https://github.com/n0ix/SFDL.NET/files/836888/unrar_no_pw_log.txt)
![unrar no pw](https://cloud.githubusercontent.com/assets/23582323/23835662/a5c3a59a-076b-11e7-8ee7-63adf646ad43.gif)

**Comment by n0ix** [comment]
Muss ich mir die Tage mal anschauen. Könnte auch an deiner dezent speziellen SFDL liegen ;-)

**Comment by tox2** [comment]
Das mit der SFDL ist sogar wahrscheinlich bei einer anderen wo das Gesamt Archiv aus 3 teilen besteht. entpackte er nur einmal bzw. kam nur einmal der PW not found satz.

**Comment by n0ix** [comment]
Hatte das selbe Phänomen eben auch bei einer komplett anderen SFDL. SIeht so aus also würden die UnRAR Chains mehrfach (bei jeden Start) hinzugefügt werden. Sprich die Variable wird nicht geleert.

**Comment by n0ix** [comment]
Du bekommst vor dem Release noch eine Version damit man diesen Umstand nochmal testen kann

**Comment by tox2** [comment]
✅ Fixed in 3.0.0.8
