### ISSUE TITLE
CRC check fails on tagged FilePaths [by Akeni]

### ISSUE THREAD

**Issue by tox2** [n0ix/SFDL.NET#128]
Hier das log dazu:

Methode XCRC:
[CRC_FileNot Found.txt](https://github.com/n0ix/SFDL.NET/files/839524/CRC_FileNot.Found.txt)
Methode MD5:
[CRC error 2_log.txt](https://github.com/n0ix/SFDL.NET/files/839570/CRC.error.2_log.txt)

**Comment by n0ix** [comment]
Ich befürchte da werde ich nicht viel machen können. 

Hat auch mit MD5 oder CRC rein gar nichts zu tun. Selbst wenn der Server MD5 unterstützen würde - der Fehler würde exakt der selbe sein.

Man könnte nur versuchen vorher in das Verzeichnis selbst zu wechseln, allerdings wird auch das vermutlich fehlschlagen.

**Comment by tox2** [comment]
✅ Fixed in 3.0.0.8
