### ISSUE TITLE
UI Verbesserungen [Pull Req.]

### ISSUE THREAD

**Issue by tox2** [n0ix/SFDL.NET#130]
Ich habe ein Fork für die UI Verbesserungen gemacht. hier https://github.com/tox2/SFDL.NET/branches
Da das ganze noch neuland mit Git für mich ist, dachte ich mir ich arbeite dort.
Bevor ich auf dem Repo was mache.

Jetzt dir Frage and dich @n0ix kann ich hier die Branch so wie dort rein geben, ist es dann leichter ein Pull Request zu machen ? Oder ist das Egal auf welchem Repo sich das befindet. 

PS: Was hältst du von denn Änderungen dort vorerst ?
PPS: ich habe auch diverse Schreibfehler im englischen gefunden, würde diese dann auch auf dem Branch abändern.

**Comment by n0ix** [comment]
Erstmal vielen Dank. Ich bin leider auch kein Github Spezi, sollte aber (so habe ich das zumindest mal gelesen) via eines Pull Requests machbar. Ich probier mal im Notfall schreibe ich eben ab :-)

**Comment by n0ix** [comment]
Habe mal einen Pull Request #131 erstellt. Sieht eigentlich ganz gut aus

**Comment by n0ix** [comment]
Ich glaube du musst die String.resx nochmal anpassen da ich aufgrund des Bug's #127 da etwas ändern musste.

**Comment by n0ix** [comment]
Hab deinen Pull Request gemerged. Sieht alles sehr gut aus - Danke für die Arbeit und mühe.
