### ISSUE TITLE
Retry sometimes generates Corrupt Fileparts [Rare Bug, does not always happen]

### ISSUE THREAD

**Issue by tox2** [n0ix/SFDL.NET#133]
48 MB filepart can be sometimes 60MB fileparts.
When a retry happens while only 12MB of 48MB where loaded.

Here the log+ SFDL:

[Retry_Corrupts_File_Sometimes.txt](https://github.com/n0ix/SFDL.NET/files/841516/Retry_Corrupts_File_Sometimes.txt)
http://xup.in/dl,10450792

**Comment by n0ix** [comment]
Mich wundert dieser Eintrag hier:

`2017-03-14 03:22:18.5965|ERROR|DownloadHelper|File error. Code=251 ('/x264-HD/Barbie.Eine.Prinzessin.im.Rockstar.Camp.2015.German.DL.DTS.1080p.BluRay.x264-BestHD/besthd-barbie.camp.108.r07 65C016EED760F90E7B7A8318D2C7BDD1')`

Was zum teufel soll denn bitte Code 251 sein? Den gibt es ja FTP RfC überhaupt nicht.

**Comment by tox2** [comment]
Hat er auch bei mir kommen sehr oft Retry versuche sobald ich mehre als 1 Thread lade. 
Auf jeden Fall bilde ich mir ein  das es in dem CRC bug auch mal vorkam das er Error 251 ausgibt. siehe 
hier 

```
2017-03-13 21:45:19.8450|ERROR|DownloadHelper|File error. Code=251 ('"/[ MP3 ]/German TOP100 Single Charts 13 03 2017 mit Cover/009 - Ed Sheeran - Castle on the Hill.mp3" E3E68B12062FA3E2423F6FB24420B582')
```

das ist in dem 2ten log von #128 
https://github.com/n0ix/SFDL.NET/files/839570/CRC.error.2_log.txt

Also ich weiß gar nicht ob ein Video zum bug hier weiterhilft, ist das zufällig ein FTP Lib error Code ?
Was meinst du @n0ix

**Comment by n0ix** [comment]
Nein, ich glaube nicht das der Fehler etwas mit der FTPLib selbst zu tun hat. Das ist meiner Meinung nach einfach die Antwort vom FTP Server selbst.

**Comment by tox2** [comment]
Fragen wir mal die Upper und Admins, vielleicht wissen die was der Code aussagt ...

**Comment by tox2** [comment]
Sag mal welcher Code Abschnitt macht den diese Zeile ?

**Comment by DatSoeren** [comment]
Der Server antwortet beim Abrufen der Prüfsumme mit Code 251. Der aktuelle Code scheint damit einfach nicht zu rechnen.

**Comment by tox2** [comment]
hm ok Zeile, scheint das Problem zu fixen:

In SFDL.NET 3/Classes/DownloadHelper.vb die Zeile 693 . Mach da mal die 250 zu 250,251

`reply = _ftp_session.Expect(_ftp_session.SendCommand(_hashcommand, _item.FullPath), 250, 251)`

**Comment by tox2** [comment]
wird wohl in jeder Zeile nötig sein wo 251 nötig ist.
Hab darunter noch 2 gesehen aber nicht speziell nicht mehr getestet.

**Comment by n0ix** [comment]
> Der Server antwortet beim Abrufen der Prüfsumme mit Status-Code 251. Der aktuelle Code scheint damit einfach nicht zu rechnen.

Das ist richtig. Kann sich jetzt drüber streiten wer falsch ist , denn meiner Meinung gibt es den Status Code 251 nicht, aber ich kann das natürlich abändern. 

Was ich aber nach wie vor überhaupt nicht verstehe: Ja hier gibt es evtl. Probleme mit dem Vergleichen der Hashes - aber was hat das überhaupt mit dem BugReport zu tun das Files inkonsistent/korrupt sind??

**Comment by tox2** [comment]
Guter Einwand, warum das so vorgekommen ist weiß ich nicht werde es die tage mal genauer ansehen.

**Comment by DatSoeren** [comment]
Triggert das fehlschlagende Post-Processing eventuell einfach einen Abbruch, sodass die Files nicht fertig geladen werden?

**Comment by n0ix** [comment]
Nein das ermitteln des Hashes usw. wird erst nachdem der Download fertig ausgelöst.

Mal ne andere Frage: Tritt das beschriebene Probleme irgendwie großflächig auf? Ich persönlich hatte den Fehler nämlich jetzt noch nie. Oder bezieht das jetzt auf eine SFDL bzw. lässt sich daraus ein bestimmter FTP ableiten?

**Comment by tox2** [comment]
Es trat bei mir nur einmal auf ... Deshalb auch im Titel Rar BUG, könnte jetzt auch nur eine Einmalige Geschichte gewesen sein aber was mich doch wundert ist ja folgendes was im video zu sehen ist.

Nun denn mein Gedanke ist das der Server einfach seine eigenen Code schickt und damit das IO Exeption auch mit auslöst, keine ahung wobei das kann es auch nicht sein weil er hat gestern noch geladen 

http://www.xup.in/dl,17148733/local_(04).mp4/

Ich denke sogar das es einfach am server liegt.... werde noch ein wenig testen und dann closen, denn ich schaffe denn fehler nicht zu reproduzieren...

**Comment by n0ix** [comment]
Zu deinem Video: Die IO Exception sind normal wenn der Server voll ist, da er den Stream nicht öffnen kann , da der FTP Server dies verweigert.

**Comment by tox2** [comment]
der Server ist einfach kacke .... ich Close hier mal denn ich bekomme beim testen nur mehr noch diese IO errors.... 

Falls ich das bei einem anderen SFDL mal sehe mach ich wieder auf ....
