### ISSUE TITLE
Improvment: Activate Logs in Settings ?

### ISSUE THREAD

**Issue by tox2** [n0ix/SFDL.NET#138]
Anstatt wie bisher mit /log die logs zu aktivieren. 
Wäre es Möglich dafür eine Settings Checkbox zu machen so wie für die Updates Prüfung ?

- [x] Logging (für logs ein)
- [ ] Logging (für logs aus)

-----------
Ich mag nicht bei jedem Release mir eine Verknüpfung zu erstellen. Und für die User im Forum ist es sicher auch praktischer :D

**Comment by n0ix** [comment]
Naja das finde etwas übertrieben. Wäre es auch ok wenn eine Verknüpfung im Zip-Archiv mit ausliefert?

**Comment by tox2** [comment]
Ja bevor ich hier aufgemacht habe, dachte ich mir das auch, aber ich denke das Verknüpfungsziel wird **je nach Ordner nicht automatisch angepasst**. 

Andererseits habe nicht genauer gegoggelt, wenn das jedoch mit der Verknüpfung funktioniert, wäre es ein Super Lösung. 👍
