### ISSUE TITLE
SFDL.net v3 Crash on Exit with "CLR20r3 " + "System.ApplicationException"

### ISSUE THREAD

**Issue by tox2** [n0ix/SFDL.NET#140]
betrifft so wie ich das im Forum mitbekommen habe nur alle  win7 win 8 und win 10 editionen. bzw. dort ist der Fehler bei 3 Usern aufgetreten.

Hab dazu einen Thread aufgemacht, weil man dort einfacher mit den Betroffenen Schreiben kann.

**Comment by tox2** [comment]
Log 1:

````
Problemsignatur:
  Problemereignisname:    CLR20r3
  Problemsignatur 01:    SFDL.NET 3.exe
  Problemsignatur 02:    3.0.0.7
  Problemsignatur 03:    58c585dd
  Problemsignatur 04:    mscorlib
  Problemsignatur 05:    4.6.1590.0
  Problemsignatur 06:    5787ed44
  Problemsignatur 07:    3a2f
  Problemsignatur 08:    29
  Problemsignatur 09:    System.ApplicationException
  Betriebsystemversion:    6.1.7601.2.1.0.256.48
  Gebietsschema-ID:    1031
  Zusatzinformation 1:    0a9e
  Zusatzinformation 2:    0a9e372d3b4ad19135b953a78882e789
  Zusatzinformation 3:    0a9e
  Zusatzinformation 4:    0a9e372d3b4ad19135b953a78882e789

Lesen Sie unsere Datenschutzbestimmungen online:
  http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0407

Wenn die Onlinedatenschutzbestimmungen nicht verfügbar sind, lesen Sie unsere Datenschutzbestimmungen offline:
  C:\Windows\system32\de-DE\erofflps.txt
````
Log2:
```
Anwendung: SFDL.NET 3.exe
Frameworkversion: v4.0.30319
Beschreibung: Der Prozess wurde aufgrund einer unbehandelten Ausnahme beendet.
Ausnahmeinformationen: System.ApplicationException
   bei System.Threading.Mutex.ReleaseMutex()
   bei SFDL.NET3.SingleInstance.Dispose(Boolean)
   bei SFDL.NET3.SingleInstance.Finalize()
````

**Comment by n0ix** [comment]
Danke fürs zusammen fassen. Bei mir hatten sich auch schon zwei leute via PN gemeldet. 

Wirklich eine Idee wie dieser fehler zustande kommt habe ich absolut nicht. Kann eigentlich nur eine Art Patch zuviel oder zu wenig sein. SOnst müsste es ja bei allen auftreten,

**Comment by tox2** [comment]
Keine Ahnung einen gemeinsamen Nenner hab ich auch nicht gefunden aus das...

`````
Ausnahmeinformationen: System.ApplicationException
   bei System.Threading.Mutex.ReleaseMutex()
   bei SFDL.NET3.SingleInstance.Dispose(Boolean)
   bei SFDL.NET3.SingleInstance.Finalize()
````

was seltsam ist vielleicht werden Threads nicht sauber geschlossen nach dem Download ?

**Comment by n0ix** [comment]
Aufgrund welchen Codes der Fehler auftritt kann ich dir sagen. Und zwar kommt das vom "SingleInstance" Code. 

**Was macht der?**
Der ist dafür zuständig das wenn eine Instanz vom Loader offen ist keine weitere geöffnet wird wenn man eine SFDL mit Doppelklick öffnen möchte. Bei WPF kann man das nicht so machen wie bei einer WinForms Anwendung. Daher habe ich etwas gegoogelt und dann Code von einer Beispiel Implementierung von Microsoft genommen.

**Was hat das mit dem Fehler zu tun?**
Sobald man die Anwendung beendet wird ein Mutex (Thread Lock  - damit wird erkannt ob die Anwendung bereits geöffnet ist) wieder freigegeben. Dabei wirft er dann aber einer Fehler. Warum er das tut -  keine Ahnung.

Ich hatte den Fehler einmal beim Debuggen. Habe dann aber (aus Verzweiflung da ich keine Ahnung hatte was jetzt los ist) meine VS neu gestartet - dann gings wieder.

**Comment by tox2** [comment]
ok 

````
17/03/2017 09:43 	<ZockerFloh7> 	aber es steht ja sogar die methode bei
17/03/2017 09:43 	<ZockerFloh7> 	gibt aber nen dumpfile, ka ob euch des was bringt
17/03/2017 09:43 	<ZockerFloh7> 	jo, nur öffnen und schließen
17/03/2017 09:43 	<tox2> 	also SFDL Loader starten (kein SFDL File öffnen+ kein download) + SFDL Loader schließen kommt der error ?

````

**Comment by n0ix** [comment]
Ich kann mal versuchen eine andere SingleInstance "Version" zu implentieren.

Das hier sieht ganz gut aus: https://elegantcode.com/2011/03/02/wpf-advanced-jump-lists-using-a-single-instance-application/

**Comment by tox2** [comment]
Sag mal n0ix in deiner Ereignisanzeige sind da die Error auch drinnen ? 
Ich hab denn error auch nur wird der mir nie gemeldet, anderen User schon :D 

![unbenannt](https://cloud.githubusercontent.com/assets/23582323/24035938/d905674c-0af7-11e7-8831-b11448f9fa98.png)

**Comment by tox2** [comment]
Das ist das selbe von oben oder ? 
https://www.codeproject.com/articles/84270/wpf-single-instance-application

**Comment by tox2** [comment]
bzw. das ist wieder das selbe ...
Macht wohl jeder via. Runtime.remoting ....

http://codereview.stackexchange.com/questions/20871/single-instance-wpf-application

**Comment by n0ix** [comment]
Maybe i fixed it: http://www.pastefile.com/rJgxRx

**Comment by tox2** [comment]
Bei mir kommt nichts mehr in der Ereignisanzeige, ist fixed ✅

**Comment by tox2** [comment]
Fixed ✅
