### ISSUE TITLE
FTP Reply 226 Result "in Unbekannter Fehler" | Speedy Overflow Error

### ISSUE THREAD

**Issue by tox2** [n0ix/SFDL.NET#141]
226 RCF ->Closing data connection. Requested file action successful (for example, file transfer or file abort).

Sowie das log das mit schreibt. 
````
2017-03-17 10:51:04.0135|INFO|FTPClient|226
[Bytes: 0][Time: 191.65 s][Speed: 0.00 K/s]
````
`2017-03-17 10:51:04.0135|ERROR|DownloadHelper|Die arithmetische Operation hat einen Überlauf verursacht.`

Das ding ist das es bei mir bei dieser einen [SFDL ](http://download.sfdl.net/ZnRwOi8vbGVlY2g6TUxDQk9BUkQyMDE1QDE0NC43Ni4xNTQuMTcwOjUyNDg3L1gyNjQtMTA4MFAtSEQtREUvQXNzYXNzaW5zLkNyZWVkLjIwMTYuR2VybWFuLkFDMy5EdWJiZWQuREwuMTA4MHAuQmx1UmF5LngyNjQtTVVMVGlQTEVYLw==)während des Downloads öfter und ständig auftritt...

Wenn das File das geladen wird 8GB hat.  

Unten folgen zwei Lade Versuche des SFDLs.

------
[log von versuch 1.txt](https://github.com/n0ix/SFDL.NET/files/850228/log.von.versuch.1.txt)

Ladete er im **ersten** Versuch bis zum Fehler Unbekannt bis:
````
Größe: 3,99 GB (4 294 965 619 Bytes)
Größe auf Datenträger: 4,00 GB (4 294 967 296 Bytes)
````
Und erstellte diesen Speedy:
`2019,91 MB in 00:06:42 heruntergeladen @ 5145,23 KB/s (Im Durchschnitt)`

-------

Versuch 2:
[log von Versuch 2.txt](https://github.com/n0ix/SFDL.NET/files/850243/log.von.Versuch.2.txt)

````
Größe:  5,99 GB (6 442 450 519 Bytes)
Größe auf Datenträger: 6,00 GB (6 442 450 944 Bytes)
````

Speedy: 

1983,01 MB in 00:03:19 heruntergeladen @ 10204,04 KB/s (Im Durchschnitt)

------

Das mit dem Speedy müsste der Überlauf Fehler sein.
Das mit dem Reply 226 keine Ahnung, ob das mit den Überlauf zusammenhängt, weil in meinen bisherigen versuchen, war der auch schon mal da. Hab aber nicht geguckt ob der Server 226 gesendet hat. 

Meine frage ist nun warum löst 226 da einen "Unbekannten Fehler" aus. bzw. Ist der FileStreamWrite Buffer voll und je nach dem kappt oder bricht die Server Verbindung ab ? 

Und Warum einmal nach 4GB (bzw. hat er 2GB+2GB geladen siehe LOG Versuch 1) und einmal nach 2 GB (im Versuch 2) ?

**Comment by tox2** [comment]
In der Mutex Fixed Version ist das mit dem 2GB- Unbekannter Fehler auch drinnen. 
Nur so als info.

**Comment by n0ix** [comment]
Cooler Fehler. Hier wird eine Integer Variable hochgezählt. Und Integer hat ein Limit von 2147483647 was ca. 2 Gb sind

**Comment by tox2** [comment]
kein long int ? in .net ?

**Comment by tox2** [comment]
oder sowas bzw unsigned int dann sind wir auf 4GB 😆

**Comment by tox2** [comment]
ist das beim Stream Writer und dem Buffer oder beim Speedy mit dem int 2GB ?

für denn Streamwriter müsste das "autoflush" doch denn buffer dann leeren und ohne abbruch weiter schreiben oder ? bzw. "FlushAsync()"
https://msdn.microsoft.com/en-us/library/system.io.streamwriter(v=vs.110).aspx

sonst sehe ich die File length kann man mit long als typ arbeiten vielleicht schafft der Abhilfe.

**Comment by n0ix** [comment]
Habe es einfach Long (int64) geändert. da sollte reichen :-)

**Comment by tox2** [comment]
Fixed ✅
