### ISSUE TITLE
i can download without starting Download Start :D 

### ISSUE THREAD

**Issue by tox2** [n0ix/SFDL.NET#142]
![select files none_still run](https://cloud.githubusercontent.com/assets/23582323/24044074/ddd47e44-0b19-11e7-85e4-797cc725e4ef.gif)

**Comment by n0ix** [comment]
Ich muss zugeben du findest schon immer ziemlich coole BUgs

**Comment by tox2** [comment]
xD
Ja der ist aber sogar praktisch bei testen muss einmal weniger klicken und der download läuft 😆 

sonst noch die zwei meldungen im englischen und alles andere was in 3.0.0.7 + 3.0.0.8  war ist behoben 🔝 

würde es dann auch zum Release Freigeben 👍  (die zwei kann man auch später mal fixen )

**Comment by tox2** [comment]
Fixed ✅
