### ISSUE TITLE
Meldung im Englischen für SFDL closed and Speedy  

### ISSUE THREAD

**Issue by tox2** [n0ix/SFDL.NET#143]
![eng](https://cloud.githubusercontent.com/assets/23582323/24044134/377117c8-0b1a-11e7-8a6c-af356526fb3b.PNG)

**Comment by n0ix** [comment]
Mit dem Speedreport ist schwierig. Ich könnte das Template anpassen, das hilft aber nicht wirklich da dies nur eingetragen wird wenn keine Einstellungen vorhanden sind.

**Comment by tox2** [comment]
egal lassen das dann offen 👍 
Meldung 1 und 3 stimmen 
die 2te nur so halb und 
die 4te ist einfach gleich wie im DE

**Comment by n0ix** [comment]
Man könnte das Template generell ins English halten. Ist dann internationaler. Was meinst du?

**Comment by tox2** [comment]
Jup wenn man nur sowas macht 
SFDL:
Upper:

Speedtime:
DownloadSize:
Speed: 

wenn das im forum steht passt das doch auch, meiner Meinung nach, jedoch am besten Seri fragen wie es am besten für die Breite Masse gedacht ist....

**Comment by n0ix** [comment]
Ok, gut dann lasse ich erstmal so. Kann dann mal später klären.
