### ISSUE TITLE
CRC Checking of Big Files takes very long time ... 

### ISSUE THREAD

**Issue by tox2** [n0ix/SFDL.NET#144]
Das [SFDL ](http://download.sfdl.net/ZnRwOi8vYnl0ZXdhcmV6OmxlZWNoQDE4OC4xNjUuMTk5LjEyMjoxNDU5MC9HYW1lcy9IaXRtYW4uVGhlLkNvbXBsZXRlLkZpcnN0LlNlYXNvbi5NVUxUaTktRWxBbWlnb3Mv)war das ... 

Das ist das log dazu. Man beachte die Zeiten ... bei mir mit der HDD 18min und der Loader zeigt 18 min einfach nur in Warteschlange, der User weiß nicht was los ist :D   

````
2017-03-18 18:03:35.5108|INFO|DownloadHelper|Check if CRC hashes match 
2017-03-18 18:03:52.0968|INFO|DownloadHelper|CRC Hash is Valid!
````

Die Frage ist, ich hab schon ein wenig gegooglt, aber kann man das bei einer bestimmten File Größe die Prüfung skippen oder einfach per Settings deaktivieren, bzw. dem User auch anzeigen das die CRC Prüfung läuft. Vielleicht sind ja andere Methoden die der Server zur Verfügung stellt ja besser für große Files.

Was sagst du @n0ix ? 
Hier unten der Link wegen CRC Optimierung .

https://www.codeproject.com/articles/1671/crc-generating-a-checksum-for-a-file

**Comment by tox2** [comment]
der sagt sogar das man die windows exe md5sum nehmen soll die ist sehr schnell. viel flotter als in .net das zu machen. http://stackoverflow.com/questions/1177607/what-is-the-fastest-way-to-create-a-checksum-for-large-files-in-c/1177712#1177712

**Comment by n0ix** [comment]
Wenn diese md5sum Binary wirklich soviel schneller ist, dann ist es wirklich eine Überlegung wert diese anstatt der .NET Implementation zu nutzen.

Bei CRC habe ich lange für einen guten Code gesucht. Hatte auch mal den von Codeproject, allerdings war dann die CRC Summe grundsätzlich anderst als die vom FTP Server (keine Ahnung wie die das implementiert haben). Mit der aktuellen Library hatte ich da die besten Ergebnisse. 

Allerdings muss man dazu sagen dass es mir wichtig war den Code möglichst nativ abbilden zu können. Wenn mann jetzt allerdings schon beim MD5 abweicht sollte man evtl. in betracht ziehen hier komplett auf eine externe Binary zu wechseln die alles abdeckt (MD5, SHA-1, CRC)

@tox2: Könntest du dich evtl die tage mal nach einer passenden binary umschauen?

**Comment by n0ix** [comment]
Habe mal kurz gegoggelt, evtl. wäre [CertUtil](https://superuser.com/a/898377) eine gute Lösung. weiß jetzt allerdings nicht wieviel schneller das ganze ist.

**Comment by tox2** [comment]
Jacksum sieht gut, wie gut ist die Performance? Werde das mal später testen :) 

bei certutil wäre auch gut. Würde dazu die Performance der beiden vergleichen und je nach dem was besser passt hier, dann posten.

**Comment by tox2** [comment]
Jacksum geht nur mit Java Leider :) 

**Jetzt frage ich mich was können die FTP Server denn alles so?**

Momentan habe ich das hier gefunden https://hashlib.codeplex.com/ wobei das wieder in .net drinnen hängt weiß ich nicht ob das schnell oder langsam ist.

Dann habe ich momentan eine Branch "https://github.com/n0ix/SFDL.NET/tree/7zip-as-extractor" für mich, weil ich meine Archive via 7z irgendwie schneller entpacken schaffe ich habe zu mindest das Gefühl. Werde dazu noch Benchmarks machen...

Aber Falls man zu 7z wechselt. 7z kann CRC32, CRC64, SHA256, SHA1, BLAKE2sp Hash summen berechnen. 7z kann sozusagen kein MD5.
Für MD5 entweder md5sum | CertUtil oder was es auch noch gibt ist via powershell das kann "SHA1;SHA256;SHA384;SHA512;MACTripleDES;MD5;RIPEMD160"..

`7z.exe h -scrc* -bt "1GB.rar" ` 
Hatte für alle Hash Summen bei mir 18s gebraucht.

`powershell -c "(Get-FileHash -a MD5 "1GB.rar").Hash"`
In ca. 7s fertig. 

`CertUtil -hashfile "1GB.rar" MD5`
In ca. 8s fertig.

Sag einfach welche Checksummen so unterstützt werden müssen ich werde da schon ein binary dazu finden :D

**Comment by tox2** [comment]
Hab noch was gefunden, http://www.slavasoft.com/fsum/index.htm
checksum algorithms: MD2, MD4, **MD5, SHA-1**, **SHA-2( 256, 384, 512)**, RIPEMD-160, PANAMA, TIGER,  ADLER32, **CRC32**;

`fsum.exe -crc32 -md5 -sha1 -sha256 -sha512 "1GB.rar"`
Ok das teil ist echt **schnell** für alle hat er zwar **120s** gebraucht aber im vergleich zur momentanten .net Sache echt schnell.

Und so:
`fsum.exe -crc32 -md5 -sha1 -sha256  "1GB.rar"`
ohne sha512 brauchte er nur **20s** 😆 

Bonus das teil kann sogar mit **.sfv Files sowie .md5 Files arbeiten** welche ja auch manchmal im SFDL drinnen sind. 

Man kann sogar mit *.rar alle berechnen und mit einer vorhandenen CHECKSUMFILE.txt selbst abgleichen. die CHECKSUMFILE.txt könnte der loader selbst erstellen und alle Checksumen der Files vom FTP eintragen oder falls die sfv datei da ist diese direkt nehmen. 

Was sagst du @n0ix ?

**Comment by n0ix** [comment]
> Sag einfach welche Checksummen so unterstützt werden müssen ich werde da schon ein binary dazu finden 

wir brauchen crc32, md5 und sha-1. Dabei ist CRC und MD5 am häufigsten und damit auch am wichtigsten.

> Momentan habe ich das hier gefunden https://hashlib.codeplex.com/ wobei das wieder in .net drinnen hängt weiß ich nicht ob das schnell oder langsam ist.

Da die Lib (wie du schon sagtest) komplett in .NET geschrieben ist wird hier der Performance Vorteil äußerst gering ausfallen. Daher fällt das denke ich raus.

- 7zip nur zum CRC32 berechnen finde ich etwas oversized

- Powershell wäre eine Option. Würde ich aber eher Certutil bevorzugen. Ist einfach etwas einfacher zu implementieren. Müsste man sich nur noch was für CRC überlegen.

- Fsum wäre Feature technisch wohl das beste nur bin ich nicht sicher ob wir das aufgrund der Lizenz (welche meines Erachtens ziemlich strikt ist) nutzen dürfen.

**Comment by tox2** [comment]
Läuft sehr gut Rhash hab gesehn man kann das auch als LIB in den Loader rein Kompilieren :D 

Bench (i52400 @ 3,10GHz mit SSHD 1TB):
````
>rhash.exe -C -H -M --percents --speed 1GB.rar
1GB.rar               100%
1GB.rar  fa7bbf43  6d202ab0d1809badc03bfa9abc95d783  8105d2cf251dbe8b27b997078bcca2c78358e1c3
Calculated in 9,480 sec, 105,48 MBps
````
Würde sagen wenn man das sogar als LIB rein kompiliert und nutzt kann ist Rhash perfekt. Vorteil sind einige unter anderem: 
a) mit --percents kann man den Hash Rechen Vorgang Im loader anzeigen lassen
b) mit der LIB müsste dann ja auch x64 x86 wegfallen (also 2 exe weniger ) nur eine dll ...


PS: 
Wegen dem mit 7z dachte ich mir nur, weil man in Zukunft mal auch Zip files entpacken lassen will.
Das die Porzent im Loader erscheinen hab ich auch soweit geschafft. 
Siehe im Branch https://github.com/n0ix/SFDL.NET/tree/7zip-as-extractor 7z verhält sich gleich wie unrar nur das man mehr Archive entpacken kann und meiner Meinung nach ist  7z schneller beim entpacken.

**Comment by n0ix** [comment]
Wenn du Lust und Zeit hast kannst das ganze mal testen. http://www.pastefile.com/AIfe4u

**Comment by tox2** [comment]
Bin mir nicht sicher aber ich denke ich habe einen BUG gefunden :) 

Und zwar bei dem SFDL (PW:MLC)-> http://www.xup.in/dl,70804901/DaVinci.sfdl/
ist beim part 4 laut server die CRC: "EBE359C" und wenn ich diese Selbst Berechne "0EBE359C"
Da verschluckt jemand die "0"  

[Part4_CRC_MissMatch_log.txt](https://github.com/n0ix/SFDL.NET/files/875547/Part4_CRC_MissMatch_log.txt)

**Comment by tox2** [comment]
![crc_check_mark_others stopped](https://cloud.githubusercontent.com/assets/23582323/24404781/d9cde93c-13c2-11e7-91f8-a5dda45ca340.gif)

Hier kurz ein Optik BUG, wo nach einem Erfolgreichen CRC Check von zb part 1 die anderen Parts als "Download Stopped" Markiert. kommt bei mir häufig vor, und passiert denke ich nur wenn Parts gleichzeitig fertig werden. siehe GIF beim Ersten Durchgang durch Zufall so wie ich es mir vorstelle. Beim 2ten jedoch werden zwei als "Download Stopped" Markiert.

LOG: Am Ende des Files sind die logs zum gif.
[CRC_Check_of_1GB_Files.txt](https://github.com/n0ix/SFDL.NET/files/875625/CRC_Check_of_1GB_Files.txt)

**Comment by n0ix** [comment]
Das hier die 0 "verschluckt" wird ist wohl nicht weiter schlimm. Ist evtl. auch nur ein Problem der Log Ausgabe denn die Hashes sind offensichtlich gleich.

`2017-03-28 14:04:34.6125|INFO|FTPClient|250
EBE359C

2017-03-28 14:04:34.6125|INFO|DownloadHelper|Hash server side successfully determined!
2017-03-28 14:04:34.6125|INFO|DownloadHelper|Check if CRC hashes match 
2017-03-28 14:04:34.9876|INFO|DownloadHelper|CRC Hash Invalid`

**Comment by tox2** [comment]
Naja wenn sie doch gleich sind dann müsste CRC HASH Valid stehen er schreibt aber invalid weil ja die 0 fehlt.

**Comment by n0ix** [comment]
Oh sry falsch gelesen. Keine Ahnung wo die Null hingeht. Ist auch nur die Server ANtwort. Da werde ich nicht viel machen können.

**Comment by tox2** [comment]
CRC haben immer die länge von 8 Zeichen, vielleicht muss man selbst die Nullen davor eintragen
"EBE359C" hat nur 7 zeichen

**Comment by tox2** [comment]
in der anderen Version tritt der BUG mit der 0 Nicht auf

**Comment by n0ix** [comment]
Kann sein, vermutlich berechnet RHash den CRC Hash anders bzw. nicht gleich wie die FTP Server.

**Comment by tox2** [comment]
das ist der log von 3.0.0.9 ohne rhash 

````
2017-03-28 15:14:26.0555|INFO|DownloadHelper|Server supports Hash Alogrightm XCRC
2017-03-28 15:14:26.0555|INFO|FTPClient|XCRC
/BlackMagic.Design.Davinci.Resolve.12.5.2.010/DaVinci_Resolve_12.5.2_Windows.part4.rar

2017-03-28 15:14:26.1216|INFO|FTPClient|250
EBE359C

2017-03-28 15:14:26.1216|INFO|DownloadHelper|Hash server side successfully determined!
2017-03-28 15:14:26.1216|INFO|DownloadHelper|Check if CRC hashes match 
2017-03-28 15:14:26.8476|INFO|DownloadHelper|CRC Hash is Valid!
2017-03-28 15:14:26.8476|INFO|DownloadHelper|Download was stopped or item was not fully downloaded - skipping Hash Check
2017-03-28 15:14:26.8636|INFO|SpeedreportHelper|Nothing was downloaded - Skipping Speedreport generation
2017-03-28 15:14:26.8676|INFO|DownloadCompleteCallback|All downloads cancled/stopped
````

**Comment by n0ix** [comment]
Laut hier http://stackoverflow.com/questions/20993557/wrong-crc32-hash-in-android könnte es allerdings wirklich sein das die 0 abgeschnitten wird. Da ein Null vorne daranzubasteln sofern die länge 7 ist, ist nicht das Problem. Ob das dann allerdings "richtig" ist - kp.

**Comment by tox2** [comment]
wenn man die Zahl statt string, als HEX Zahl 0x0EBE359C vergleicht passt dass immer

**Comment by n0ix** [comment]
ok, als FTP Antwort bekomme ich aber nur String und kein HEX. Von daher werde ich jetzt einfach mal einen 0 vorne dranbasteln :-D

Findest du dass die CRC Berechnung jetzt schneller ist? ich persönlich finde (rein gefühlsmäßig) das sogar ein tick langsamer ist.

**Comment by tox2** [comment]
echt bei mir dauert die statt 18min nur 3 sekunden :D

**Comment by tox2** [comment]
kann man denn string nicht in ein hex zahl Konvertieren ?

**Comment by n0ix** [comment]
Schon möglich, kann mir aber nicht vorstellen dass da dann eine Null hingezaubert wird.

**Comment by tox2** [comment]
Actually, I realized this would be wrong for any characters ≤ 0x0F, because of the missing zero padding. To fix that, use ToString("X2") sowas 🗡 
http://stackoverflow.com/questions/16999604/convert-string-to-hex-string-in-c-sharp

**Comment by n0ix** [comment]
Sorry, aber ich steh auf dem Schlauch. Ich verstehe nicht was das bringen soll. Wenn der einfachheit halber den Hash EBE359C in einen [Online Converter ](http://www.online-toolz.com/tools/text-hex-convertor.php) rein haue, dann kommt da etwas raus was sicher kein CRC Hash ist. Mir ist es auch neu das man Buchstaben in HEx umwandeln kann. Ich dachte das macht man nur mit zahlen.....

**Comment by tox2** [comment]
https://social.msdn.microsoft.com/Forums/en-US/7bb492d1-7079-46da-aaf5-14b39627b5eb/adding-leading-zeros-to-string?forum=vblanguage

ja es geht ja darum das man denn String einfach auf die 8zeichen mit denn nötigen Nullen auffüllt, ein convert ist es nicht in dem Sinne. vielleicht hilft der obere Link

**Comment by tox2** [comment]
also das müsst ja klappen meiner Meinung nach `myString = myString.PadLeft(desiredLength, "0"c)`

**Comment by n0ix** [comment]
Ok, ich glaueb zu verstehen auf was du hinaus willst. Du willst sicherstellen dass wenn der Korrekte Hash 00BE359C wäre das das dann auch auch die 2 Nullen aufgefüllt werden da du berfüchtest das die FTP Antwort BE359C lauten würde. Richtig?

**Comment by tox2** [comment]
0EBE359C ja genau weil CRC32 immer 0x12345678 8zeichen lang ist bzw 0x00001234 denn rhash gibt denn CRC wert auch mit Nullen zurück

**Comment by n0ix** [comment]
Hätte es nun so gelöst

```
   _log.Info("Check if CRC hashes match ")

                        If ToHexString(RHash.Hasher.GetHashForFile(_item.LocalFile, RHash.HashType.CRC32).ToLower).Equals(ToHexString(_item.FileHash.ToLower)) Then
                            _log.Info("CRC Hash is Valid!")
                            _item.DownloadStatus = NET3.DownloadItem.Status.Completed_HashValid
                        Else
                            _log.Info("CRC Hash Invalid")
                            _item.DownloadStatus = NET3.DownloadItem.Status.Completed_HashInvalid
                        End If

 Public Shared Function ToHexString(str As String) As String
        Dim sb = New Text.StringBuilder()

        Dim bytes = Text.Encoding.Unicode.GetBytes(str)
        For Each t In bytes
            sb.Append(t.ToString("X2"))
        Next

        Return sb.ToString()
    End Function
```

Hast du mir das File wo der CRC Hash mit einer NUll anfängt?

**Comment by tox2** [comment]
Hier ist das SFDL 
SFDL (PW:MLC)-> http://www.xup.in/dl,70804901/DaVinci.sfdl/
ist beim part 4 laut server die CRC: "EBE359C" und wenn ich diese Selbst Berechne "0EBE359C"

**Comment by n0ix** [comment]
Also das mit dem Hex klappt überhaupt nicht. `_item.FileHash = _item.FileHash.PadLeft(8, "0"c)` hingegen klappt einwandfrei.

**Comment by tox2** [comment]
Ja perfekt dann werden sich hoffentlich weniger User über CRC Failed in Zukunft wundern  👍 
Die dachten dann oft das weil CRC Falsch war das File neu geladen werden musste 😆

**Comment by n0ix** [comment]
Prima, dann mach hier zu,

**Comment by tox2** [comment]
Was hat es mit dem Verhalten auf sich. ? Der User hat ja eigentlich nie den Stopp Button gedrückt ?
Wie hängt das mit dem Beenden des Downloads Zusammen ?

Man muss nichts daran wollte es aber einfach anmerken das es doch verwirrt :D 

----------

![crc_check_mark_others stopped](https://cloud.githubusercontent.com/assets/23582323/24404781/d9cde93c-13c2-11e7-91f8-a5dda45ca340.gif)

Hier kurz ein Optik BUG, wo nach einem Erfolgreichen CRC Check von zb part 1 die anderen Parts als "Download Stopped" Markiert. kommt bei mir häufig vor, und passiert denke ich nur wenn Parts gleichzeitig fertig werden. siehe GIF beim Ersten Durchgang durch Zufall so wie ich es mir vorstelle. Beim 2ten jedoch werden zwei als "Download Stopped" Markiert.

LOG: Am Ende des Files sind die logs zum gif.
[CRC_Check_of_1GB_Files.txt](https://github.com/n0ix/SFDL.NET/files/875625/CRC_Check_of_1GB_Files.txt)

**Comment by tox2** [comment]
Fixed ✅
