### ISSUE TITLE
Subfolder are not loaded into their parent Subfolder [by Shiva]

### ISSUE THREAD

**Issue by tox2** [n0ix/SFDL.NET#145]
Im Forum hat Shiva was aufdecken können.

Hab hier ein Test SFDL was zeigt das Folder mit dieser Struktur:

- Folder_Level0
  - Folder_level1
    - Folder_level2
      - Folder_level3

Als solche geladen werden: 

- Folder_Level0
  - Folder_level1
  - Folder_level2
  - Folder_level3

Was dann in Shivas Fall dazu führt das alle Sample in einen Ordner kommen...

http://xup.in/dl,12414822

**Comment by n0ix** [comment]
Hallo,

halte ich nicht für sinnvoll das einzubauen. Einfach die Option"Unterordner pro Paket" und schon ist das Thema gegessen. Dafür ist die Funktion schließlich auch da. Wenn man das nämlich ändert beschwert sich jemand anderes das hier so viele Unterordner erstellt werden...

**Comment by tox2** [comment]
ja das mit dem "Unterordner pro Paket" würde ja klappen nur macht shiva einen Bulkfolder "Gesamte Serie" mit "Season01-*" als ein Paket.. siehe SFDL.

Damit das mit dem "Unterordner pro Paket" geht müsste er für jede Season einen Bulkfolder erstellen. 
Denke das ist für ihn umständlich, keine Ahnung.

**Comment by n0ix** [comment]
> ja das mit dem "Unterordner pro Paket" würde ja klappen nur macht shiva einen Bulkfolder "Gesamte Serie" mit "Season01-*" als ein Paket.. siehe SFDL.
Damit das mit dem "Unterordner pro Paket" geht müsste er für jede Season einen Bulkfolder erstellen.

Ja natürlich. Das ist ja auch Sinn der Pakete. Sonst könnte man diese ja auch gleich weglassen.  Ob ihm das zu "umständlich" ist, ist mir ehrlich gesagt egal. Das ist das SFDL format ist so und fertig.

Ich mach viel um das leben einfacher zu machen aber bisschen was denken/arbeiten müssen die Damen und herren dann eben doch

**Comment by tox2** [comment]
Alles klar, schließe dann hier mal 👍
