### ISSUE TITLE
[Feature] Reset Settings

### ISSUE THREAD

**Issue by n0ix** [n0ix/SFDL.NET#146]
Add Button to reset all Settings to default

**Comment by tox2** [comment]
Als hinweis ich würde parallel zum "All Settings Reset" noch, einen Button neben "SFDL Information" einfügen welcher einfach die Maske resetet "Standard Maske"  oder so. 

Beim "All Settings Reset" wird ja alles betroffen sein, so wie ich das von goofy gelesen habe wollte er nur die Maske wieder so wie im Default haben. 
![image](https://cloud.githubusercontent.com/assets/23582323/24322703/d9938932-1169-11e7-84da-bf1322798f56.png)

**Comment by n0ix** [comment]
So gut?

![image](https://cloud.githubusercontent.com/assets/17708302/24397543/d3794e3a-13a6-11e7-9ddb-b5574498441a.png)

**Comment by tox2** [comment]
Sieht geil aus 👍

**Comment by tox2** [comment]
Fixed ✅
