### ISSUE TITLE
URL: sfdl.net/download verweist auf alte Version

### ISSUE THREAD

**Issue by tox2** [n0ix/SFDL.NET#147]
Die Link unten verweist auf Version 3.0.0.7 
http://sfdl.net/download/ ->  https://github.com/n0ix/SFDL.NET/releases/download/3.0.0.7/SFDL.NET_3.0.0.7.zip

![old version](https://cloud.githubusercontent.com/assets/23582323/24321639/65f31df2-1151-11e7-94b7-e13fbacba601.PNG)

Könnte man hier einfach auf denn LINK unten Verweisen ?
https://github.com/n0ix/SFDL.NET/releases/latest

Es gibt etliche User die sich noch über denn einen oder anderen Bug in 3.0.0.7 zu Wort Melden...
Obwohl in der Ecke Update verfügbar steht. Aber um die Seite nicht ständig ändern zu müssen ist der Link doch praktisch :D

**Comment by n0ix** [comment]
Danke für den Hinweis. Habe es geändert.

**Comment by tox2** [comment]
Fixed ✅
