### ISSUE TITLE
[Feature] Improve/Add Priority Handling

### ISSUE THREAD

**Issue by n0ix** [n0ix/SFDL.NET#148]

**Comment by n0ix** [comment]
Ich muss nochmal nachfragen was hier genau gewünscht wurde. Habe ich es richtig in Erinnerung dass via Einstellungen festgestellt werden kann, dass die Sessions/Pakete sequenziell abgearbeitet werden und **nicht** freie Threads (wenn man z.B 10 im Loader eingestellt hat) verwendet werden um bereits eine zweite, dritte etc. Session bereits anfangen zu laden.

**Comment by tox2** [comment]
Genau, man soll die "Sichtweite" des Loaders für aktive Pakete auf 1 Paket beschränken können. bzw. immer dass erste unfertige Paket laden dürfen. 

So nach dem Motto load max. 1 Package with max. 3 Threads... 

Da man jetzt dann nur schwer die Reihenfolge der Pakete ändern kann, wird das seltsam beim Umsetzten es sei denn man kann in diesem ListView die Reihenfolge (user seitig) ändern.

Beim Lösungsprozess stehe ich gerne Hilfsbereit zur Stelle. Sag einfach bescheid. 
Zu zweit denke ich werden wir hier schon was tricksen können 😆

**Comment by n0ix** [comment]
Also, als Besipiel -> Rechtsklick Session -> Mit höhster Prio laden.

Hat zur folge: es werden erst alle parts in dieser session geladen bevor etwas anderes angefasst wird.

**Comment by tox2** [comment]
Wäre denke ich auch eine Möglichkeit wenn nicht sogar die Bessere, wird man dann im Feldversuch merken.

**Comment by n0ix** [comment]
habe mal eine Version gebastelt womit es möglich ist ein oder mehrere Sessions zu priorisieren.

Man muss dazu recht auf den pfeil klicken. aktuell gibt es dazu noch keine visuelle Rückmeldung.

Ich hab folgende Szenarios getestet:
- Prio für ein oder mehere (2) Sessions vor dem Download erhöht
- Prio für eine Session während eines laufenden Downloads mit Sessions erhöht.

http://www.pastefile.com/1QRPYW

**Comment by tox2** [comment]
habe auch mal etwas versucht, ist ja noch in Beta. Aber vielleicht hier der hinweis auf das eine oder andere Deadlock :) 


Einmal als gif -> http://www.xup.in/dl,61151469/Neues_Prior_Bugs.gif/
und einmal dasselbe als mp4 (x2 Speed, weiß nicht warum das ScreentoGif das so macht)
http://www.xup.in/dl,20496516/Neues_Prior_Bugs.mp4/

Dauer 8min/4min

LOG: 
[Prio_DeadLocks.log.txt](https://github.com/n0ix/SFDL.NET/files/1020039/Prio_DeadLocks.log.txt)

PS: finde das funktioniert schon ganz gut, hat zumindest genau denn Effekt denn die User haben wollen.
Würde es aber noch ausgiebiger testen, bevor sie alle jammern :P

**Comment by n0ix** [comment]
Soo hier nochmal eine version. die deadlocks sollten weg sein.

http://www.pastefile.com/nOWacX

**Comment by tox2** [comment]
Ja die gröberen sind weg, hatte nur mehr noch einen/zwei. Konnte aber auf Grund Zeitmangel dazu kein Video machen.

Habe folgendes gemacht wieder 4 Pakete geöffnet, dann mit dem 3 Paket (prior) angefangen dann während des Downloads auf 2 gewechselt dann wieder während dessen Downloads auf 1 gewechselt.
1 fertig geladen, 2 fertig geladen, während des 2ten Ladens aber dann auf Paket 4 (prior) gesetzt. Dies Paket 4 **wollte leider nicht** starten zu laden, er lud dann 3 weiter. Habe dann Download gestoppt und Paket 3 geschlossen. Dann ging Paket 4, war ja nur das einen mehr drinnen und noch die Pakete 1&2 welche fertig waren. Während des Download 4 dann ein Paket 5 geöffnet und auf prior gesetzt, er lud aber **dennoch immer 4 weiter...**

Soll ich dazu ein Video machen, oder Reicht das als Info vorerst ?

**Comment by n0ix** [comment]
Ich gehe das mal gedanklich durch.

1. Schritt. Es sind 4 Pakete und wir starten den Download.
 --> Der Loader packt alle Files welches markiert sind in eine Warteschlange und arbeitet diese ab.
2. Schritt: Wir priorisieren das 3. Paket
---> Alle Files in der Warteschlange werden gecanceld, außer diese die bereits schon laufen und die der Session welche wir angeklickt haben.

Der loader wird jetzt sobald wieder ein File fertig wird "fragen" welche Files er aus der Session Liste nehmen soll. Hier wird so eingeschränkt das nur Files aus session's genommen werden welche das "isHighPrio" Flag besitzen. Sprich es gibt keine HighPrio Reihenfolge.

Du hast jetzt noch 2 Weitere Pakete als high Prio markiert. Es passiert nichts anderes als dass jetzt eben mehr sessions abgefragt werden dürfen. allerdings dürfen immer nur files einer high prio session verarbeitet werden.

> Dies Paket 4 wollte leider nicht starten zu laden, er lud dann 3 weiter.

Sollte klar sein wieso das passiert oder?

>  Dann ging Paket 4, war ja nur das einen mehr drinnen und noch die Pakete 1&2 welche fertig waren. Während des Download 4 dann ein Paket 5 geöffnet und auf prio gesetzt, er lud aber dennoch immer 4 weiter...

Warum sollte der loader mit Paket 5 anfangen. du hast doch Nr. 4 Priorisiert.


Was ich aus deinem test ablese: der Benutzer erwartet dass die Pakete in der Reihenfolge abgearbeitet werden in diese priorisiert wurden. Das kann der loader aber zum aktuellen zeitpunkt nicht. Da muss ich dann wohl noch etwas hirnschmalz reinstecken.

**Comment by tox2** [comment]
Denke es wäre leichter zu verstehen wenn man mit dem Button dort die Priorität Stufe erhöhen kann, dann kann man das automatisch im Hintergrund laden lassen sobald diese gesetzt sind.

Sagen wir haben 5 Pakete:

1. Paket: Prio Stufe 4
2. Paket: Prio Stufe 1
3. Paket: Prio Stufe 3
4. Paket: Prio Stufe 5
5. Paket: Prio Stufe 2

wenn man dann neben den Button die Stufe sieht kann man sich die Reihenfolge beliebig einstellen und es ist transparenter wie der Loader wird. Geladen wird dann immer die Höchste Stufe also in dem Fall oben (Paket 4 > 1 > 3 > 5> 2 ) 

Neu geöffnete Pakete Nr. 6 bis X bekommen die Prio 0, Pakete mit Prio 0 werden simultan geladen. Bis man deren Prio erhöht.  

Ist das ein möglicher Ansatz ?

**Comment by tox2** [comment]
Zum thema oben was ich mir dachte das der Button tut in meinen Testfall ist dass, das zuletzt gewählte Paket dann die höchste prio bekommt und folglich gestartet wird.

**Comment by tox2** [comment]
Quick Feedback, Das man in der vorab version die Priorität sieht ist super.
Jetzt ist nur so ich kann bei mir diesen Counter  mit einem Klick bei 2 Paket gleichzeit erhöhen ?

Falls das noch nicht bekannt ist:

Siehe gif.

![priority counter increases 2 times](https://cloud.githubusercontent.com/assets/23582323/26763451/51dcc95a-4953-11e7-93aa-91c8a175d38b.gif)

**Comment by n0ix** [comment]
Hi tox,

tut mir leid wenn ich mich erst jetzt melde.

Ist aktuell byDesign so, und jetzt wo ich das sehe macht das natürlich nicht so wirklich sinn. Schaue es mir nochmal an.

**Comment by n0ix** [comment]
Kannst du dir es bei gelegenheit nochmal im Release 'SFDL.NET_24062017_NIGHTLY' anschauen?

**Comment by tox2** [comment]
Klar, vorerst es läuft bei mir nun Deutlich besser. Also bis auf ein paar Merkwürdigkeiten. 

- Prio wird manchmal um mehr als 1 erhöht (+2, x2 ?)
- Pakete mit gleicher Prio wie zb. Prio 3 wurden bei mir nicht simultan geladen. (Sequenziell wahrscheinlich schon wollte aber nicht warten bis das Paket 2 fertig ist. Würde soweit dann auch gut sein. )
- Es kommt vor das wenn ein Paket fertig geladen wird das nächste Paket in der Warteschlange mit der nächst höheren  Prio. nicht von selbst startet. Erst nach User Stopp/Start. 

Test Szenario war wie folgt. 2 SFDLs öffen.


- Paket Nr. 2, Prio auf 1 erhöhen.
- Download start.
- Paket Nr. 1, **Prio erhöhen, statt 1 bekam ich den Wert 2 direkt nach einmal drücken :)** 
- Download stopp.
- Download start, um zu sehen ob nun Paket Nr. 1 geladen wird, und es wird geladen.
- Download stopp.
- Paket Nr. 2, Prio auf 3 erhöhen.
- Download start.
- Paket Nr. 3 öffnen, während des Downloads.
- Paket Nr. 3, Prio erhöhen, da kam nach drei mal drücken dann Prio 3.
- Download stopp.
- Download start um zu sehen ob nun beide Prio 3 Pakete (Nr. 2 und Nr. 3) gestartet werden. **Gestartet wurde nur Nr. 2.**
- Paket Nr. 3, Prio erhöhen auf 4.
- Download stopp.
- Download start Paket Nr. 3 ladet. Passt soweit.
- Paket Nr. 3 wird fertig geladen.
- Hier setzt dann Paket Nr. 2 seinen Download normal fort. Passt soweit, Alles.
- Paket Nr. 2 ladet, **während dessen erhöhe ich Paket Nr. 1 Prio nach einmal drücken von 2 auf 4.**
- Download stopp.
- Download start.
- Paket Nr. 1 ladet, dann passend weiter. 
- Nachdem Paket Nr. 1 fertig geladen wurde. 
- **Paket Nr. 2 startet nicht von selbst, erst nach** 
- Download stopp.
- Download start.
- Downloads Fertig.

Die Download stopp/start Sachen sind deswegen drinnen weil Paket Nr. 2 sehr große Files hat und ich nicht warten wollte. Normal jedoch nicht getestet vorerst ladet der Loader dann ja das richtige Paket, sobald die laufenden Downloads fertig sind. 

Sry das ich kein Gif dazu habe. Falls nötig werde ich das machen.



Gruß tox2

**Comment by n0ix** [comment]
Hallo,
ich glaube ich muss hierzu noch etwas erklären.

Es kann mehrere pakete mir Prio=0 geben allerdings immer jeweils nur ein Paket mit Prio > 0.

**Aktuelles verhalten:**

Wir gehen von folgendem aus: Paket X = 0, Paket Y =0, Paket Z = 0

Paket X wird erhöht --> Paket X = 1
Paket Y wird erhöht --> Paket X hat schon Prio 1 --> Paket Y = 2


**Im Release davor hatte ich es wie folgt:**

Wir gehen von folgendem aus: Paket X = 0, Paket Y =0, Paket Z = 0

Paket X wird erhöht --> Paket X = 1
Paket Y wird ehöht --> Paket Y= 1--> Paket X hat schon Prio 1 --> Paket X = 2

**Comment by tox2** [comment]
Im Realtime Operating OS, gibt es zu dieses Problem mehrere Lösungen eine davon ist ein simpler Ansatz. Mit dem Namen priority celling. (gibt sicher im Internet Erklärungen).

Man geht aber her und sagt wenn mehrere Pakete/Tasks wie bei uns hier eine Ressource haben wohlen, in unserem Fall denn gesamten Netzwerk Durchsatz (Ressource). 
Dann gibt man Denjenigen Paket/Task die höchste Prio. (Max Prio von allen Paketen +1 ) 
Und unser Scheuleder wäre dann ein oder mehrere Download Fertig Ereignisse in dem anderen Paket/Task. 

Was bei mir im oberen Testlauf passiert ist war folgendes.
Ich hatte zwei Paket X und Y. 
diese haben sich ganz normal nach deiner Beschreibung "Aktuelles Verhalten" verhalten.
Nach dem öffnen von Paket Z kann man dann per Mausklicks die Prio des Paket Z auf eine Prio  der Anderen zwei Pakete setzten, was nach deiner Beschreibung ja nicht sein darf.

Würde man hier die Regel, einführen onButtonpressed-> get MaxPrior-> set PaketPrio=MaxPrio +1 
Würde man das soweit gelöst haben bis man and MaxPrior Grenze anstößt (im RealTime OS oft schon bei 255). Da kann man aufräumen wenn alle Pakete/Tasks fertig sind wird die MaxPrio wieder auf 0 gesetzt etc. 

Ob das nun bessere ist kann ich nicht sagen es verhindert zumindest sogenannte "Deadlocks" und "Starvations" von Paketen/Tasks und wenn der Scheuleder regelmäßig die Reihenfolge prüft und verwalten ladet alles sauber durch. 

So einen Deadlock, wo Paket Nr. 2 erst nach Download Stopp/Start angefangen wurde zu laden, hatte ich ja gestern beim Test auch.

**Comment by n0ix** [comment]
Hi tox,

sorry aber ich verstehe nur größtenteils nur bahnhof. was ist denn bitte "realtime operatin os"?

**Comment by tox2** [comment]
Kurz gesagt wenn du bei Windows einen Prozess/Task/Anwendung startest dauert der mal 1min mal 2min etc. Bei sogenannten Real-time OS https://en.wikipedia.org/wiki/Real-time_operating_system 
Ist die dauer der Prozesses deterministisch also berechenbar und planbar. zb. Task Prozess/Task/Anwendung A dauert immer 1min. egal was passiert. Und das nur auf Kernel Prozesse Bezogen, User Prozesse also Selbst geschrieben Funktionen können da hingen zeitlich nicht vorhersehbar sein.   

Aber in unserem Fall müssen wir nichts davon wissen was RTOS sind. Wollte nur sagen um dort diese Reihenfolge von Task/Prozessen zu koordinieren gibt es verschiedene Lösungsansätze, eines heißt eben davon. priority celling. 

Kannst wenn du bock hast auch alles nachlesen, leider habe ich dazu kein gutes Lese-material dazu, Jedoch können wir das Grundprinzip kopieren. 

**Indem wir Max Prio von allen Paketen +1  setzen [ onButtonpressed-> get MaxPrior of all Packets-> set PaketPrio=MaxPrio +1 ]** 

Momentan ist es ja ähnlich umgesetzt, wo bei ich mir unsicher bin das der Loader zum onButtonpressed alle Prioritys prüft und die größte davon nimmt. 

onButtonpressed ist für mich jedes mal wenn man denn Button neben den X drückt um die Priority zu erhöhen.

**Comment by n0ix** [comment]
Hi tox,

wieder was gelernt. Im prinzip ist es so programmiert du es meinst. durch einen "SyncLock" wird verhindert dass "jemand anderes" die prio verändert solange die Prio Änderung durchgeführt wird.

Im Code findest du das hier: https://github.com/n0ix/SFDL.NET/blob/master/SFDL.NET%203/Classes/ViewModels/MainViewModel.vb#L1654

Ich schaue mir das aber nochmal an. Evtl. finde ich morgen abend dazu Zeit.

**Comment by tox2** [comment]
Hi n0ix,

habe hier mal ein GIF um das hervorzuheben. Ist das normal ? Das der Download stecken bleibt. Und ich die Prios gleich setzten kann? würde hier nach sourcecode sagen das mit any ist zwar gut jedoch müsste noch sichergestellt werden das man die höchste prio hat.

Anbei kann man nach nicht erfolgreichen Retries Eine Meldungen an den User weitergeben, in dem dann im Status Reiter beim Part eine Meldung steht, das der Server Voll ist bzw. Retry versuche nicht erfolgreich. Es ist nicht immer der Fall das diese Meldung kommt. Muss dazu auch noch ein GIF zaubern. 
Hab von ein paar Usern gehört via Shoutbox dass das recht nervig ist und die Downloads als solche nicht mehr erkenntlich sind was noch fehlt. (mache dann dazu ein neues Issue auf 😄 )

http://www0.xup.in/exec/ximg.php?fid=21474191

Gruß tox2

**Comment by n0ix** [comment]
Hi,

also das mit der doppelten Prio (sprich 2 Container haben dieselbe Prio) habe ich gefixxt ( 51a6f04 ).
Jetzt haben wir ja noch das "Problem" bei folgendem Szenario:

Wir haben 3 Container geöffnet. Ich erhöhe die Prio von 2 Containern. Daraus ergibt sich , dass wir folgende Prio's im "Spiel" haben: _(Paket X)_ 0, _(Paket Y)_ 1, _(Paket Z)_ 2. Wenn ich jetzt möchte das Paket X mit der Prio 0 nur eine "Stufe" weiter nach oben geht ,dann geht dass nicht, da Paket X dann die Prio 3 bekommt.

Das finde ich nicht so schön, daher werde ich versuchen das mal so umzusetzten

**Comment by tox2** [comment]
Wieso unschön das passt doch oder? 
wenn man Paket X dann per 1mal Klick ganz nach obensetzt. Ist für mich auch schlüssig. Anhand der Prio-Zahl sieht der User dann auch die Prio Lade Reihenfolge. und dadurch kann er/sie es sotieren wie er/sie will :D 

Wichtig war ja das mit diesen ich nenn es Mal Prio System, der user die Lade Reihenfolge einstellen kann und keine Prios doppelt sind. zudem darf das Prio System keine Aussezter habe, wenn der user das einstellt 1h weg geht und wieder kommt das dann Paket X geladen wurde aber Paket abc stecken bleiben.

Das würde grob doch alles dann sauber ablaufen. Unter den oben genannten voraussetzungen.

**Comment by n0ix** [comment]
So ich glaube ich habs (so wie ich es wollte). Pls try it :-)

http://www.pastefile.com/b5dfn2

**Comment by n0ix** [comment]
Ich überlege noch grade die Prio änderung während des Downloads zu verbieten. Befürchte nämlich dass wir uns damit eine menge Probleme einhandeln. Wenn man die Prio vor der Download definiert funktioniert (soweit ich das getestet habe) alles wunderbar

**Comment by tox2** [comment]
Das könnte man tatsächlich verbieten :D 
Mal testen das gute Teil :P

**Comment by tox2** [comment]
Geht deutlich besser als vorher, 
Punkt A würde die Prio während des Downloads Verbieten weil sonst der Loader durcheinander kommen kann. Und sonst ist mir noch aufgefallen das wenn man bereits geladene Pakete im Loader hat die eine Prio haben dann werden die niederen nicht mehr gestartet. Wobei wenn man den Punkt A hat und vielleicht sogar das hinzufügen von neuen Paketen via. Öffnen verbietet läuft das ding.

**(Nach dem Kurzen Test) würde eine Beta version davon an die User verteilen um zu sehen ob die echt stabil ist.** 

Und in der Finalen Version 3.0.1.2 bzw 3.0.1.3 das mit dem Retry etwas besser machen dort würden die User wollen das wenn die Retrys nicht erfolgreich sind als Server was auch immer der Hacken vom Part nicht verschwindet sondern bleibt. und Vielleicht das wenn ein Retry gerade am laufen ist dieses durch einen Download stopp auch mit abgebrochen wird. und damit auch der Status geändert wird momentan bleibt da einfach stehen.

**Comment by n0ix** [comment]
> Und sonst ist mir noch aufgefallen das wenn man bereits geladene Pakete im Loader hat die eine Prio haben dann werden die niederen nicht mehr gestartet.

Den punkt habe ich leider nicht so recht verstanden.

> (Nach dem Kurzen Test) würde eine Beta version davon an die User verteilen um zu sehen ob die echt stabil ist.

Beta Version mach ich gerne. Allerdings hat die erfahrung gezeigt dass die absolut nix bringt. außer (gefühlt) 10 Leute nutzt diese dann eh niemand. Und somit bekommt man auch so gut wie kein Feedback.

Zum dritten Punkt - können wir das in einer extra Issue nochmal angehen? Wenn wir das hier mischen blickt man nix mehr.

**Comment by tox2** [comment]
> Den  punkt habe ich leider nicht so recht verstanden.

Ja ist etwas blöd denn hatte ich jetzt einmal und kann ihn nicht rekonstruieren... :) egal wird vielleicht den 5 Leuten auffallen.

> Beta  Version mach ich gerne. Allerdings hat die erfahrung gezeigt dass die absolut nix bringt. außer (gefühlt) 10 Leute nutzt diese dann eh niemand. Und somit bekommt man auch so gut wie kein Feedback.

würde schon reichen wenn die User das testen die es auch nutzten als alle die im Thread das gewünscht haben. Jeder User bedient den Loader ja anders um hier schon mal etwaiges abzufangen bevor dann alle mekern :D 

> Zum  dritten Punkt - können wir das in einer extra Issue nochmal angehen? Wenn wir das hier mischen blickt man nix mehr.

Klar, muss mal einen Server dafür finden der das Auslöst. dann mache ich ein GIF/Video dazu. :)

**Comment by n0ix** [comment]
> Klar, muss mal einen Server dafür finden der das Auslöst. dann mache ich ein GIF/Video dazu. :)

GIF muss nicht sein. führe dass thema dann in #156 fort.

**Comment by n0ix** [comment]
Ich habe keinen Fehler mehr gefunden und auch nix gehört. Du? Wenn nicht machen wir hier erstmal zu :-)

**Comment by tox2** [comment]
Könn ma zu machen scheint stabil zu laufen. 👍
