### ISSUE TITLE
[Feature] Improve User Security, block Special File Extension perDefault

### ISSUE THREAD

**Issue by tox2** [n0ix/SFDL.NET#150]
Auf diversen Quelle wird mit der Zeit Malware verteilt damit die User vom SFDL Loader nicht damit betroffen sind. Gibt es nun folgenden Vorschlag.

Beispiel Malware liegt so auf der Quelle "photo.scr". 
Damit man das Löst konnte man jetzt die Filter Funktion vom Loader nutzten diese ist aber nicht per Default für alle aktiv. 
Deshalb würde eine Checkbox in den Settings wie folgt per Default gesetzt sein. 
"Dateiendungen, die höchstwahrscheinlich zu schädlichen Dateien gehören, blockieren"
Und dann als Popup Hover eine kleine Beschreibung oder so dazu. welche Extension geblockt werden.

Diese kann man dann auflisten oder auch nicht, jedoch ist diese mit der Zeit, anpassbar.

Momentan würde ich auf die Liste die File Extension ".scr" setzten. Und falls in Zukunft noch was dazu kommt dann mit der Nächsten Version updaten.

PS: @n0ix Hab das im Forum angesprochene Thema "Ausnahmeliste" hier kurz zusammengefasst.

**Comment by n0ix** [comment]
Finde ich eine gute Idee

**Comment by n0ix** [comment]
Sieht dann so aus:

![image](https://cloud.githubusercontent.com/assets/17708302/25563484/4f0854a0-2d9d-11e7-8d82-97c073fb1754.png)

**Comment by tox2** [comment]
Damit jetzt dann beim Release oder später mal keine Fragen aufkommen, könnte man ein Tooltip mit den Betroffenen Dateienden anzeigen lassen ? 

Aber Super Arbeit. Das sich Malware so beschießen verbreiten kann :D

**Comment by n0ix** [comment]
Klar kann man anzeigen lassen. Wäre halt hardcoded. Aber das wird sich kaum ändern daher wird sich der Aufwand das dynamisch zu machen nicht lohnen.

**Comment by tox2** [comment]
hardcoded ist ok, bislang ist es ja nur scr, denke nicht das weiter dazukommen werden.

**Comment by tox2** [comment]
Was denkst du soll man das neue Release bald mal veröffentlichen ?
Denn es sind sehr Viele Quellen schon von der Malware betroffen. 

unter anderem auch das was gerade vorhin gemeldet hast :D 

gruß tox2

**Comment by tox2** [comment]
Fixed ✅
