### ISSUE TITLE
[Feature] Help Button in Settings with ref. to Wiki 

### ISSUE THREAD

**Issue by tox2** [n0ix/SFDL.NET#151]
Seris Vorschlag wäre noch das man in den Settings ein Button hat der auf die wiki mit dem Filter Req Exp verweist bzw. auch das Instant Video besser erklärt.
Sowie eine Aufklärung warum und welche bestimmte File Ext. geblockt werden.

also auf die Seite verlinkt. -> https://github.com/n0ix/SFDL.NET/wiki/Getting-Started

**Comment by n0ix** [comment]
In Settings finde ich den Link jetzt nicht unbedingt logisch. Hier müsste man sich ggf. eine andere Lösung überlegen (ToolTip Info)

Habe jetzt in der Hilfe die Wiki verlinkt.

![image](https://cloud.githubusercontent.com/assets/17708302/25563269/98daf0ec-2d98-11e7-9a33-6dd1197539a5.png)

**Comment by tox2** [comment]
Fixed ✅
