### ISSUE TITLE
[BUG] Loading Hash LIB

### ISSUE THREAD

**Issue by tox2** [n0ix/SFDL.NET#152]
Hi n0ix, 

ist ja lange her das ich hier mal einen Bug melde und der hier ist echt cool 
(mittlerweile etwas nervig schon 😆 )

Ist mir jetzt des öfteren schon aufgefallen und da dachte ich mir ich gehe der Sache mal nach.

Meine Analyse Ergebnisse sind folgende:

- Wenn man denn Loader normal startet. Dann ladet der Loader die Hash LIB und das Prüfen geht.
- Wenn man aber denn Loader nicht gestartet hat sonder via einer SFDL Datei per Doppelklick startet. Dann ladet er die Hash LIB nicht. 
- Dachte mir gut ist das immer so? ja leider. 
- Bonus Erkenntnis wenn man die SFDL Datei ins Loader Verzeichnis verschiebt und startet, ladet er die Hash LIB auch und es klappt wie bei Punkt 1. 

Zu Punkt 1 - 3 habe ich ein GIF. -> http://xup.in/dl,18606655

@n0ix nun die Frage was passiert da und kann man das Lösen ?

**Comment by tox2** [comment]
Andere Frage warum kommt bei mir dieses Admin Run Ständig ich habe doch, eine installstate file.

hab das zb. gestern ausgeführt als Admin und für denn gestrigen tag ging es dann ohne das er die Meldung auswirft. 

Heute kommt diese wieder wie im gif zu sehen da sieht man auch das eine installstate file. da ist. 

werde dass morgen nochmal analysieren.

gruß tox2

**Comment by n0ix** [comment]
In der tat ein komischer fehler. schaue ich mir an. habe schon eine idee woran es liegen könnte,.

**Comment by n0ix** [comment]
probier es mal damit.

http://www.pastefile.com/cbmglu

**Comment by tox2** [comment]
Jap damit läuft es 1a, sehr gute Arbeit @n0ix. 
Lag es am Working Directory ?

**Comment by n0ix** [comment]
jop, kann man so sagen. Verwende jetzt nur eine andere funktion. Die "alte" gab hier wohl nicht immer das richtige zurück.

**Comment by n0ix** [comment]
Ups der Comment für den Komment war jetzt nicht ganz richtig. wurde ja nur in der RHash Lib geändert.
https://github.com/n0ix/SFDL.RHash/commit/b142cbfe2678461ee438096a887cf4909122e1bf

**Comment by tox2** [comment]
✅ Fixed in upcoming Version 3.0.1.2  https://github.com/n0ix/SFDL.NET/releases/tag/NIGHTLY_04062017
