### ISSUE TITLE
SFDL öffnen, hängt denn Loader auf [rbx]

### ISSUE THREAD

**Issue by tox2** [n0ix/SFDL.NET#153]
Eine Bug Meldung von rbx,
nach dem öffnen der Datei hängt der Loader sich auf.

Liegt wohl daran das es 4682 files sind.

SFDL: http://xup.in/dl,97521541

**Comment by n0ix** [comment]
hm mal schauen was man machen kann

**Comment by n0ix** [comment]
Scheint eine Limitation von der Kombination WPF + OberservableCollection zu sein. Da werde ich nicht viel machen können - sorry

**Comment by n0ix** [comment]
Scheint irgendwas auch mit MahApps zu tun haben. Muss hier wohl einen größeren Test aufsetzten :-(

**Comment by tox2** [comment]
✅ Fixed in upcoming Version 3.0.1.2  https://github.com/n0ix/SFDL.NET/releases/tag/NIGHTLY_04062017
