### ISSUE TITLE
Bulkfolder mit "_" im Namen können nicht geöffnet werden ? 

### ISSUE THREAD

**Issue by tox2** [n0ix/SFDL.NET#154]
Siehe log.log File -> https://linka.link/?http://www.xup.in/dl,17532328/log.log/
und auch im Forum

**Comment by n0ix** [comment]
Hallo,

hat mit den _ nicht zu tun. Der Server hat bei dem normalen LIST Command nur einfach 0 Items zurückgeben. Mit dem MLSD Command ging es allerderings. Habe daher die Bulk File Listing funktion etwas verbessert. Damit lässt sich dann auch diese SFDL öffnen.

**Comment by tox2** [comment]
✅ Fixed in upcoming 3.0.1.2 Version https://github.com/n0ix/SFDL.NET/releases/tag/NIGHTLY_04062017
