### ISSUE TITLE
[Feature] Automatically decrypt Container

### ISSUE THREAD

**Issue by n0ix** [n0ix/SFDL.NET#155]

**Comment by n0ix** [comment]
Feature implemented

**Comment by tox2** [comment]
Ehm ich weiß nicht warum das log File sagt auch nichts aus aber ich kann bei mir keine Settings via ok speichern da kommt ein Fehler Popup 

habe auch denn %appdata%/Folder gelöscht und neu als Admin gestartet. 
Betrifft nur das Build von 2406. 

![image](https://user-images.githubusercontent.com/23582323/27509815-3f6cf1e8-5905-11e7-850d-90a3bee241f3.png)

**Comment by n0ix** [comment]
hups..
