### ISSUE TITLE
Speed Report - Variable ie. "Total Download Size" " Download Time"no/or random output

### ISSUE THREAD

**Issue by tox2** [n0ix/SFDL.NET#17]
Variables include sometimes other random Variables ...

**Comment by n0ix** [comment]
Kannst mir etwas genauer erklären was du meinst? Versteh nicht so recht was du meinst....

**Comment by tox2** [comment]
Versuch einen Speedreport zu erstellen welcher alle Variablen benutzt

- Benutzername, Verbindung, Kommentar, Download Geschwindigkeit, SFDL Informationen (Beschreibung, **Upper**, **gesamtdownloadgröße**) , **Benötigte Downloadzeit** 

Wenn ich jetzt nach der Reihe alle andrücke erscheinen fast alle unten, außer **Benötigte Downloadzeit**  , **Upper** und **gesamtdownloadgröße**. Bei gesamtdownloadgröße kommt immer " %%TIME%%" .

Zudem kann man hier die Sachen alle eintragen lassen dann in der Box denn gesamten Text löschen und wenn man die Leere box nicht speichert mit dem Button darunter wird mit der nächsten eingefügten Variable der zuvor gelöschte text wieder eingefügt. Obwohl ja eine leere Box da war.
