### ISSUE TITLE
Automatic unrar, delete Files after unrar does not work

### ISSUE THREAD

**Issue by tox2** [n0ix/SFDL.NET#18]

**Comment by n0ix** [comment]
Hm, kann den Fehler leider nicht so recht nachvollziehen. Bei mir klappt das löschen.
Wüsste auch nicht was das löschen verhindern sollte. da ich ja warte bis die UnRAR.exe fertig ist.

**Comment by tox2** [comment]
Teste ich dann mal in einer späteren Version nochmal, also bei mir ging es bei 3 verschiedenen SFDLs nicht.
