### ISSUE TITLE
Task Bar: shows inaccurate Total Download Speed compared to Windows Taskmanager 

### ISSUE THREAD

**Issue by tox2** [n0ix/SFDL.NET#24]

**Comment by n0ix** [comment]
Ich habe versucht das ganze etwas zu optimieren sodass der Status nicht allzu hinter her hängt. Wenn ich es Realtime mache geht das mir zu stark auf die CPU

**Comment by tox2** [comment]
Verstehe liegt also an der Refresh Rate, alles klar. Denke wenn die Anzeige des Speeds nicht so laggy ist dann vertraut man der auch :D

**Comment by n0ix** [comment]
Ich lass den mal offen. In der TP 2 schaust dann einfach nochmal ob es ok/besser ist
