### ISSUE TITLE
Speedlimit: Text area has no reset or clear button

### ISSUE THREAD

**Issue by tox2** [n0ix/SFDL.NET#27]

**Comment by n0ix** [comment]
Ist so dass wenn man nichts eingibt das Speed limit aufgehoben wird. Wieso braucht man da noch einen "Clear" Button?

**Comment by tox2** [comment]
Aso das wusste ich nicht, ja dann braucht man keinen ist ja unnötiger coding Aufwand.

**Comment by n0ix** [comment]
Jo, aber wenn das dem user nachher nicht klar ist bringt das auch nix. Ich denke ich werde da etwas mehr "feedback" einbauen müssen

**Comment by tox2** [comment]
Hab hier vielleicht was gefunden, wenn man die zeile im MainWindow.xaml einbaut kommt der ClearTextButton
aber wenn man ihn drückt setzt der das Ganze auf 0, ich dachte ersetzt wieder das Watermark ein.

```
TextBox Width="120"
                             Controls:TextBoxHelper.UseFloatingWatermark="False"
                             Controls:TextBoxHelper.Watermark="Max KB/s"
                             Controls:TextBoxHelper.ClearTextButton="True"

                             Text="{Binding MaxDownloadSpeed,
                                                     UpdateSourceTrigger=PropertyChanged}" 
```

**Comment by n0ix** [comment]
Das mit TextClear Button ist eine gute idee. Habe ich so eingebaut.
