### ISSUE TITLE
Complete English Translation / Uniform Task & Status Messages

### ISSUE THREAD

**Issue by n0ix** [n0ix/SFDL.NET#3]

**Comment by tox2** [comment]
Ich poste einfach mal hier die Meldungen welche bei mir in englischer Form auftreten.
Werde das ganze einfach von zeit zu Zeit ergänzen.

TASKs Meldung. oder besser gesagt Aufgaben Meldungen: 
(Ereignisse: Download-Aufgaben bzw. SFDL- Loader Aufgaben )

- Meldung: We need a password to extract but i am not allowed to do any password test or there no passwords in the list

- Meldung:  No valid UnrRAR Password found!

- Einstellungen: Unrar Einstellungen - Automatisches Entpacken...

- InstantVideo: Ich wurde zum Teil von ein Paar User gefragt was das ist :D 
Vielleicht hilft ja eine Deutsche Funktions Beschreibung wie zb. Sofort Abspielen oder so ...

-------

PS: Wie du es schon von mir kennst, ich zähle hier einfach nur die Sachen auf welche ich verdächtig finde bzw. welche so nicht erwünscht sind.
Wie immer können Sachen falls ich falsch liege einfach ignoriert werden.
