### ISSUE TITLE
Feature Request to close SFDL Package via context menu 

### ISSUE THREAD

**Issue by tox2** [n0ix/SFDL.NET#35]

**Comment by n0ix** [comment]
Hm lustig. Habe mir einen abgef****t um so ein schönes X bei jeden Paket hinzumachen damit man eben nicht mehr über rechtsklick das schließen muss (hat wohl recht viele verwirrt/gestört) und kommst du....

Naja machen wir eben beides....

**Comment by tox2** [comment]
Aso sry bins mittlerweile gewöhnt via Rechtsklick :D

ich will hier kein Wunsch Konzert starten aber vergleiche nur Funktionen von v2 mit v3 :)
