### ISSUE TITLE
TaskBar, leaves a emtpy area below when minimized

### ISSUE THREAD

**Issue by tox2** [n0ix/SFDL.NET#38]
Pic shows more,
![image](https://cloud.githubusercontent.com/assets/23582323/20465874/f7394918-af67-11e6-8682-a464c3a8c20c.png)

**Comment by n0ix** [comment]
Problem ist hier der Expander. Das mit dem Dynamisch anpassen klappt nicht so recht. Überlege aus dem Expander eine GroupBox zu machen. Wäre evtl. eh Sinnvoller....

**Comment by n0ix** [comment]
Switched to GroupBOx
