### ISSUE TITLE
Speed Report Time writes Programm execution time in report instead of Download time

### ISSUE THREAD

**Issue by tox2** [n0ix/SFDL.NET#41]
Also result into a miss Calculation of Avg Speed in Speed report

**Comment by n0ix** [comment]
Sorry den issue versteh ich leider nicht so recht. Abgesehen das der Codeteil mehr oder weniger 1zu1 vom v2 Loader (und da war es ja richtig oder?) ist kann ich das sonst auch nicht nachvollziehen.

Denn an der Code Zeile sieht man ja recht klar was berechnet wird.

` _rt_speedreport = _rt_speedreport.Replace("%%DLTIME%%", SecToHMS(DateDiff(DateInterval.Second, session.DownloadStartedTime, session.DownloadStoppedTime)))`

**Comment by tox2** [comment]
Ok ich mach dann mal ein video dazu, aber test case war wie folgt. 

- Speedreport erstellen aktiv einstellen.
- Loader schließen
- Loader starten
- Ca. 2 min oder je nach dem wie lange man warten will, warten
- dann Download kurz starten reicht eine Sekunde oder auch 10s
- Resultat nach Download stopp steht, im Speedreport.txt eine zeit in dem Fall von 2MIn + sek....
  Die DatenMenge die geladen wurde stimmt, aber da jetzt die Zeit viel größer ist als tatsächlich wird 
  AVG. speed auch Falsch ausgerechnet.

**Comment by tox2** [comment]
Ok ich denke das Video zeigt denn BUG ganz gut, Test Schema wie oben beschrieben nur nicht bei erstem versuch des Ladens sondern beim 2ten (plus alle weiteren Downloadversuche). ein Neu Lade einer SFDL scheint den Timer im Background zu stoppen.

Hier der Link: http://www.xup.in/dl,19509574/Time_bug.7z/

Die Video-Zeit trifft so ziemlich genau die Zeit im Speedreport da der 1. Download versuch erst 30s 
verzögert gestartet wurde.

Sobald man eine Art Session einbaut wo man SFDL nicht mehr neu öffnen muss, kann man ja die aktive Downloadzeit mit speichern und wenn er dann fertig/komplett fertig mit dem SFDL laden. dann spuckt er auch einen richtig Speedreport aus denke ich.

Download time versuch 1 + versuch 2 +versuch n bis Download Komplett summiere  alle Download times. und parallel kann man das auch für File Size machen aber die kann man auch einfach auslesen vom Filesystem :D

**Comment by tox2** [comment]
Ach ja, ich kann das auch in v2 testen, aber wenn es der Selbe Code ist, ist der BUG wohl dort auch drin nur hat nie wer so genau einen speedreport angeschaut :D

**Comment by n0ix** [comment]
Danke für die umfangreiche darlegung des Problems. Dadurch habe ich den fehler innerhalb von paar Minuten gefunden :-) -> Danke!

Problem ist aber deutlich simpler als von dir vermutet. Bei starten des Download wurden einfach die Felder DownloadStartedTime und DownloadStoppedTime nicht geleert/zurückgesetzt. Ich denke das dürfte das problem beheben.
