### ISSUE TITLE
Download Stopped Message in Taskbar shows only date not time when stopped 

### ISSUE THREAD

**Issue by tox2** [n0ix/SFDL.NET#43]

**Comment by n0ix** [comment]
Ok war eigentlich so beabsichtig, aber da es du bist habe ich es geändert ;-)

**Comment by tox2** [comment]
Aso ja ne dachte nur das Datum hat ja keine Ausagekraft wenn ich dann in History gucke und nur das Datum ohne Uhrzeit sehe. :D
