### ISSUE TITLE
Unrar after download works only for rar files and not for single zip Files?

### ISSUE THREAD

**Issue by tox2** [n0ix/SFDL.NET#46]

**Comment by n0ix** [comment]
Ja das stimmt wohl. Zip Files hatte bis jetzt noch gar nicht auf dem Schirm.

**Comment by tox2** [comment]
Bin mir nicht sicher, ob das commit hier den Zip extract support bietet aber in TP4 will sowas wie im Bild noch nicht Auto entpacken.

![image](https://cloud.githubusercontent.com/assets/23582323/20650468/5f72c48e-b4cf-11e6-9cb3-ccb72c7060ee.png)

**Comment by n0ix** [comment]
Nein Zip-Support habe ich noch nicht eingebaut

**Comment by tox2** [comment]
Denke hier um den Support für Zip Files zu haben, muss man was anderes als UNRAR.exe nehmen. Denn diese funktioniert irgendwie nur für Rar Files. 

TestCase
-  unrar.exe l "my.zip" für list bzw für unrar.exe x "my.zip" 
-  Result: "my.zip" is not RAR archive

**Comment by n0ix** [comment]
Wie beschlossen lassen wir 7Zip und ZIP Support weg,. Mache daher hier zu.
