### ISSUE TITLE
Download Threads: i can run 10 threads in settings, SFDL limit does to 5, but i am loading 7 simultaneous

### ISSUE THREAD

**Issue by tox2** [n0ix/SFDL.NET#47]
Download Threads: i can run 10 threads in settings, SFDL limit is set to 5, but i am loading 7 simultaneous

After stopping download, 5 are "stopped" in status and 2 are marked "Download running", in real nothing is loading in background.

Also download can not be restarted, with the button.
See pic for details,
![image](https://cloud.githubusercontent.com/assets/23582323/20466239/ac72ec38-af6f-11e6-94dd-1142efb28d9a.png)

**Comment by n0ix** [comment]
Also entweder habe ich das "ausversehen" schon gefixxt oder ich bin zu blöd das nachzustellen

**Comment by tox2** [comment]
Testcase war:

-  In settings auf 10 stellen und SFDL manuell von 3 auf 5 stellen
- SFDL laden 
- Download  starten.
- kurz warten dann wieder Download stopp

**Comment by tox2** [comment]
Hier hab ich denn Bug rekonstruieren Können, als ich es das letzte mal testete trat er beim ersten mal auf hier erst beim 2ten. 
es gibt ein kurzes und langes Video im Archiv, da das lange 160MB hat kann ich es nicht auf xup.in stellen habe beide deshalb gezippt.

Hier der Link : http://www.xup.in/dl,14561764/10Threads.7z/

Das Komische am BUG ist ich habe gleich im Anschluss das ganze nochmal rekonstruieren wollen das ich das Video kürze aber dann trat er nicht mehr auf. Vielleicht siehst du etwas im Video. 
Ich vermute es liegt an so einem Worst case Timing szenario. damit es dann so autritt.
Aber selten ist er anscheind deshalb nicht hab jetzt 2 von 3 mal denn gesehen.

Sry zu viel Text ...

**Comment by n0ix** [comment]
Hatte hier glaub einen logik Fehler. Denke das habe ich mit Commit 58874d5 gefixxt. Viell. klappt es dann mit TP4 dann...

**Comment by tox2** [comment]
Sieht gut aus habe in TP4 bislang den Fehler nicht nachbilden können. würde das hier auch Closed/Solved markieren.

**Comment by n0ix** [comment]
Danke für die Rückmeldung
