### ISSUE TITLE
Auto Unrar does not delete files after extraction

### ISSUE THREAD

**Issue by tox2** [n0ix/SFDL.NET#49]
Video 2 ist ein wenig länger bringt aber sicher licht ins dunkle, vielleicht ist es ein Folge BUG weil bei mir im alle unrar als Fehlerhaft ausgegeben werden in der Task Message.

http://www.xup.in/dl,93554581/local_(01).mp4/

**Comment by n0ix** [comment]
Ich komme dem Fehler leider nicht auf die Schliche. Habe daher jetzt Log funktioniert vervollständigt.
Log kann man wie folgt erzeugen:

`SFDL.NET 3.exe /log`

Im Verzeichnis findet man dann eine `log.log`

Wenn TP3 dann fertig ist müsste ich bitten das so nochmal zu testen und das log hier hochzuladen. Vielleicht kommen wir dann weiter.

**Comment by tox2** [comment]
Ok alles Klar

**Comment by n0ix** [comment]
so habe es evtl. mit Commit 7f8c8b0 gefixxt

**Comment by tox2** [comment]
dass muss wohl bei mir daran liegen das ich immer die meldung entpacken fehlgeschlagen bekomme 
hab hier das ganze mit log nochmal getestet -> #62

**Comment by n0ix** [comment]
Link to Log: http://www.xup.in/dl,12619002/log_extract_error.log/

**Comment by n0ix** [comment]
Habe in 0f2cc84 noch paar sachen bzgl. UnRAR gefixxt. Hoffe jetzt tut alles.

**Comment by tox2** [comment]
Also bei mir werden die Rar Files jetzt auch gelöscht, :D Somit BUG Close

An der stelle kenne ich von anderen Loadern das es die Option gibt generell Downloads nach dem erfolgreichen laden und entpacken auch aus der Download Liste zu streichen. Könnte man hier auch einbringen würde ich sogar nutzen wo jetzt das Autounrar + delete funzt :D
