### ISSUE TITLE
Kann es sein das Drag&Drop nur bei mir nicht geht ?

### ISSUE THREAD

**Issue by tox2** [n0ix/SFDL.NET#52]
Also irgendwie war das ja schon in TP1, habs aber in TP2 noch nie genutzt außer jetzt und es will nicht.
Hier auch ein video dazu, http://www.xup.in/dl,11474691/local_.mp4/

**Comment by n0ix** [comment]
Danke für das Video. Tut bei mir aber einwandfrei. Startest du den Loader im einem anderen Context (z.B als Admin)? Dann geht das nämlich nicht. Wäre auch spontan das einzige was mir einfällt wieso das  nicht gehen sollte

**Comment by tox2** [comment]
Ne eigentlich nicht, bei mir ist es ziemlich egal wie ich es starte es geht nie, bin auf win10.

**Comment by tox2** [comment]
Darkside hat es auch bei ihm geht Drag'n'Drop auch nicht. siehe Forum.

**Comment by n0ix** [comment]
Ha Bug gefunden. Wenn im Pfad ein Leerzeichen war ging es nicht.
