### ISSUE TITLE
Theme Vorschlag: MLC stlye Black Orange

### ISSUE THREAD

**Issue by tox2** [n0ix/SFDL.NET#57]
Hi N0ix,

habe mir gedacht um dir ein wenig Arbeit zu ersparen mache ich mal so ein MLC Style für v3, Black Orange

Ich mache es in dem Sinne das man das ganze dynamisch anpassen kann je nach dem, welche hier gewählt sind:

` <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Accents/Orange.xaml" />
<ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Accents/BaseDark.xaml" />`

Sind hier `{DynamicResource AccentColorBrush}` in der Variable oder was das auch immer ist. Vordergrund und Hintergrund Farbe abgelegt.

Das soll denn zweck dienen das man entweder mehrer Themes in den Settings hat oder wählen kann,
ohne den XAML Code ändern zu müssen.

Hab es auch geschafft Vektorgrafiken einzubinden um diese auch Orange oder Blau oder welche Farbe auch immer diese dynamisch angepasst werden.

Siehe am besten das Bild hier und soll ich an dem weiter basteln und weiter denn Code dynamisch umstellen. Oder ist das eher unerwünscht für v3?

![mlc_style_window](https://cloud.githubusercontent.com/assets/23582323/20561690/1599433a-b180-11e6-9727-88944f57afb0.PNG)

**Comment by n0ix** [comment]
Weiß ich dass das geht war auch der Plan einzubauen. Allerdings so dass man die Farbe in den Einstellungen ändern kann.

**Comment by tox2** [comment]
ja ich wollte sozusagen da ein wenig mitwirken und die etwas arbeit abnehmen. :D

**Comment by n0ix** [comment]
Interresant wäre es wie man das hinbekommt das Icons auch passen. Weil wenn ich jetzt auf den DarkTheme wechsle sieht man die Icons nicht mehr :-/

**Comment by tox2** [comment]
Ja dazu hab ich in ein eigenes Xaml eine Vector Grafik eingebaut diese kann man wie folgt einbinden und die dann die Farbe setzten. ist jetzt nicht ganz Sauber und geht sicher etwas schöner aber das war nur das es mal funktioniert.

File "SFDL\Resource\icons.xaml"hab ich das vorhandene von MahApps genommen die bieten auch viele Vektor Grafiken an, und in diesem das hier eingefügt zb.
**http://pastebin.com/Fbs3U7S2**

und im _MainWindow.xaml_ bei : 
`  <MenuItem Header="{x:Static p:Strings.MainMenu_File}">
                        <MenuItem.Icon>`

Statt

` <Image Width="32"
                                       Height="32"
                                       Source="Resources/Icons/appbar.folder.open.png" />`

das hier: 
` <Rectangle Width="15" Height="15" Fill="{DynamicResource AccentColorBrush}">
                                <Rectangle.OpacityMask>
                                    <VisualBrush Visual="{StaticResource appbar_sfdl}" />
                                </Rectangle.OpacityMask>
                            </Rectangle>`

hier auch nochmal etwas schöner Formatiert.
**http://pastebin.com/gsk24NLm**


Die Vector Grafiken stammen von MetroStudio das ist ne Bibliothek mit 7000 icons, und man diese als XML bzw VektorGrafik und SVG und PNG exportieren.

Hier der Link zu MetroStudio:  man muss sich leider Registrieren, und sonst halt die Vorlagen von Mahapps in _Icons.xaml_ nutzen  da mit sollten die Icon in angepasster Farbe je nach Theme auch raus kommen 
**https://www.syncfusion.com/downloads/metrostudio**

**Comment by tox2** [comment]
Also hier würde ich dir anbieten diese Arbeit zu übernehmen und dir dann das **mainWindow.xaml** zu schicken, da ich mich ich in VB nicht so auskenne. :D

**Comment by n0ix** [comment]
Super, vielen dank tox. funktionier super :-)

**Comment by n0ix** [comment]
Siehe 49609cb

**Comment by tox2** [comment]
Das Einzige was ich nicht hinbekommen hab ist das Icon in der Titelleiste umzufärben, bzw mit der DarkBase Accent zu setzten anstatt mit der Orange Accent. :D

Hast du dieses Icon eigentlich auch dynamisch eingefärbt ?

**Comment by n0ix** [comment]
Hab ich noch nicht versucht

**Comment by tox2** [comment]
Alter Schwede ich finde den SFDL Loader v3 mit den Themes in TP4 einfach nur genial.
Gefällt mir Mega. 

Hab auch gestern noch vor TP4 mit Darkside ein wenig über das Desgin von mir im ersten Bild geredet. Er meinte wenn man das so wie in TP4 einstellen kann ist das super vor allem der Glow Effekt vom Fenster gefallt ihm und auch mir. Er meinte das solltest du unbedingt rein geben denn das Gibt dem Loader einen eigenen Touch. :D 

Ich habs so eingebaut in mainwindow.xaml
bei
`Controls:MetroWindow x:Class="MainWindow"`
wo auch das TitelIcon drinnen ist
das dazu gehängt. :D 
````
GlowBrush="{DynamicResource AccentColorBrush2}"
BorderThickness="2"
````

**Comment by tox2** [comment]
Abgesehen vom Fenster Rahmen, dachte ich teile dir noch andere Kleinigkeiten bzgl Design mit, welche in TP 4 nicht so schön aussehen. Bitte jetzt nicht als Änderungs - Aufforderung verstehen. Ist nur meine Meinung/Vorschlag. 

Im folgenden Bild habe ich ein paar Visual Glitches drinnen und ein paar Sachen die ich mir denke das sie halt anderes besser auf das Gesamt-Design wirken wenn man hier die Accent Farbe ändert.

![image](https://cloud.githubusercontent.com/assets/23582323/20649850/ac5bce0a-b4c8-11e6-8d7d-74d11f828467.png)

**Comment by n0ix** [comment]
Hallo tox,

die Vorschläge schaue ich mir an. Was ich aufjedenfall ändern möchte sind die "Icons" von den Statusmeldungen.

Den Glow an den Rändern hatte ich mal kurz drin, hat mir persönlich aber nciht so gefallen deswegen habe ich es auf Schwarz gelassen. Das war mir dann zuviel des guten ^^

**Comment by tox2** [comment]
:) verstehe vielleicht kann man ja den User in denn Settings entscheiden lassen :D 
als Kompromiss für mich und Darkside 

Zudem an der Stelle Danke für die Mühe die du dir hier machst, ich meine ein v3 zu machen und hier auf User Feedback einzugehen 👍
