### ISSUE TITLE
Encrypted SFDL v9 bug: hängt denn Download Stop Process

### ISSUE THREAD

**Issue by tox2** [n0ix/SFDL.NET#58]
Vorraussetzung wie im Bild:
![image](https://cloud.githubusercontent.com/assets/23582323/20581850/df924a78-b1db-11e6-93f0-09a9d4b19b9a.png)

Nach Download Start/Stop:
![image](https://cloud.githubusercontent.com/assets/23582323/20581900/61c0ea86-b1dc-11e6-8441-2126bf4d4b84.png)

Speedreport - Output:
THX! Speedy Follows, ,by holle : in  00:00:09  at  0 KB/s loaded   0 MB .
tox2  has a  6 MBit connection  

PackageName fehlt bzw ist ja nicht vorhanden in der SFDL.
0 KB/s loaded   0 MB, wird wohl am hänger liegen Keine Ahnung.

**Comment by n0ix** [comment]
Komischer Bug. Stellt sich aber mir auch spontan die Frage ob die Option "Unterordner pro Package" in der Form überhaupt sinn macht. Wenn dann würde ja nur sinn machen: ContainerName\Package01.

Weitergehend ist evtl. besser die Einstellung so zu ändern sodass immer ein Unterordner pro Container erstellt wird und man in den EInstellungen dann noch aktivieren kann das man ein zusätzlich Unterordner pro Packet möchte oder?

**Comment by tox2** [comment]
Hm wie war es in v2 ...

![image](https://cloud.githubusercontent.com/assets/23582323/20607372/e9e9d5bc-b277-11e6-85fc-a6ab39b4d26f.png)

So weit ich weiß kann man in einer SFDL ja mehrere Pakete haben zb. eine SerienStaffel SFDL und jedes Paket darin ist dann eine Folge. wenn man dann 2 solche SerienStaffel SFDLs hat könnte so eine Untergliederung mit pro Download/SFDL File, dann ja nützlich sein.

Die Auswahl wie in v2 mit SFDL Dateiname oder Beschreibung, ist die Beschreibung umsonst, denn die  meistens sind ja Leer oder ?

Also ich habe in v2 immer das mit pro Paket genutzt, weil mir damals so ein Multi Paket unterkam. 

Bin mir nicht sicher, aber ich denke im v2 ist der Paket Name gleichgesetzt mit Dateiname. 
Also ich denke in v2 ist es egal ob man pro Download oder pro Paket einstellt, für ein Paket im SFDL ist das resultat das gleiche, nur dann nicht wenn mehrere Pakete in einem SFDL drinnen sind. Dann wird der pro Download alles in einen Ordner. ...
Wäre zum Testen :D

**Comment by n0ix** [comment]
Also ich habe es nun wie folgt abgeändert (macht für mich so am meisten Sinn):

- Es wird **immer** ein Unterordner pro Container erstellt (z.B Film.German-LOL)
- Man kann optional in den Einstellungen anwählen das ein Unterordner pro Packet erstellt werden soll.
  Das hätte dann z.B zur folge das der Pfad wie folgt lautet: D:\DL\Film.German-LOL\Package01\

**Comment by tox2** [comment]
wird dann Package01 immer geschrieben oder nur wenn der Package Name im SFDL leer ist ?

**Comment by n0ix** [comment]
PackageXX wird dann gesetzt wenn der packetname leer ist
