### ISSUE TITLE
Application crashing on Exit

### ISSUE THREAD

**Issue by n0ix** [n0ix/SFDL.NET#6]
Application is Crashing on Exit

![unbenannt](https://cloud.githubusercontent.com/assets/17708302/20445254/9f93617e-add4-11e6-84d3-0821e52bc7c3.PNG)

**Comment by tox2** [comment]
Ne denn hatte ich in keiner der TP 1 -4 nicht. Also beim schließen nicht .... 

Nur einmal jetzt kurz beim Öffnen des Loader, aber denke das war grad einmalig.

**Comment by n0ix** [comment]
Liegt wohl an meinem PC /OS. Woanders tritt das Problem bei mir auch nicht auf.
