### ISSUE TITLE
TP3 same BUG Succsessfull unrar report message "extraction failed"

### ISSUE THREAD

**Issue by tox2** [n0ix/SFDL.NET#62]
hier der log dazu. http://www.xup.in/dl,12619002/log_extract_error.log/

ich vermute deshalb werden bei mir nie die Archive gelöscht, sollen ja auch nicht wenn das Entpacken fehl schlägt .. :D

**Comment by n0ix** [comment]
Ich mach das hier zu. Führe das Problem weiter in #49
