### ISSUE TITLE
Loader hang: Doch kein Vanish bug Zusammenhang, der kommt auch nach 1mal start/stop

### ISSUE THREAD

**Issue by tox2** [n0ix/SFDL.NET#63]
hier der log dazu: 
http://www.xup.in/dl,17579139/log_random_hang_after_1_startstop.log/
http://www.xup.in/dl,13544840/log_hang_again_after_startstop.log/

keine ahnung warum, hate sowas in TP 2 Noch nicht

EDIT:
hab noch 2 Logs. welche den selben Bug drinnen haben. 
Log 1 lässt denn Download nicht mehr starten bzw der Button kann drücken nur passiert nix
Log 2 während des Downloads nach einem 2 start, kommt plötzlich und keine Task Meldung Download running ... eta usw. und nach Download Stop und einer kurzen Wartezeit hängt der Loader.
Log1: http://www.xup.in/dl,47866793/log_freeze.log/
Log2: http://www.xup.in/dl,90694492/log_hang_and_no_download_running_task.log/

**Comment by n0ix** [comment]
Ist dann doch der selbe Fehler wie #60 oder?

**Comment by tox2** [comment]
kann sein bin mir nicht sicher denn alle anderen TaskBar infos verschwinden nur "Download läuft..." verschwindet nicht nach x Sekunden.
