### ISSUE TITLE
Multiselect Files select with Shift and arrow/ STRG mouse in List like in v2

### ISSUE THREAD

**Issue by tox2** [n0ix/SFDL.NET#66]

**Comment by n0ix** [comment]
Muss ich mir nochmal genauer anschauen wie das in WPF geht. Auf anhieb habe ich das gestern nicht hinbekommen. Denn eigentlich wollte ich es so machen wie in v2.

**Comment by n0ix** [comment]
Fixed, allerdings hab ich es nicht hinbekommen die dann mit der Leertaste zu makieren. Geht dann nur mit Enter
