### ISSUE TITLE
Settings Window: ist zu hoch für meinen Bildschirm :) | Is the Save button obsolet ?

### ISSUE THREAD

**Issue by tox2** [n0ix/SFDL.NET#68]
Hab hier eben 1366x768, kann man hier einen eigenen Reiter für Themes machen, oder sonst denn Speichern Button rausnehmen, denn mir ist aufgefallen wenn man das Settings Window schließt wird so oder so gespeichert egal, ob man den Button drückt oder nicht. 

![image](https://cloud.githubusercontent.com/assets/23582323/20649900/1d918672-b4ca-11e6-8c51-49d266091ebc.png)

**Comment by n0ix** [comment]
Habe ich befürchtet das dass zu lange wird. Muss ich dann wohl etwas umstellen

**Comment by tox2** [comment]
Verstehe kommt der Button zum speichern raus, denn Fenster schließen hat ja die selbe Funktion ? :D

**Comment by tox2** [comment]
Ach stimmt leider nicht ganz mit Close button Gleich save button. Die Theme Settings werden zwar sofort übernommen, aber bei nur schließen der Settings werden diese nicht mit gespeichert.

ist mir grad eben aufgefallen man muss damit diese auch nach eines Loader restarts bleiben, erst auf speichern drücken, bei mir halt immer unten nur sehr knapp zu erreichen :D

**Comment by n0ix** [comment]
Sieht jetzt so aus:

![unbenannt](https://cloud.githubusercontent.com/assets/17708302/20650746/51a56512-b4d6-11e6-8c02-c3d473010b6c.PNG)

**Comment by tox2** [comment]
Super 👍  hier noch kleine Frage Warum ist Deutsch / Englisch nicht Links unter Click'n'Load ?

Und ich schätzte mal "nach Updates suchen" und "Click'n'Load" haben noch nicht die geplannte Funktion, Hab diese jedes mal beim Testen ignoriert. 

Frage nur weil ich jetzt alles erdenkliche probiert habe und der Loader bis auf die schon eingetragenen Sachen super läuft. Ab jetzt mein Default Loader :D

**Comment by n0ix** [comment]
Hast du recht macht unter Click'n' Load mehr sinn. Und ja Click'nLoad und Updates suchen tut noch nicht. Ich mach mir dazu mal ne issuse sonst vergesse ich das wieder ^^
