### ISSUE TITLE
Download SubFolder Setting wird ignoriert wenn das SFDL bereits geöffnet ist

### ISSUE THREAD

**Issue by tox2** [n0ix/SFDL.NET#69]
Download SubFolder Setting wird ignoriert wenn das SFDL bereits geöffnet ist. 
Der Downloadpfad ist jener der beim SFDL öffnen in denn Einstellungen drinnen stand.
Nach öffnen der SFDL kann man denn SubFolder Download  nicht mehr umstellen und muss neu öffnen.

Anmerkung die Fehler die ich finde werden immer Kleiner und Kleiner :) die Beta naht :D

**Comment by tox2** [comment]
ich schreibs einfach hier nochmal rein will kein neues Issue Ding aufmachen.
Das Video wie in der PN zu #69, -> http://www.xup.in/dl,20321168/local_(01).mp4/

Also bei mir wie im Video zusehen wird es noch immer ignoriert, außer man öffnet die SFDL neu dann wird auch das Download Dir neugesetzt.

**Comment by n0ix** [comment]
Danke für das Video - habe nun verstanden was du meist - habe dann damals  einen anderen Bug gefixxt :-D
