### ISSUE TITLE
Session Storage, bug ! Confirmed

### ISSUE THREAD

**Issue by tox2** [n0ix/SFDL.NET#70]
wenn du eine SFDL geladen hast und denn Loader neustartest, ist die SFDL dann bei dir schon im Loader drinnen, bei mir irgendwie nicht :(

**Comment by n0ix** [comment]
Existiert der Ordner `C:\Users\Tim Hofmann\AppData\Roaming\SFDL.NET 3\Sessions` ?

**Comment by tox2** [comment]
Ja ist aber leer

**Comment by n0ix** [comment]
Okay, komisch. habe das Loggin ertwas bzgl. der zwei Funktionen angepasst. Hast du den Fehler hier -->#6 ?

**Comment by n0ix** [comment]
Also ist ein Bug, Auf meinem Notebook habe ich den selben Fehler.
