### ISSUE TITLE
Download "Unbekannter Fehler" kann man hier ein Retry machen ?

### ISSUE THREAD

**Issue by tox2** [n0ix/SFDL.NET#71]
Er kommt zwar selten ist anscheinend auch Unbekannt aber meistens geht das ganze wieder wenn man denn Download manuell stoppt und startet. 
Deshalb die Frage an der stelle das man hier ein Retry macht nach 10s oder so ?
Geht das ?

**Comment by n0ix** [comment]
Retry geht generell schon. Nur unterscheitet der Loader je nach fehler ob ein Retry sinn macht oder nicht.
Kann natürlich durchaus sein das es hier zu nicht defnierten Fehler kommt (dann wird es als unbekannt makiert) die sich trotzdem durch einen Retry beheben lassen. Das müsste man sich jetzt an einem speziellen Beispiel anschauen und dann sehen ob man das beheben kann.

**Comment by n0ix** [comment]
Mache hier mal zu. Muss man dann ggf. nochmal aufmachen
