### ISSUE TITLE
OK ich hab das zwar schon mal hier gehabt aber warum springt bei mir immer das Settings Window

### ISSUE THREAD

**Issue by tox2** [n0ix/SFDL.NET#72]
Es scheint so zu sein als ob ich mehrere Instanzen des Fenster öffne und diese eine Art offset nach unten und Rechts haben, obwohl es immer nur ein Fenster ist das aufgeht. 

Kann jetzt auch ein Video machen aber denke das verhalten ist bekannt.

Also in meinem Fall drücke ich Datei -> einstellungen -> das fenster geht auf random position -> mache das Fenster wieder zu -> und gehe wieder auf Datei etc... 

Ich schiebe jedes mal das Fenster nach rechts aber beim nächsten öffnen ist es auf Default Pos + Offset...

**Comment by n0ix** [comment]
Steuern tue ich das nicht direkt. Eingestellt ist `WindowStartupLocation="CenterOwner"`
KP ob es da zu Fehlern kommt. Habe daher jetzt mal noch `SaveWindowPosition="True"` hinzugefüt. dann sollte es sich die letzte Pos merken. Ich denke das sollte damit dann gefixxt sein.
