### ISSUE TITLE
Enchanment ? Lösche denn automatisch erstellten SFDL Ordner wenn der Leer ist und das SFDL geschlossen wird

### ISSUE THREAD

**Issue by tox2** [n0ix/SFDL.NET#73]
Klassische Verbesserungs Idee kein BUG in dem Sinne.
Beim testen und auch sonst verdrücke ich mich manchmal beim öffnen der SDFLs, oft schließe ich auch direkt im anschloss das eben nicht gewünschte SFDL. aber es bleibt eben noch der Ordner auf der Platte.

Kann man hier zwecks Benutzerfreundlichkeit beim Schließen des SFDLs überprüfen, ob der SFDL Ordner leer ist um dann auch gleich diesen Automatisch löschen. Ich hab auch schon in v2 unzählige mal diesen manuell gelöscht :P

**Comment by n0ix** [comment]
Puh ok, ist schon sehr speziell den der normale User wird sowas nicht tun. Ich lass es mal als "Enhanment" kann dir aber nicht versprechen wann ich das einbaue

**Comment by tox2** [comment]
Ja der normal User ist ja in der Regel nicht so unfähig wie ich :D, bzw normalerweise nehme ich eine SFDL öffne diese und mit dem Öffnen ist diese von der Platte. Aber Ja, Danke falls es als Funktion kommt :D

**Comment by tox2** [comment]
Ok hab noch was entdeckt wenn ich die SFDL öffne somit im Loader habe und danach denn Ordner der SFDL manuell lösche, erstellt der Loader beim Start des Downloads denn Ordner.

Somit muss nur das Automatische Ordner Erstellen raus genommen werden dann man muss man auch nicht den Ordner automatisch löschen. Bzw. es Entsteht kein Zombie Ordner jedes mal wenn ein SFDL nur geöffnet wird.

**Comment by n0ix** [comment]
Hm...guter einwand....

**Comment by n0ix** [comment]
Gut - habe es umgesetzt

**Comment by tox2** [comment]
Best Coder Ever :D 👍
