### ISSUE TITLE
Updater not yet implemented / not working

### ISSUE THREAD

**Issue by n0ix** [n0ix/SFDL.NET#75]

**Comment by n0ix** [comment]
Add Basic Functionality - Needs more testing and fine Tuning for RC2

**Comment by tox2** [comment]
Wenn ich die RC1 starte, kommt keine Meldung das es eine RC2 gibt bzw. das ein Update vorhanden ist.

**Comment by n0ix** [comment]
Und jetzt?

**Comment by tox2** [comment]
Jop jetzt kommt die Meldung.
Schade das man den Link nicht direkt öffnen kann. :D 
Kann man wieder schließen.
