### ISSUE TITLE
Feature like in v2? copy Speedreport to Clipboard.  

### ISSUE THREAD

**Issue by tox2** [n0ix/SFDL.NET#77]
Im v2 kam dann immer das Fenster, mit Speedreport und einen Button zum in die Zwischenablage kopieren.

Frage kann man es irgendwie zur Meldung "Speedreport erstellt" beifügen also das dort dann so ein kleiner  Button ist zum kopieren. ? 

Hab hier nur ein Beispiel gefunden für eine Textbox mit Icon welches eine Funktion ausführt. Aber nicht für TextBlock bzw Listbox. https://cisart.wordpress.com/2013/10/09/metro-textbox-with-browse-folder-button-and-validation/

Anmerkung der Link oben kann auch für denn Download Pfad in denn Settings interessant sein.

**Comment by n0ix** [comment]
In den Einstellungen habe ich das wie vorgeschlagen angepasst. Ein extra Button für den Speedreport finde ich etwas unnötig. Des Weitern wüsste ich jetzt auch nicht wie ich das in WPF umsetze.

**Comment by tox2** [comment]
Ja stimmt da kein Speedreport Pflicht ist, wird es wohl nie wer nutzen bzw. jener braucht diese Abkürzung nicht. Man kann ja noch immer auf die Speedreport.txt zugreifen.

Aber würde das Umsetzen dann so gehen wie im Link, oder bin ich jetzt ganz falsch?
LINK: http://stackoverflow.com/questions/7127920/wpf-listview-with-buttons-on-each-line

**Comment by n0ix** [comment]
Ne das wäre wohl eine gute Lösung. Viell. bauch ich es später mal noch ein.

**Comment by tox2** [comment]
Vielleicht könnte man an dieser Stelle noch einen Verbesserungsvorschlag machen, wenn man jetzt die Task Meldungen via Rechtsklick kopieren kann. Wäre es möglich die 2te Spalte welche in der Task List ist dafür zu verwenden dort ein Copy Icon zu platzieren. 

So hatte ich das ganze eben nur für die Meldung ' Speedreport erstellt' gedacht. Das anstatt 
' Speedreport erstellt ' dann eben der Inhalt des Speedy kopiert wird.

Falls das mit dem Icon zu viel Aufwand ist, passt die Lösung via Rechtsklick eigentlich auch.
Werden aber wohl die wenigsten bemerken das das geht. (das man das eben via Rechtsklick kopieren kann)

Desweiteren würde ich die 2te Spalte in der Task List dann auch rausnehmen wenn diese keinen Nutzen hat.
