### ISSUE TITLE
SFDL crash when Download Directory does not exsist + open containing SFDL Folder

### ISSUE THREAD

**Issue by tox2** [n0ix/SFDL.NET#79]
Log vom Crash: http://pastebin.com/vGSEfkpX

**Comment by n0ix** [comment]
Kannst du mir etwas genauer erläutern wie du den Fehler produziert hast?

**Comment by tox2** [comment]
Jo ich hat eine RamDisk in "D:\"geladen um zu testen, ob der Loader "HDD Full test" macht und dann habe ich vergessen den Downloadpfad wieder zu tauschen. Ich würde mir denke das kann man auch mit einem USB stick machen, USB rein, Pfad setzten usb raus. ...

**Comment by n0ix** [comment]
Okay, also kommt der Fehler wenn das Laufwerk nicht mehr existiert. Schau ich mir mal an

**Comment by n0ix** [comment]
Hm also ich kann den Fehler nicht so recht nachstellen. Wenn ich ein Laufwerk einstelle welches nicht existiert bekomme ich nur beim starten des Downloads eine Fehlermeldung (was korrekt ist). Einen Absturz oder so konnte ich nicht provozieren.

**Comment by tox2** [comment]
Komisch bei mir ist es bei TP4, hast es auch auf dem Notebook getestet oder nur mit Debugger ?

Anmerkung es ist nicht das Problem mit dem Downloaden, da kommt die Meldung sondern nur mit der Kontext Menu funktion, Beinhalteten Ordner öffnen

**Comment by n0ix** [comment]
Ne, auch auf meinem Notebook sowie ohne Debugger lässt sich der Fehler nicht reproduzieren. Auch nicht wenn ich "Beinhalteten Ordner öffnen" klicke. Ich denke mal ich habe es bereits "unfreiweillig" durch etwas anderes gefixxt...

**Comment by tox2** [comment]
Verstehe, werde es dann nochmal in einem späteren Release bei mir testen, kann auch nur an meinem PC liegen.

**Comment by n0ix** [comment]
Hm äußerst komisch. Macht auch irgendwie gar kein sinn. Ich mach jetzt mal noch ein Try Catch Block um die funktion dann kann definitiv nix mehr passieren, auch wenn der Fehler mir nicht auftritt.
