### ISSUE TITLE
Warn before Close, while Download or Extracting SFDL Packages?

### ISSUE THREAD

**Issue by tox2** [n0ix/SFDL.NET#82]

**Comment by n0ix** [comment]
Man kann eine SFDL nicht schließen wenn diese sich im Download Status befindet. Beim entpacken dürfte das auch nciht gehen, bin aber grade nicht sicher ob das ich schon eingebaut habe...

**Comment by tox2** [comment]
Ja das SFDL Paket kann man nicht schließen/aus dem Loader entfernen, während des Downloads.
Aber es ist schon möglich den Loader zu schließen Datei->Beenden bzw. Loader Fenster schließen, während des Downloads.

Ich kenne es nur von Qt in C++, das man denn Application Exit Event abfängt und je nach Bedienung, den Loader schließen lässt. Bzw. ne Warnmeldung an den User gibt.

Ob das auch in .net geht keine Ahnung.

**Comment by n0ix** [comment]
Aso, ja stimmt das wäre ganz gut ^^

**Comment by tox2** [comment]
Wenn ein Download läuft und man im Eck auf das X drückt kommt die Meldung ob man denn Download abbrechen will und denn Loader schließen möchte. Falls Nein ladet alles sauber weiter falls ja wird geschlossen und die session gespeichert.

Wenn man den Loader aber über Datei Beenden schließt, kommt keine Meldung ob Ja oder Nein und die Session geht auch verloren.
