### ISSUE TITLE
Meldung: BulkPackage konnte nicht gelesen werden, Open Error ?

### ISSUE THREAD

**Issue by tox2** [n0ix/SFDL.NET#86]
Tritt das nur auf wenn der FTP Server Offline ist ?
Man könnte dann auch als Meldung schreiben, "Server Down" bzw.
 "Try FTP Link, either SFDL corrupt or Server is Down"schreiben... 

Das ist einfacher dem User zu mitteilen das er es als FTP Link mal testen soll, bevor er den Thread als Down im Forum melden kann.

**Comment by n0ix** [comment]
Ja dem ist so. - setzte ich so um
