### ISSUE TITLE
SFDL Files can be opened more than 1 time via Click'n'Load Function.

### ISSUE THREAD

**Issue by tox2** [n0ix/SFDL.NET#87]
![image](https://cloud.githubusercontent.com/assets/23582323/21508150/d9722876-cc7e-11e6-805e-9eb5a396ae2f.png)

Das Click'n'Load ladet anscheinend, das SFDL File vom Host und gibt einen zufälligen Namen
in dem Fall 'arnzzylz.amp' und 'tsx33lmz.4wi' 

Was zur Folge hat das man nach Download Start seltsame Fehler beim Download sieht.

**Comment by tox2** [comment]
Es gibt momentan eine heiße Diskussion im Forum ob das Forum das Click'n'Load überhaupt nutzen wird.
Seri meint es ist verwirrend für denn User und nicht sauber im Thread wenn 2 Links 
einmal        'sfdl://download.sfdl.net/*' steht
und einmal 'http://download.sfdl.net/*' steht.

Somit würde ich das ganze mal auf Eis legen mit dem Click'n'Load da es per default nicht von seri genutzt wird bzw. nicht genutzt werden will.

Nur als Info, falls das Feature nur fürs Forum existiert.

**Comment by n0ix** [comment]
Also ich bau die funktion wieder aus. ein problem weniger...
