### ISSUE TITLE
[Vorschlag] SFDL File extension icon

### ISSUE THREAD

**Issue by tox2** [n0ix/SFDL.NET#88]
Falls man das separat als File Extension Icon angeben kann.
 Collection as 7z Archiv and Preview of Icon.
http://www.xup.in/dl,11666906/SFDL_APPicons.7z/
![file-format-sfdl_orange_512px](https://cloud.githubusercontent.com/assets/23582323/21508549/2f7c6508-cc82-11e6-8117-9dbce0fee83a.png)

**Comment by n0ix** [comment]
Das Icon hab ich schon eingebaut? Oder hast du das nochmal abgeändert?

**Comment by tox2** [comment]
Hm ja das HauptIcon ist ja schon drinnen das sollte sich aber von den SFDL File unterscheiden,
Dazu müssen ledeglich in der exe 2 icons drinnen sein und wenn man die File Ext im system registriert, statt 0 index für das haupticon, 1 index nehmen dann sind es 2 unterschiedliche icons.

Bei mir sehen die Files gleich aus wie die Haupt Anwendung.

![image](https://cloud.githubusercontent.com/assets/23582323/21525325/e373efb4-cd1c-11e6-82a3-694e990a10a1.png)

**Comment by n0ix** [comment]
Ah okay - sry stand auf dem Schlauch. Ne es wird nur das Icon.ico welches im Verzeichs liegt als File Icon genutzt. Habe das nun ausgetauscht.

**Comment by tox2** [comment]
Packt er diese nicht in die 'SFDL.NET 3.exe' rein ? Ich dachte er packt diese dazu wenn es in dieser 'FileAssociation.vb' deklariert ist.
 
Momentan liegt in dieser Exe ja nur das Haupt Programm Icon. 

Aber es stört auch nicht wenn das Icon nicht gepackt ist. Wollte es nur anmerken. 

Bei 7z ist es zum Beispiel so gemacht, die 7z.exe hat das Haupticon und die 7z.dll beinhaltet alle verschiedenen FielExt Icons 

Siehe bild, 
![image](https://cloud.githubusercontent.com/assets/23582323/21527678/13135178-cd2d-11e6-8642-a93eff6607b6.png)
