### ISSUE TITLE
Toac.exe wird momentan von ein paar Virenscanner geblockt.

### ISSUE THREAD

**Issue by tox2** [n0ix/SFDL.NET#89]
Toac.exe wird momentan von ein paar Virenscanner geblockt.
Leider führt das zu einem Absturz von dem Loader und unter anderem auch zu einem Fehlverhalten.

Da es ein kompiliertes Batch File ist denke ich es liegt daran. Ich arbeite momentan sowie so an einer schöneren Version. Diese wird im momentanen Entwicklungsstadium nicht geblockt. Ich hoffe es bleibt auch so, weil es im Grunde nur 2x die 7z.exe mit anderen Parameter ausführen soll. 

Wenn die v1 fertig ist stelle ich den Source Code auch auf Git. 

PS: Bis nächste Woche sollte die v1 dann soweit sein.
Die v2 lässt sich dann denke ich ganz in den Loader implementieren, wenn v1 sauber laufen sollte. Dann kann man sich die exe ersparen und schließt somit auch das blocken von Virenscanner mehr oder weniger aus.

**Comment by tox2** [comment]
Hab ein klasse Tool gefunden, welches eigentlich durchaus bessere Optimierung liefert als das vorherige Toac.exe. 

Hab Ein kleines Vorführungs-Script in Powershell dazu hier veröffentlicht. 
https://github.com/tox2/TOAC/releases

Ich hoffe eigentlich nur das man dieses Tool welches nicht als Virus markiert wird besser nutzen kann.
Sowie das man das Ganze direkt in denn Loader einbinden kann ohne weitere Zusätzliche Binaries :D 

Für die gängigen 7Zip und RAR/RAR5 Archive funktioniert es wunderbar. 
Nur Leider nicht für Zip Archive, aber wer setzt denn dort auch schon ein Passwort :)

**Comment by n0ix** [comment]
Cool schaue ich mir mal an

**Comment by tox2** [comment]
Falls das ganze doch besser wie das alte ExitCodes liefern lassen soll kann ich wieder sowas basteln,
TOAC.exe -p PW "Archiv.ext" 

Das würde dann statt 7z.exe die 2 crark.exe Files nutzen, ich weis nur nicht ob wenn ich das wieder in eine Exe packe das ganze als Virus markiert wird und ich deshalb besser das als PS Script anbieten soll. BZW. weiß ich auch nicht ob das PS Script dann auch vom Loader genutzt werden kann.

**Comment by n0ix** [comment]
Powershell lässt sich generell einbinden, allerdings wird es vermutlich probleme geben unsignierte PS Scripts auszuführen da diese standardmäßig geblockt werden.

**Comment by tox2** [comment]
verstehe und was ist wenn du einfach selbst die Crark exe Files startest, und das ganze in net codes ? 

Also nach meiner Logik könnte es so ablaufen. Loader ladet... ist fertig. 
Dann wird halt Part 1 vom Multi-Archiv oder das Single Rar genommen und mit dem cRARk Tool kurz abgecheckt.

Die PW Liste in den Settings mit der PW Eingabe von User könnte dann die Wörterbuchdatei sein. 
'Password.def', wäre jetzt das Default Setting von cRARk der Dateiname der Wörterbuchdatei könne aber auch anders heißen. 

Also müsste man in .net das Coden, dass die cRARk.exe mit dem Archiv Pfad als Parameter startet und anschließen den Consolen-Output vom Tool weiterverarbeitet bzw. parst. Dieses Scan Resultat liefert dann die Antwort ob das PW passt oder nicht, oder ob gar keins nötig ist.

Vorteil das Ganze ist in nur paar Sekunden Fertig egal wie Groß die Archiv Files sind.
Im Vergleich zum unrar test Archiv Methode welche Minuten dauert bei größeren Files.

-------------

Angebot:
Ich könnte mich auch schnell mal in .net einlesen dann mach ich das in .net. 
In Powershell sind es 4 - 7 Zeilen die man braucht. 
Frage gleich dazu wäre eine Funktion genug, welche das PW überprüft ? Damit man dann einfacher im Loader das einbinden kann.

------------

Das mit dem ZIP und 7zip ist ja eigentlich noch unwichtig nutzt ja niemand und sonst muss man die halt mit PW manuell entpacken. 7zip.exe würde an der stelle sogar alle Formate können bezogen auf das entpacken. unrar kann ja nicht alles. 

----------

Vorschlag:
Als mein Verbesserungsvorschlag um mehr Performance im Loader zu haben bezogen auf Unrar nach dem entpacken wäre.

1. cRARk.exe mit 'Password.def' File als PW Checker nutzten 

1. 7z.exe zum Entpacken von Rar/Rar5/zip/7z Archiven auch mit PW 

Offene Fragen:
Ich weiß nur nicht wie einfach/schwer die PW aus denn Settings in das 'Password.def' File kommen
und ob man das Userinput PW auch in das 'Password.def' bekommt. Damit das cRARk damit arbeiten kann.

Punkt 2 ob man wenn ein Download fertig geladen hat egal wie viele Files schon geladen wurde immer das Start Archiv angeben kann weil cRARk nur in dessen Header die PW- Check machen kann.

Punkt 3 ob 7z.exe erwünscht ist um als Entpacker zu dienen, bzw ob entpack Support für zip 7zip erwünscht ist.

------------

Sry für denn langen text und die lange Wartezeit auf ne Antwort ich habe die Tage nicht rein geguckt. Aber bitte gibt mir bescheid bzgl. des Optimieren, würde echt gern da was machen und dir helfen oder gar auch selbst hand anlegen und das realisieren.

gruß tox2 :)

**Comment by n0ix** [comment]
Also um cRARk,exe nutzen zu können müsste man das ganze komplett in den Loader einbauen. Eine weitere exe die wiederum nur als wrapper für die cRARk.exe dient halte ich für unnötig. Macht das ganze auch unnötig kompliziert.

1.) Settings vom loader so umbauen sodass die Passwörter in die Password.def geschrieben wird ODER man schreibt die Password.def jedesmal kurz vor dem ausführen von cRARk.exe (was ich spontan für die bessere Idee halte)

2.) Das start Archiv ist nicht das Problem. Ohne das würde auch InstantVideo nicht funktionieren. Sprich der loader weiß welches das StartArchiv ist.

3.) 7z ist schön gut  - nutz aber keine sau. Bei den zwei SFDL/Realeases welche mit ZIP oder 7z gepackt sind überlege ich och ich mir den "Stress" überhaupt mache Support dafür einzubauen. Wenn dann müsste man komplett auf 7z umstellen und das Parsing bzgl. der 7z Ausgabe komplett neu schreiben.

**Comment by tox2** [comment]
Stimme dir nur zu. Einen Wrapper würde ich auch nicht empfehlen sonst kommt wieder das mit dem AnitViren Sachen. 

Nun gut wenn Punkt 1 und Punkt 2 keine Probleme sind, würde ich sagen das wir unseren neuen Archiv PW Checker gefunden haben. 

_Ich würde sogar sagen das man den SFDL Loader "Auto Unrar Feature" nur für rar Archiv Files anbietet._

Weil A 7z.exe dazuführt dass das Parsen des Forstschritts geändert werden muss.
Und B weil für 7zip bzw zip dann wieder eigene PW Checker Nötig sind. :) 
Für 7zip gibt es denn PW Checker zwar, aber Zip müsste man wiederum was neues Coden.

---------

Als kleine Info, ich habe schon ein wenig versucht das ganze in denn Loader zu bekommen, muss aber sagen sämtliche zusammenhänge habe ich aber noch nicht durchblickt. Deshalb die Frage. 

_Würdest du in RC2 dann das Ganze mit dem neuen PW Checker machen wollen /bzw. implementieren ?_

PS: Es tut mir leid dass das mit dem batch TOAC.exe nicht so geklappt hat und ich jetzt hier ein wenig Mist gebaut habe. Aber um ehrlich zu sein ich hatte das so auch nicht kommen sehen, dass nach ner Zeit die AVs darauf anschlagen. Bin mir noch immer nicht sicher warum das passiert ist.... :)

**Comment by n0ix** [comment]
Du kein Problem. Ich finde es toll das du dich hier so einbringst. 

Masterplan wäre daher wie folgt: 7z und ZIP Support schmeißen wir (zumindest mal vorerst) über Board. Ich schmeiß die TOAC.exe raus und baue die cRARk.exe ein. Die password.def wird dann immer kurz vor dem entpacken neu geschrieben. Guter Plan?

**Comment by tox2** [comment]
Ja das klingt denke ich sehr gut. 

Vielleicht noch eine Anmerkung, wegen dem 'password.def'. 
Ich denke meine TOAC.exe ist deshalb als Virus markiert, weil ich den Konsolen Output in ein Temp.txt File gepuffert habe, da das sozusagen bei jedem start der Fall ist wird die ständig erstellt und wieder gelöscht. (Natürlich kein schöner Ansatz war aber auch nur als Proof of Conzept Design gedacht).

Ich vermute jetzt mal das ein solches Verhalten, bei AV Lösungen unerwünscht ist. Deshalb würde ich die password.def nur speichern wenn die Settings geändert werden. Also nicht zu jedem PW Prüfvorgang, falls der Loader irgendwie das ganze öfter hintereinander machen will. (subs und Film Archive und so...) 

Weiters müsste die password.def aktualisiert werden, wenn der User gefragt wird welches PW das Archiv hat. Falls das zur Laufzeit des Entpack Prozesses überhaupt gefragt wird. 

---------------

Kann mir hier vorstellen das nicht Jeder normale User in denn Settings seine PW liegen hat. Und bei einem neuem SFDL unter Umständen auch ein neues PW nötig sein wird.

Würde das dann so machen:  Erster PW check die vorhanden Settings PW. checken.
Falls das Ergebnis lautet dass das Archiv geschützt ist aber kein PW richitg ist. dann würde ich den User um ein PW Fragen. (2. versuche) und wenn das auch nicht klappt dann müsste das Auto Unrar übersprungen werden.

Somit hat man zur Laufzeit max. noch 2. Schreibvorgänge. Und einen bei jedem PW edit in den Settings.

-------------

Ob man hier echt auf diese Schreibvorgänge aufpassen muss, ich hoffe nicht weil die Speedreport.txt ja auch ständig geschrieben wird. Das stört die AVs auch nicht :D

**Comment by n0ix** [comment]
Fixed with dc4b3d9 and 67cfcf8

**Comment by tox2** [comment]
Hab was seltsames gefunden mit dem entpacken mit PW.
Habe dazu das Log und das Thread/SFDL dir via PN geschickt.

Und zwar kann das richtige PW im password.def stehen der Loader aber als TASK meldung das hier ausgibt.
'No valid UnrRAR Password found!' 

Zudem sollte hier das ganze eben auch auf Deutsch stehen und nicht englisch. wenn im Loader German gewählt ist, aber ich denke das ist noch ne offene Baustelle das mit DE und EN :D 
Ist mir bei einigen Meldung schon aufgefallen welche der Loader so macht einmal DE einmal EN.
Lass ich jetzt mal nur so als Erwähnung. 

Was denn Bug aber angeht, bzw. warum die Meldung kommt 'No valid UnrRAR Password found!' 
mein PS script macht bei dem Archiv alles Richtig da kommt die Meldung ' _ _ _ Correct PW '

kann es sein das du denn Output anderes als ich parst ? 
Bei mir ist:
$line = echo $stdout  | select-string -pattern 'CRC OK' -CaseSensitive

weil 'crc ok' kommt auch in klein geschriebener Form im Output manchmal vor.

**Comment by n0ix** [comment]
Ach das wird manchmal auch klein geschrieben? Dann wird es vermutlich daran liegen. Ich probier das mal

**Comment by n0ix** [comment]
So wie es aussieht passt etwas mit dem Password def File nicht.

Ich bin aber zu doof und checke die Doku nicht.

```

##
testme
4all
lol
abc
```

So wäre das doch nicht oder?

Bekomme da nämlich immer folgenden Fehler:

```
Testing archive with encrypted headers E:\Download\Adobe.Photoshop.CC.2015.5.v17.0.0\adbphotocc15517.part1.rar: version 2.9
OpenCL device #0 GeForce GTX 970 found, 1253 MHz, 1664 SP cores, GPU rate = 9.15
Trying to compile  NVIDIA OpenCL kernel. Please wait... Successfully.
Running self-test... Successfully.
Choosing best crypto functions.......
Chosen: AVX, AVX, AVX (-f244), AES-NI
Clock cycles per password expected = 8261355(SIMD)/22000335 (x64) (*), theoretical = 21172752
Calculating pure SHA-1 clock cycles...
Pure SHA-1 clock cycles per byte expected = 1.6 (SIMD)/4.0 (x64) (*), theoretical = 4.3
Intel(R) Core(TM) i5-3570K CPU @ 3.40GHz found, CPU rate = 2.66 (*)
(*) May be inaccurate if Turbo Boost is on

Fatal syntax error in line 1
```

Verstehe nicht was der so ein Problem mit der 1. zeile hat. Laut Doku sind die 2 ## wichtig und müssen da sein.

**Comment by tox2** [comment]
Ja bei dem SFDL_password.def ist das encoding auf UTF-8 with Sig wenn ich das auf ansi ändere gehts .

**Comment by n0ix** [comment]
Was ne scheiße - da kommt ja kein Mensch drauf.....danke für die Hilfe.
