### ISSUE TITLE
Vorschlag von User: Settings.ini File anstatt appdata

### ISSUE THREAD

**Issue by tox2** [n0ix/SFDL.NET#90]
<Kiffer>	Speichert er den noch datein in /appdata ab
<Kiffer>	Tox2 Könnte man das auch alles im ordner Speichern wo der Loader im einsatz ist

Er meinte damit, ob man die Einstellungen welche in appdata hinterlegt werden auch portable machen könnte, sodass die Settings in eine Settings.ini gespeichert werden?

Wäre das eigentlich möglich unter .net? Denn eigentlich ist der Loader ja portable.

**Comment by n0ix** [comment]
Sehe ich anders. Was ist denn bei einem Update? Da muss man immer dran denken die ini zu kopieren. 

An sich ist es aber natürlich möglich. Sehe da aber eher nachteile als vorteile darin.

**Comment by tox2** [comment]
Ist bei einem Update die alte ini Datei zur neuen Version inkompatible ?
Also mir ist es ja egal wo die settings gespeichert werden, bislang meldete sich nur user 'Kiffer' mit dem Vorschlag. 

Aber gut wenn da ein unnötiger Mehraufwand entsteht und wenn halt mehr nachteile sind als Vorteil.
Können wir das hier schließen 👍

**Comment by n0ix** [comment]
Ne die ini ist nicht zwangsläufig inkompatibel.

Nimms nicht persönlich aber jeden Userwunsch renne ich jetzt nicht hinter her. Die Settings liegen in AppData und fertig.

**Comment by tox2** [comment]
Alles klar, kann ich verstehen weil es unnötiger Mehraufwand ist, bin auch deiner Meinung.
