### ISSUE TITLE
Wegen dem Unrar BUG von praynD, hier die LOGS

### ISSUE THREAD

**Issue by tox2** [n0ix/SFDL.NET#91]
Habe das eine SFDL welches er geladen hat auch mal bei mir geladen. Und hier die logs [SFDL.NET_3_RC1_UNRAR_LOGS.zip](https://github.com/n0ix/SFDL.NET/files/730666/SFDL.NET_3_RC1_UNRAR_LOGS.zip)

1 Testcase. Einfach mal alles laden bis auf das letzte Archiv.  
LOG FileName:  'log - with MultiUnrar_BUG.log'

- Loader entpackt während des Ladens schon mal sauber die Subs. und löscht die Rars auch.
- Download stopp nachdem alle files geladen wurde bis auf einen Part 
- vom Download ein Backup gemacht
- Loader Download wieder gestartet, er ladet alles fertig und entpackt fast zeitgleich die subs und das Haupt Archiv
- subs sind da und werden gelöscht
- Hauptarchiv wird geprüft und anscheinend vom anderen Unrar Prozess als fertig markiert, und daher wird im Anschluss ohne etwas zu entpacken vom Hauptarchiv alles gelöscht.

2. Zuerst alle laden bis auf subs und ein Haupt Part ...
LOG FileName: 'log -With non Parallel MultiUnrar_Chain_works.log'

- Loader laden die 2 fehlenden Files
- zuerst die subs, werden auch sauber entpackt und die subs Archive gelöscht
- danach das hauptpart, das wird auch sauber entpackt und gelöscht
Es tritt kein fehler auf

3. Zuerst alle laden bis auf ein Haupt Part ...
LOG FileName:  'log - with MultiUnrar_BUG2.log'

- Loader ladet das Haupt Part Archiv
- Loader entpackt beide Archive wieder zeitgleich
- subs entpackt ok,  Haupt Archiv entpackt nicht ...
- bei diesem Testcase war das löschen der Archiv deaktiviert.

**Comment by n0ix** [comment]
Gehe ich richtig in der Annahme dass das beschriebene unabhängig von der SFDL auftritt (abgesehen davon das subs enthalten sein müssen) ?

**Comment by n0ix** [comment]
Habe mir das mal an genannten Beispiel SFDL von praydn angeschaut. Also ein richtiger Bug ist es nicht, und wie das genau fixen soll weiß ich auch nicht.

Problem ist folgendes: Im Sub Archiv ist nochmal ein Archiv welches genau so heißt wie das master Archiv vom Film.

![image](https://cloud.githubusercontent.com/assets/17708302/22341575/9c894bf8-e3f1-11e6-84cd-241a8895211b.png)

So und jetzt wird es lustig: Sobald das file dfd-fast.furious.4-1080p.rar vom Loader nicht mehr verwendet wird überschreibt der Unrar Prozess (welcher versucht die Subs zu entpacken) das andere Master Archiv. Dann passt natürlich gar nix mehr. 

Ich könnte es jetzt so ändern das beim entpacken nicht überschrieben wird - das ist aber auch das einzige sinnvolle was mir einfällt.

**Comment by tox2** [comment]
Könnte man Subs Archive nicht immer in einen Unterordner entpacken lassen?
Weil in der Regel bei den Subs im Archiv-Namen auch immer Subs drin steht. :)

**Comment by n0ix** [comment]
Hatte ich mir auch überlegt. Aber wenn dann die RAR schon im einem Unterordner liegt (eg Subs) dann wird daraus Movie\Subs\Subs. Das ist dann auch wieder doof.

**Comment by tox2** [comment]
Also ist das hier eigentlich kein Bug vom Loader sondern vom Upper der das so gepackt hat oder ?
Würde jetzt dafür nichts coden um solche Fälle abzufangen.

Wobei wäre es möglich dass das Unrar nie Vorhanden Files überschreibt, sondern einen Fehler ausgibt ?
Wenn dann nämlich ein Fehler auftritt, weiß der Loader auch Bescheid.

**Comment by n0ix** [comment]
> Also ist das hier eigentlich kein Bug vom Loader sondern vom Upper der das so gepackt hat oder ?
> Würde jetzt dafür nichts coden um solche Fälle abzufangen.

Ja so sehe ich das.

> Wobei wäre es möglich dass das Unrar nie Vorhanden Files überschreibt, sondern einen Fehler ausgibt ?
> Wenn dann nämlich ein Fehler auftritt, weiß der Loader auch Bescheid.

Werde es so ändern das keine Files überschrieben werden. Fehler ausgeben wird schwierig da ich diesen Parameter ja nur der Unrar Binary übergebe. Die gibt dann nicht entsprechendes zurück (glaube ich)

**Comment by tox2** [comment]
Oje das SFDL ist einfach nur Broken. Gratulation an den Upper welcher das so geschafft hat.

Ich lade gerade das ganze nochmal runter und nun ist es ja so weil die subs im Paket ganz oben sind diese zuerst geladen werden und entpackt werden.

Dann ist auf der HDD das Archiv: "*****.4-1080p.rar" ja schon mal vorhanden. Und wenn der Loader dann  das Andere Archiv ladet, ist bei mir laut Loader Settings das so drinnen das ja die vorhandenen Files fortgesetzt werden. im Endeffekt kommt dann auch ein CRC Error bei raus. 

Lösung für das habe ich jetzt nicht aber ich merke es hiermit mal an.

**Comment by tox2** [comment]
Ok hab noch was hier das log:
Und zwar da jetzt beim entpacken nichts überschrieben wird kommt ständig die Meldung nach jedem fertig geladenen Part, 'Entpacken ist fehlgeschlagen!'

http://www.xup.in/dl,99454430/log.log/

**Comment by tox2** [comment]
Nachtrag das folgende Log zeigt nochmal das jetzt ein weiteres Archiv komplett ignoriert wird.
Somit zwar die Subs entpacken werden aber das andere Archiv nicht mehr.


http://www.xup.in/dl,11543070/log_-_No_Unrar_of_2nd.log/

**Comment by n0ix** [comment]
Habe jetzt ja einige sachen gefixxt - muss man sich nochmal mit RC3 anschauen ob da das ganze noch so auftritt.

**Comment by tox2** [comment]
So hab mir nochmal das angesehen das SFDL Ladet und entpackt alles sauber 
Somit Closed
