### ISSUE TITLE
Download Liste: Die Checkboxen können versteckt werden, Spaltenlinie verschiebbar

### ISSUE THREAD

**Issue by tox2** [n0ix/SFDL.NET#92]
![bug_checkbox_hidden](https://cloud.githubusercontent.com/assets/23582323/22436102/f585ef52-e722-11e6-9df1-9521d8059562.PNG)

Die erste Spalte könnte man auf eine fixe Breite einstellen um das zu verhindern. 

Ist natürlich jetzt nur ein kleiner Optik Bug.

**Comment by n0ix** [comment]
Habe mal etwas gegogglet. Das umzusetzen ist richtig aufwendig. Ich werde mal schauen ob ich was finde was sich gut einbauen lässt. aber ich glaube es wird darauf hinauslaufen dass man mit dieser Optik Macke leben muss.

**Comment by tox2** [comment]
hab ein wenig gesucht um dir vielleicht eine coole Lösung anbieten zu können. Bislang habe ich das hier gefunden. 
https://blogs.msdn.microsoft.com/atc_avalon_team/2006/04/10/fixed-width-column-in-listview-a-column-that-cannot-be-resized/

Aber ich denke das  hast du auch gefunden und als etwas umständlich gesehen. 

Ich werde noch ein wenig weiter suchen. Vielleicht gibt es ja was einfaches. :D
