### ISSUE TITLE
Main Package | Sub Package expand ?

### ISSUE THREAD

**Issue by tox2** [n0ix/SFDL.NET#94]
Die Funktion 'Alle Pakete einklappen ausklappen', funktioniert bei mir nur für Sub Pakete. 
Falls die Root Pakete eingeklappt sind, hat die Funktion keine Auswirkung es wird weder Ausgeklappt noch eingeklappt. 

----

Zudem ist ein neu geöffnetes SFDL MainPackage immer eingeklappt.

**Comment by n0ix** [comment]
Hallo,
das ist mir auch schon aufgefallen. Wollte eigentlich selber dafür eine Issue aufmachen - habe ich dann aber wohl vergessen....

Der Fehler besteht seitdem ich den View so geändert habe sodass die SubPackages besser dargestellt werden. Ich habe es nicht hinbekommen das die Root Pakete sich korrekt verhalten.

**Comment by n0ix** [comment]
**Kleines Update**: Habe etwas rumprobiert und auch mal in ein paar Foren gefragt  --> Keine Lösung. Sprich das wird vorerst so bleiben. Ich hoffe ich finde noch eine adäquate Lösung.

**Comment by tox2** [comment]
Das ist echt seltsam, wenn man mit der Maus drauf drücken kann, damit das erweitert wird muss das doch irgendeine Funktion aufrufen, welche man dann auch anders nutzen kann. 
Aber vielleicht liegt der Bug auch einfach bei MahApps :D

**Comment by n0ix** [comment]
Nein, kein Bug von Mah Apps. Mein Problem ist dass ich das Binding für Property "isExpanded" im XAML Code (WPF) nicht hinbekomme da das Sub-Sub Items sind.

**Comment by tox2** [comment]
Ehm vielleicht ein blöder Einwand aber kann man es nicht so machen ? 

`<Expander IsExpanded="True">` für die Main Packages und für die Sub Packages 
`<Expander IsExpanded="{Binding Items[0].IsExpanded}">` das belassen ?

Dann ist wenigsten das Paket ausgeklappt beim öffnen. Also per Default ausgeklappt statt zu.

Wie man das coden weis ich nicht aber ich denke weil man das Binding das so setzt geht es nur für sub pakete. 

Hier habe ich was gefunden was dem jeweiligen Expander einen Namen gibt um dann speziellen diese setzten zu können, LINK : http://stackoverflow.com/questions/17237299/closing-just-one-expander-within-another-expander-in-wpf-vb-net

Vielleicht gibt es auch hier einen Hinweis wie man es machen kann: http://www.c-sharpcorner.com/UploadFile/mahesh/using-xaml-expander-in-wpf/

Ich verstehe leider das zusammen spiel zwischen vb und xaml fast gar nicht :D 

Gib es denn eine andere Variante außer der mit dem Bindung auf den Expander zuzugreifen?

**Comment by tox2** [comment]
So wie hier der sagt geb dem Expander einen namen und ab gehts :D 
https://social.msdn.microsoft.com/Forums/vstudio/en-US/98283bfc-338a-4ef5-b559-660e6db46bff/create-collapseexpand-button-to-collapse-or-expand-all-the-expander?forum=silverlightarchieve

**Comment by n0ix** [comment]
Habe es jetzt soweit hinbekommen das die Sub-Packages eingeklappt und erweitert werden können. Die Hauptgruppe (also des Container Selbst) bleibt standardmäßig ausgeklappt kann aber manuell eingeklappt werden.

![proof](https://cloud.githubusercontent.com/assets/17708302/23760322/97dc379a-04ef-11e7-8257-f38255fe5047.gif)

**Comment by tox2** [comment]
ist im Commit https://github.com/n0ix/SFDL.NET/commit/ee75c8394da1ec68be2e4b7d35466c32fddc6de4 drinnen oder ? :D 

sieht gut aus. das verhalten habe ich auch mit 
`<Expander IsExpanded="True">` im xaml geschafft 
Top. 👍

**Comment by tox2** [comment]
mir scheint irgendwie das die Sachen im code bzw. commit des öfteren auf falsche Issue sachen zeigen wie das commit https://github.com/n0ix/SFDL.NET/commit/53afc341a16cf99fd06c5d70a2e0d1fb674ca9b2 auf #109 statt auf #112  und das 
https://github.com/n0ix/SFDL.NET/commit/ee75c8394da1ec68be2e4b7d35466c32fddc6de4 auf #3 statt auf #94

**Comment by n0ix** [comment]
Ja war mein Fehler habe das paar sachen durcheinander gebracht. Ist aber nur kosmetik
