### ISSUE TITLE
Fast richtige Download Prozentanzeige, Bug Meldung von goofykill via SB

### ISSUE THREAD

**Issue by tox2** [n0ix/SFDL.NET#95]
Hier kurz die Beschreibung er hat eben ein SFDL geladen, welches nur eine *.avi datei ladet.
Wenn man jetzt zb das erste mal das laden beginnt dann steht unten in der Task Meldung die Prozent welche geladen wurden.

Der bug tritt jetzt dann nach dem ersten start stop auf. wenn der Download sagen wir 20% geladen wurde danach wieder fortgesetzt wird fängt die Zahl für die Prozent-anzeige wieder bei 1% an statt 21%
Siehe Bilder.

![1st load_attempt](https://cloud.githubusercontent.com/assets/23582323/22478492/6039f5c4-e7ea-11e6-997e-46e9aa23e394.png)
![2nd load_attempt](https://cloud.githubusercontent.com/assets/23582323/22478496/62659754-e7ea-11e6-9bb0-e9d5f884d01c.png)
[log_Prozent_Bug_SingleFile.zip](https://github.com/n0ix/SFDL.NET/files/742797/log_Prozent_Bug_SingleFile.zip)

Wenn jetzt aber schon Download Parts fertig wären wie zb. part01 part 02 (100% geladen), werden diese auch berücksichtigt in der  Prozent-anzeige.

**Comment by tox2** [comment]
Mir ist aufgefallen in der nicht springenden version der Prozentanzeige ist das beschrieben verhalten hier wieder treffend. man fängt nach start stop eines Downloads immer bei 0 % an.

Wird wohl nur einer Line of code liegen :)

**Comment by tox2** [comment]
In RC4 ist das ganz oben beschrieben wieder da

**Comment by n0ix** [comment]
Hm, also der ETA fängt wieder bei 0% an. Was an sich ja nicht wirklich falsch ist. Das rührt jetzt vermutlich daher das die Files automatisch demarkiert werden. Damit werden diese nicht mehr in die ETA Kalkulation einbezogen. Ich sehe das wie gesagt nicht als Bug bzw. notwendig das zu ändern.

**Comment by tox2** [comment]
ich verstehe nun denn mich hat es eigentlich nie sonderlich gestört, wurde ja von goofykill als solches Fehlverhalten des Loaders interpretiert. :D 

ist jetzt halt Ansichtssache, aber bevor durch das beheben dieses noch andere Bugs entstehen würde ich ja nichts ändern. :D
