### ISSUE TITLE
Window is not brought to Foreground

### ISSUE THREAD

**Issue by tox2** [n0ix/SFDL.NET#96]
Ich denke denn ersten hatte ich auch kurz in einem Issue angeschnitten, wo ich meinte man könnte sich denn Speicher button Sparen und nur beim Exit des Einstellungsfenster die Sachen speichern.

Habe das ganze hier mal eingetragen, weil ich diese Vorschläge durchaus sinnvoll finde. Solange diese  auch so erwünscht sind. 

Aber hier nochmal das von tenti:

> Zitat von tenti 

- Wenn man die Einstellungen editiert hat und dann auf "Speichern" klickt, sollte sich das Einstellungsfenster automatisch schließen. Es ist unnötig, hier nochmal extra das Fenster manuell schließen zu müssen. 

- Wenn der SFDL Loader minimiert ist, und ich einen Doppelklick auf eine .sfdl Datei mache, deminimiert sich der Loader nicht automatisch, das könnte man noch umsetzen.

- Wenn das Verzeichnis auf dem FTP nicht gefunden wurde, kommt "try ftp link, server is probably down". Fände hier "Directory not found" o.ä. besser.

**Comment by n0ix** [comment]
Vorschlag 1 und 2 konnte ich umsetzten.

Der dritte Punkt sich so nicht direkt umsetzten lassen.

Hintergrund ist dass nicht einfach auf das Verzeichnis prüfen kann da dass bei tagged Servern eben nicht funktioniert (ist ja auch sinn des taggens.) Daher bekomme ich auch keinen Fehler sondern einfach nur keine Dateiliste zurück - Warum ich keine Dateien auflisten konnte allerdings nicht.

**Comment by tox2** [comment]
1 und 2 funktionieren einwandfrei.
Falls 3 nicht mehr kommt kann man hier schließen.

**Comment by tox2** [comment]
1. Geht soweit noch in RC4
2. Leider nicht mehr, keine Ahnung warum nicht, aber egal welche SFDL ich via Doppelklick öffne der Loader bleibt minimiert

**Comment by n0ix** [comment]
Witzig - bei mir gehts. Hab da auch nix geändert. In der OpenSFDL funktion steht auch nach wie vor:

```
        If Me.WindowState = WindowState.Minimized Then
            Me.WindowState = WindowState.Normal
        End If
```

**Comment by tox2** [comment]
Stimmt mein Fehler es ist ja nicht minimiert sonder nur von anderen Fenster wie Zb. Chrome und Windows Explorer verdeckt. gibt sowas wie  If Me.WindowState = WindowState.NotInFrontThen ...
Also wenn das Fenster nicht aktiv vor dem User ist ?

**Comment by n0ix** [comment]
Es gibt die Eigenschaft TopMost. Allerdings wüsste ich nicht wie man erkennt ob das Fenster im hintergrund ist.

**Comment by tox2** [comment]
Not TopMost ?

**Comment by n0ix** [comment]
Mit TopMost kann man glaub nur bestimmen ob es im Fodergrund ist, aber nicht abfragen. Geht aber bei WPF eh nicht...

**Comment by tox2** [comment]
verstehe ich es richtig ein Applicantion Active heißt das aktiv mit dem Programm gearbeitet wird also das Fenster wurde zb. mit einem Maus Klick aktiviert. Wenn es dann von anderen Fenstern überdeckt wird ist es ja nicht mehr aktiv und ist als Deactive markiert. dann wäre das der gesucht Zustand für die IF Abfrage ?

**Comment by n0ix** [comment]
Genau, scheint auch so zu funktionieren (nach einem kurzem Test)

**Comment by tox2** [comment]
Möchte hier nochmal kurz nachfragen, verwendest du windows 10 ?
denn bei mir ist es so das wenn ich jetzt denn Loader maximiert deactive mit Chome bzw. FileExplorer überdecke der Loader nicht geöffnet wird sonder das TaskIcon unten blinken anfängt.

An der stelle ich denke nicht das es notwendig ist das ganze auf biegen und brechen zu implementieren.
Dennoch auch hier die Frage könnte das hier das Problem lösen ?
http://stackoverflow.com/questions/5282588/how-can-i-bring-my-application-window-to-the-front#11941579

**Comment by n0ix** [comment]
Ich nutze Windows 10, aber kein Chrome. Auch wenn ich das Fenster maximiere geht das bei mir. (hab es auch extra oder IDE probiert ;-) )

**Comment by tox2** [comment]
Also bei **dir** blinkt nichts unten in der Task Leiste wenn der Loader von irgendeinem Programm verdeckt wird. Und der Loader springt nach dem öffnen einer SFDL im Windows Explorer in Vordergrund ?

Wenn ja bei mir springt er eben nicht in den Vordergrund, es blinkt einfach nur unten in der Task Leiste.

**Comment by tox2** [comment]
So sieht es bei mir aus im Video... 
http://www.xup.in/dl,71315595/Vordergrund_unterschied.mp4/

**Comment by n0ix** [comment]
Hm keine AHnung. Funktioniert bei mir so. Aber wie gesagt - weiter Zeit reinstecken werde ich da nicht. Ist ja gut das es dann blick. dann weiß man das da etwas passiert.

**Comment by n0ix** [comment]
Noch ein kleiner Nachtrag: Das von dir beschriebene verhalten tritt auf wenn man ein Passwortgeschütztes SFDL File öffnet.
