### ISSUE TITLE
Video welches ein Paar Bugs und Verbesserungsvorschläge aufzeigt.

### ISSUE THREAD

**Issue by tox2** [n0ix/SFDL.NET#97]
Hey N0ix, in dem Video sind ein Paar Sachen schon behoben worden andere dazu gekommen.
Vielleicht kann man das eine oder andere Verhalten besser machen oder verbessern.

- Im alten Loader werden Automatisch vorhanden Parts beim Starten des Loaders abgewählt, kann man das auch im v3 machen lassen ? und im Status das Part als bereits vorhanden markieren.

- Der "Anmeldeversuch Fehler", ist das in der Regel auch bei vollen Servern der Fall wenn diese nur eine bestimmte User Anzahl erlauben oder bei Servern die offline sind. Wäre es Möglich da ein Auto Retry nach 30s zb. zu machen?

- Die ETA Berrechnung dauert jen ach File Größe und Download Speed sehr lange. Könnte man das irgendwie beschleunigen ?

- Das ist auch sicher schon bekannt aber im Video sieht man auch nochmal denn nutzen, wenn man die Speedreport erstellt kopiert, wäre der Inhalt des Speedys wertvoller.

- Das der Speedy seltsam werte annimmt, könnte in der v3 RC3 dann behoben sein. Aber geladene Größe stimmt nicht, weil er hat ja in dem Fall nichts geladen war ja "Anmelde Fehler".

http://www87.zippyshare.com/v/zLiiAiJS/file.html
http://www.xup.in/dl,27154878/log_der_Session.log/

gruß tox2 :)

**Comment by n0ix** [comment]
Ok fassen wir mal zusammen:

Datein auslassen welchen bereits heruntergeladen wurden wenn der Loader neu gestartet wird

- Retry erlauben/aktivieren wenn ein Auth Fehler auftritt
- ETA Berchnung optimieren
- "Mini Speedreport" in den Taks anzeigen

Die berechnung der Downloadgröße etc. sollte bereits behoben sein.

**Comment by n0ix** [comment]
Bzgl. Mini Speedreport - Wäre sowas ok?

![image](https://cloud.githubusercontent.com/assets/17708302/22799580/a227b142-ef06-11e6-817e-f0ca98db923e.png)

**Comment by n0ix** [comment]
Das mit dem Retry sollte eigentlich schon so funktionieren. Hast du mir zufällig das File wo das vorkommt?

**Comment by tox2** [comment]
Hast 2x PN :) 
Hoffe die helfen dir weiter mit den Retrys.

Das mit dem Speedy im Task hab ich mir genau so vorgestellt 👍

**Comment by tox2** [comment]
Vielleicht kann man ja das mit dem Anmelden am Server ja auch ändern ich weiß ja nicht wie die FTP Lib. das macht. Aber wäre es Möglich zu Beginn der Download Session sich am FTP Server Anzumelden und erst wenn alle Parts geladen wurde mit Ende der Download Session sich wieder vom FTP Server abmelden ? 

Es scheint ja so als ob sich der Loader bei jedem einzelnen Part Neu anmelden muss.

**Comment by n0ix** [comment]
Das nur eine Session genommen wird habe ich schon so gut wie möglich eingebaut/umgesetzt. Ich muss aber zugeben das ich auch noch nicht zu 100% verstanden habe wie das Session Handling der FTPLib funktioniert.

Der Loader ist auch so "schlau" sodass er erkennt wenn der Server voll ist und dann nur noch mit 1 Thread lädt. Allerdings ist es nicht so trivial zu erkennen ob es sich um einen "normalen" Fehler handelt oder einem Fehler/Disconnect etc. weil der Server voll ist.

Ich habe auch etwas rum getestet - die Retry funktion geht prinzipiell. Ich werde die Tage auch mal versuchen es mit einem lokalen Filezilla das etwas zu provozieren. Etvl. kann ich das dann besser testen.

**Comment by tox2** [comment]
Zur Not kannst du ja denn Entwickler um ein Einsatz Beispiel Fragen so wie der eine das gemacht hat.
Vielleicht hat er auch eine gute Dokumentation seiner LIB.

https://github.com/ArxOne/FTP/issues

**Comment by n0ix** [comment]
Habe mir das heute nochmal angeschaut und meinen Logik Fehler gefunden. Jetzt nutzt der Loader nur eine Anmeldung. Das Parsing der FTP Fehler habe ich auch nochmal neu strukturiert sodass die "ServerFull" Erkennung nun besser funktioniert sollte. Außerdem funktioniert die Retry Funtktion nun etwas zuverlässiger.

Da ich aber befürchte das sich durch die ganze Änderung paar andere Fehler eingeschlichen haben lasse ich hier mal noch offen^^

**Comment by tox2** [comment]
Alles Klar, solange wir mehr Fehler beheben als produzieren, sehe ich Fortschritt :D

**Comment by tox2** [comment]
Also bislang läuft das mit der Session Umstellung sehr stabil. Bislange keine Bugs entdecken können was das laden angeht und Retry Versuche hatte er auch schon ein paar und dann erfolgreich fortgesetzt.

Speedy zum kopieren ist auch geil.
und die ETA läuft durchaus schneller. Außer wenn man ein File ladet mit über 10Gb da dauert es nach wie vor 10 20s bis was kommt :D 

Aber sonst alles top, deshalb schließe ich hier mal und wenn ich einen Bug finde erstelle ich einfach eines issue... :D
