### ISSUE TITLE
SFDL First Run Warning , Want Restart "Yes" ?  

### ISSUE THREAD

**Issue by tox2** [n0ix/SFDL.NET#98]
Hey hab gerade die alte RC2 gestartet da kam dann auch gleich der Hinweis das es eine Neue gibt das geht   also super.

Dann die neue geladen entpackt und beim ersten Start wird ja gefragt ob man als Admin neu starten will.
Ich habe Ja gewählt aber der Loader startet nicht neu.

Ich vermutet weil der Loader selbst das RunAsAdmin startet (subrun/invoked). Und da der Prozess ja noch läuft öffnet er nicht. Ich habe dazu ein Video um zu sehen wie das bei mir abläuft. Vielleicht ist es auch nur auf meinem System so. 

http://www.xup.in/dl,21219533/local_(02).mp4/

**Comment by n0ix** [comment]
Hm evtl. ein timing problem. Ich habe mal in der RunAsAdmin die Wartezeit auf 3 Sekunden erhöht.

**Comment by tox2** [comment]
Jup mit 3 s delay gehts
