### ISSUE TITLE
Die Prozent Anzeige springt in RC3 (siehe Video)

### ISSUE THREAD

**Issue by tox2** [n0ix/SFDL.NET#99]
http://www.xup.in/dl,96745533/local_(03).mp4/

**Comment by n0ix** [comment]
Hm kann den Fehler (auch mit dem selben SFDL) leider nicht nachvollziehen bzw. reproduzieren. War das einmalig oder ist das immer/sehr häufig?

**Comment by tox2** [comment]
Ist mir zur Laufzeit aufgefallen habe dann später nicht mehr darauf geachtet, vielleicht sieht man das nochmal in denn anderen Videos.

**Comment by tox2** [comment]
Hat das Springen vielleicht was mit der CRC Überprüfung zu tun?

Ich hab gerade nochmal das selbe SFDL getestet wieder selber Effekt, mal 1% mal 2% dann wieder 1%...

**Comment by n0ix** [comment]
Wüsste nicht was das mit der CRC Überprüfung zu tun haben soll. Was veranlasst dich zur dieser Annahme?

**Comment by tox2** [comment]
War nur so ein Gedanke aber am CRC kann es nicht liegen. :D 
Aber andere Frage. Die Einzel Parts updaten die Prozente pro Thread oder pro Session ?

also wenn jetzt zb. 4 parts in einem Container/Paket sind. mit Jeweils 25MB.
man dann mit 2 threads ladet. Da muss es ja so sein das zb. bei 5/25MB + 5/25MB = 10MB/100MB also 
in summe müssen die einzelnen (5/25MB) in dem Fall 20% +20% = 10% Gesamt ergeben.
40%/4= 10%
wenn jetzt ein Part auf 24% aktualisiert und der alte aber noch mit 20 % ist dann muss in Summe
44%/4 =11%  sein.

Ich kann mir nur vorstellen das jetzt der 2te Thread mit alten Werten auch die GesamtSumme beeinflusst.
also das zwar der aktuelle stand von Thread1  (11/25MB) = 24% + Thread 2   (5/25MB) = 20% ist. 
Aber der Thread 2 zb. intern noch mit Thread1  (5/25MB) = 20% + Thread 2   (5/25MB) = 20% rechnet.

Und da das jetzt so ist wenn jeder Thread die Gesamt Summe updaten darf. Sozusagen je nach Zustand dann solche Sprünge verursacht werden können.
Man müsste dazu dann die Fortschritte der Einzel Threads alle auf einmal mit einem Watchdog oder einen selbstständigen Thread abfragen oder ? 

Aber ich weiß nicht ob jeder Thread für sich selbst denn Gesamtfortschritt ändern kann oder ob das anders intern läuft.

**Comment by n0ix** [comment]
Hier mal den Code welcher den ETA bererchnet:

`Private Function CalculateETA(ByVal _mytask As AppTask) As Boolean

        Dim _log As Logger = LogManager.GetLogger("CalculateETA")

        While SmartThreadPool.IsWorkItemCanceled = False

            Dim _total_speed As Double = 0
            Dim _total_size As Double = 0
            Dim _total_size_downloaded As Double = 0
            Dim _size_remaining As Double = 0
            Dim _time_remaining As Double = 0
            Dim _percent_done As Integer = 0

            Try

                If WindowState = WindowState.Maximized Or WindowState = WindowState.Normal Then 'Nur berechnen wenn Window Sichtbar


                    System.Threading.Tasks.Parallel.ForEach(Of DownloadItem)(DownloadItems, Sub(_item As DownloadItem)

                                                                                                If _item.DownloadStatus = DownloadItem.Status.Running Then

                                                                                                    If Not String.IsNullOrWhiteSpace(_item.DownloadSpeed) Then

                                                                                                        Dim _raw_speed As String = _item.DownloadSpeed.ToString

                                                                                                        If _raw_speed.Contains("KB/s") Then
                                                                                                            _raw_speed = _raw_speed.Replace("KB/s", "").Trim
                                                                                                            _total_speed += Double.Parse(_raw_speed)
                                                                                                        Else

                                                                                                            If _raw_speed.Contains("MB/s") Then
                                                                                                                _raw_speed = _raw_speed.Replace("MB/s", "").Trim
                                                                                                                _total_speed += Double.Parse(_raw_speed) * 1024
                                                                                                            End If

                                                                                                        End If

                                                                                                    End If

                                                                                                End If

                                                                                            End Sub)


                    System.Threading.Tasks.Parallel.ForEach(Of DownloadItem)(DownloadItems, Sub(_item As DownloadItem)
                                                                                                If Not _item.DownloadStatus = DownloadItem.Status.None Then
                                                                                                    _total_size += _item.FileSize
                                                                                                    _total_size_downloaded += _item.LocalFileSize
                                                                                                End If
                                                                                            End Sub)

                    _percent_done = CInt((_total_size_downloaded / _total_size) * 100)

                    _size_remaining = _total_size - _total_size_downloaded

                    If _size_remaining > 0 And _total_speed > 0 Then

                        _time_remaining = Math.Round(Double.Parse(CStr(((_size_remaining / 1024) / _total_speed) / 60)), 2)

                        If _mytask.TaskStatus = TaskStatus.Running Then

                            If _total_speed >= 1024 Then
                                _mytask.SetTaskStatus(TaskStatus.Running, String.Format("Download läuft - Speed: {0} MB/s | ETA: {1} | {2} %", Math.Round(_total_speed / 1024, 2), ConvertDecimal2Time(_time_remaining), _percent_done))
                            Else
                                _mytask.SetTaskStatus(TaskStatus.Running, String.Format("Download läuft - Speed: {0} KB/s | ETA: {1} | {2} %", Math.Round(_total_speed, 2), ConvertDecimal2Time(_time_remaining), _percent_done))
                            End If

                        Else
                            _mytask.SetTaskStatus(TaskStatus.Running, String.Format("Download läuft - {0} %", CInt((_total_size_downloaded / _total_size) * 100)))
                        End If
                    Else
                        _log.Debug("Nothing to Calculate")
                    End If

                Else
                    Debug.WriteLine("Keine Berechnung Fenster ist runtergeklappt!")
                End If

            Catch ex As Exception
                _log.Error(ex, ex.Message)
            Finally
                Thread.Sleep(500)
            End Try

        End While

        _log.Debug("ETA While beendet!")

        PostDownload()

        Return True

    End Function`

**Comment by tox2** [comment]
hm ok,
Bei` _total_size_downloaded += _item.LocalFileSize ` 
hat das vielleicht andere update zyklen ?

könnte man hier einfach auf den Fortschritts Wert in % der einzel Parts für die Gesamt Prozent nehmen ?
und dann einfach durch die anzahl der Parts dividieren ?

also sowas wie 
`_total_percent_downloaded += _item.Progress_percent_value`
`_percent_done = CInt(_total_percent_downloaded / DownloadItems) `

Kann ja sein das wenn ein FileStream offen ist und gleichzeitig geschrieben und gelesen wird, dass 
die Werte von _item.LocalFileSize dann je nach dem andere Werte annimmt oder ?
Bzw. bei Read Accsess denied einfach ein 0 Byte wert zurückgegeben wird, statt dem tatsächlichen wert.
Was dann die Ursache für die Sprünge ist.

**Comment by tox2** [comment]
Ich hab mal ne Frage kann es sein das wegen der Zeile das so auftritt und daher die LocalFileSize manchmal  intern springt ?

https://github.com/n0ix/SFDL.NET/blob/master/SFDL.NET%203/Classes/DownloadHelper.vb#L416-L437

da steht in Zeile 419: 
`bytesRead = _ftp_read_stream.Read(buffer, 0, buffer.Length)`

und in 431: 
`bytesRead = _ftp_read_stream.Read(buffer, 0, Length)` jetzt würde ich mich fragen müsste hier nicht buffer.Length stehen weil Length alleine ist ja nur 256 der Buffer selbst aber 8192 
siehe length :
`Const Length As Integer = 256`
siehe Buffer : 
`  buffer = New Byte(8192) {}`

welches dann in Zeil 437 übernommen wird:
` _item.LocalFileSize += bytesRead` 

------------

Somit denke ich folgendes passiert hier.
Die Formel sagt ja `_total_size_downloaded / _total_size * 100`. Dann ist wohl LocalFileSize kurzfristig sehr hoch. Damit der Prozentwert hoch sein kann. und ich gehe davon aus das `_total_size += _item.FileSize` sich nicht verringert für die Session. Bzw. ich habe nichts im Code gefunden wo diese  während der Session Laufzeit geändert wird. 

> System.Threading.Tasks.Parallel.ForEach(Of DownloadItem)(DownloadItems, Sub(_item As DownloadItem)
                                                                                            If Not _item.DownloadStatus = DownloadItem.Status.None Then
                                                                                                _total_size += _item.FileSize
                                                                                                _total_size_downloaded += _item.LocalFileSize
                                                                                            End If
                                                                                        End Sub)
                _percent_done = CInt((_total_size_downloaded / _total_size) * 100)


-------------

Echt irgendwie seltsam, aber denke du hast da einen besseren Überblick im Code.
Aja und noch ne frage ist das bei dir auch mal aufgetreten oder nur bei mir im Video ?

**Comment by tox2** [comment]
Hab auch noch ein kurzes Video wo ich mich während des Downloads einfach mal aus dem Wlan trenne und dort springt die Prozent Anzeige auch. Obwohl alle Werte LocalFileSize und FileSize sich technisch nicht ändern können weil ja keine neuen Daten übers Internet reinkommen. 

http://www.xup.in/dl,77203600/local_.mp4/

**Comment by n0ix** [comment]
Hallo, also ich hatte den Fehler eben noch nie, das finde ich ja so komisch.

Das LocalFileSize plötzlich springt kann überhaupt nicht sein da ja immer in 8k Blöcken gelesen wird. Was passieren könnte das die Prozentzahl nach oben springt - aber nach unten  - keine ahnung wie das gehen soll.

**Comment by tox2** [comment]
Sie springt ja auch immer nach nach oben wenn sie spring dann kommt wieder der aktuelle richtige wert. aber beim Springen kommt immer eine Zahl die höher ist aber nie höher als 100%, also bis lang hatte ich noch welche gesehen die höher als 100% waren.

**Comment by n0ix** [comment]
Ok, da hat du recht. Trotzdem will es mir nicht in den Kopf gehen wieso das bei dir springt und bei mir nicht. Tritt das auch bei Einzel SFDL's auf (also nur mit einem Package) ?

**Comment by tox2** [comment]
Ja, in dem Video zb. hab ich nur ein SFDL drinnen.
http://www.xup.in/dl,77203600/local_.mp4/

**Comment by n0ix** [comment]
Ich hatte den Fehler heute auch mal. Ich habe mir das ganze dann gleich angschaut. Ich weiß zwar absolut nicht warum (logisch ist es für mich nicht) aber ich habe in der ETA Funktion die ForEach Schleife  wieder durch die LINQ Funktion ersetzt - jetzt tut es.

```
                    _total_size = DownloadItems.Where(Function(myitem) Not myitem.DownloadStatus = DownloadItem.Status.None).Select(Function(_item) _item.FileSize).Sum
                    _total_size_downloaded = DownloadItems.Where(Function(myitem) Not myitem.DownloadStatus = DownloadItem.Status.None).Select(Function(_item) _item.SizeDownloaded).Sum

                    'System.Threading.Tasks.Parallel.ForEach(Of DownloadItem)(DownloadItems, Sub(_item As DownloadItem)
                    '                                                                            If Not _item.DownloadStatus = DownloadItem.Status.None Then
                    '                                                                                '_total_size += _item.FileSize
                    '                                                                                _total_size_downloaded += _item.LocalFileSize
                    '                                                                            End If
                    '                                                                        End Sub)

```

Ich hatte die LINQ Funktion durch die ForEach Schleife ersetzt da die etwas schneller war. Vermutlich kommt er aber aufgrund dessen dass das dann parallel läuft durcheinander.

**Comment by n0ix** [comment]
Hier mal noch die neue Exe für dich zum Testen:

http://www.xup.in/dl,10662726/SFDL.NET_3.rar/

**Comment by tox2** [comment]
Es liegt wohl daran habe es jetzt mal laufen lassen bei mir und in 60s laufzeit sprang er nicht einmal. Seltsam aber ist wohl fixed
